functions/timber-menu-item.php, readme.txt, tests/test-timber-helper.php, tests/test-timber-menu.php
This PR cleans-up menu trailing slash behavior to no longer overrride user/WP defaults. It should solve #426
=> 426 trailing slash

functions/timber-image-helper.php, tests/test-timber-image.php, timber.php
Hi,
tl;dr: Using the resize filter on a site with WPML translations resulted in broken resized image links, I fixed it (and added non-regression tests).
More details:
- WPML works by changing home_url() from 'example.com' to 'example.com?lang=en'
- timber resize used to build resized url by doing home_url().'...path...'
- mixing the 2 resulted in broken url of 'example.com **?lang=en** /wp-content/.../img-300x500-c-default.jpg'
- I updated resize to use content_url(), which WPML does not touch
- I very slightly refactored timber-image-helper in the process.
Thanks
=> Image resize did not work on WPML sites

functions/timber-loader.php
Add a filter that will allow us to change the location of twig cached files.
This way if someone wants to change the default location and store the caches say on wp-content/cache (see #441) or anywhere else they'll be able to do it.
=> added a timber_cache_loc filter

functions/timber-comment.php
Currently there is no method to get the comment_status. I could be useful to create a frontend that show all comments:
```html
<tr class="{{ comment.status }}">
<td>{{ comment.date | date('d.m.y - h:i:s') }} Uhr</td>
<td>{{ comment.author.name }}</td>
<td>{{ comment.content }}</td>
</tr> 
```
=> added getter for comment_status

lib/timber-post.php
This method is usable for classes extending TImberPost. Setting it as protected still hides it from being called on the instance.
=> Changes visibility to protected on TimberPost::check_post_id()

lib/timber-post.php, lib/timber-term.php, tests/test-timber-pages.php
ref #520 -- this resolves issues raised by @teohhanhui with incorrect guesswork by `TimberPost` which can cause issue on pages like `/category/{my-category}`
=> 520 posts on term pages

timber.php
Problem
-----------
In the original implementation, you implement the following logic:
```
// we look for Composer files first in the theme (theme install)
// then in the wp-content dir (site install)
if (    file_exists( $composer_autoload = __DIR__ . '/vendor/autoload.php' )
|| file_exists( $composer_autoload = WP_CONTENT_DIR.'/vendor/autoload.php' ) ) {
require_once $composer_autoload;
}
```
The first file exists function does not actually check the themes folder. Instead, it loads from the current file directory and checks to see if a vendor folder is found within it --usually this is done when you require a common composer package. However, the second condition does stay constant to the comment above.
Solution
-----------
Let's stay consistent with the comment above, we do the …
=> Let's allow the timber plugin to load the composer autoload from three different locations

lib/timber-image-helper.php, lib/timber-url-helper.php
Hi,
The TimberImageHelper::is_external did not handle the case where upload_dir was overridden.
This PR fixes it.
In addition, I moved the function itself to TimberURLHelper::is_external_content($url).
=> properly detect external image using content_url

lib/timber-post-getter.php, timber.php
handle_post_results is depreciated and an internal function to begin with. It can be safely disposed of
=> Remove handle_post_results

lib/timber-image.php
We're using [WP Offload S3](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) to serve images through S3/CloudFront, and it works most of its magic through hooks in `wp_get_attachment_url()`. Since Timber never calls this function, we're currently using the timber_image_src hook to rewrite the URL string, but that's not super robust.
Passing the ID through as an arg to this filter makes compatibility super simple. Does this seem like a sensible addition? Alternately, any thoughts on a better way to do this?
=> Passing ID thru to 'timber_image_src' filter

lib/timber-helper.php, lib/timber-post.php
Hi,
This is a piece of code from WP core (`comments_template()`) required for Timber to respect properly the default_comments_page setting from the Discussion settings in WP. Without this comments pagination will be broken, missing comments pages can happen (I was getting only 2 pages instead of 3) and first comments would be displayed not accordingly to what's saved in the Discussion settings.
Cheers
P.S Contains my other pull request to add `blockquote` to allowed_tags in `trim_words` and possibility of filtering the `$allowed_tags`
=> Fix for Timber ignoring default_comments_page and missing pages in comment pagination

lib/timber-theme.php, lib/timber-url-helper.php, tests/test-timber-url-helper.php
According to WordPress documentation, path-related constants shouldn't be used by plugin/themes, and it seems the issue was because Timber was assuming the themes folder would always be inside WP_CONTENT_DIR.
By using methods instead of the constants, `{{theme.path}}` returns the right value.
This should fix `PauGNU`'s issue in #619
=> Remove constant usages from TimberTheme

lib/timber-post.php
This enables accessing the comment reply link via {{ comment.reply_link }} in your comments loop.
Fixes https://github.com/jarednova/timber/issues/319
=> Added Reply Link for threaded comments.

lib/timber-site.php
Urls for rdf, rss, rss2 and atom are retrieved
=> Add WordPress feed urls to TimberSite

lib/timber-twig.php
Add a second condition to check if the $date variable contains a unix timestamp. If a unix timestamp is present strtotime returns false. if you have a date formated by acf strtotime returns the unix timestamp.
=> Fix for the ACF date field issue #724

lib/timber-post.php, lib/timber-term.php, tests/test-timber-post.php
This PR addresses a few things (sorry about that) but I tried to limit the reach of the code changed to only that which is relevant.  I think the commit messages give a pretty good summary, but here's the gist of it:
- Add tests & support for calling the `terms`/`get_terms` methods on a `TimberPost` and passing an array of taxonomies to fetch terms for, rather than all of them.  
> It seems as though support for this was intended, but not documented, or tested for, and was not working as such.
- Refactor existing tests for `terms` as well as tags and categories to be cleaner and more readable
- Add a static named constructor for `TimberTerm`, which takes the same arguments as the constructor method.  Usage like `TimberTerm::from('My Term Name')`.  This is also totally compatible with …
=> Add support for TimberPost->terms( array ) & more

lib/image/timber-image-operation-letterbox.php
Get's the quality from WP_Image_Editor() and uses that in imagejpeg. Means quality can be controlled with jpeg_quality filter.
In response to https://github.com/jarednova/timber/issues/693.
=> use WP_Image_Editor() quality for letterbox quality

lib/timber.php, timber.php
- Moved class Timber to lib/timber.php …
- Removed autloading and WP meta data from the class file
- Readded the WordPress plugin file with original content (autloading, instantiation for Timber object)
This PR fixes  issue #833
=> Move class Timber into separate file

lib/timber-post-getter.php
**Issue**
Let's say you have a custom post type called ```job``` and you have a file ```inc/job.php``` that contains a ```class Job {}```. This class just contains some helper functions for your ```job``` post type, filtering etc.
With all that in mind, if you try and then do ```Timber::get_posts(array('post_type' => 'job'))``` it will not work and return the page you are on, rather than the jobs.
**Solution**
Add an extra check to make sure a class extends ```TimberPost``` before using the class (as the doc explains).
**Impact**
This will break (incorrect) implementations that uses classes without extending ```TimberPost```.
**Usage**
No change
=> Ensuring class is subclass of TimberPost

lib/timber-image.php
In a TimberPost, you can access the id [through `post.id` or `post.ID`](https://github.com/jarednova/timber/blob/master/lib/timber-post.php#L628). However with a `post.thumbnail`, you can only use `post.thumbnail.ID`, which doesn't seem intuitive and leads to errors.
This adds `id` to `post.thumbnail` as a duplicate of `ID`.
=> Add id as a duplicate of ID in timber-image.php

lib/timber-image.php
**Issue**
If you have static images that you want to use via ```TimberImage('wp-content/themes/default/hello.jpg')``` it will only support ```.jpg```
**Solution**
Adds a ```private``` variable to the class that lists all image types from https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support and loops over that array to see if any of them exist in the string given.
**Impact**
Negligibly slower
**Usage**
No change
**Considerations**
This version of ```TimberImage``` could do with a little bit more development, currently you would have to hardcode the path to the theme, which isn't great. I tried to add a second parameter ```TimberImage(string, boolean)``` that a user could set to ```true``` to indicate they want a relative path to the theme directory. However it …
=> Adding support for more relative image types

docs/wiki/cookbook-images.md, lib/timber-image.php
Caveat: I have only just started using Timber so this may already be solvable easily.
**Issue**
Using ACF, if you have a repeater field that contains a relationship field, there is no easy way to get the featured image of the post that has been selected in the relationship field. You can init a new ```TimberPost``` however that is adding more logic to the views whilst it can be easily solved within the ```TimberImage``` class
**Solution**
If you pass a post object to ```TimberImage```, it will grab a new instance of ```TimberPost```, get the ```_thumbnail_id``` and re-init ```TimberImage``` with the correct id.
**Impact**
This will be slightly slower than just passing the ID, but in the instance I described above the only way to do this in the first place is this method, it's just moved …
=> Allow post object as parameter of TimberImage()

lib/timber-request.php, lib/timber-site.php, lib/timber.php
**Issue**
There is no easy way to access GET/POST variables in the Twig templates
**Solution**
Add ```site.request``` array that contains ```site.request.get``` and ```site.request.post```
Eg.
/vacancies/?salary=30000
```
Requested salary: £{{site.request.get.salary}}
```
```
Requested Salary: £30000
```
=> Adding request.get/post to TimberSite

docs/wiki/wp-integration.md, lib/timber-function-wrapper.php, tests/test-timber-function-wrapper.php
Adds official (you can currently do `TimberFunctionWrapper('MyClass::staticFunction')`) support for classes in `TimberFunctionWrapper`. Fixes #854 and #843
**Issue**
It's currently not documented that you can do `TimberFunctionWrapper('MyClass::staticFunction')` and also that does not solve the issue with non static functions.
**Solution**
Allows the first parameter of `TimberFunctionWrapper` to be an array, consisting of an `object` (class) OR a `string` that references a class. It seems you need to pass a string for name spaced classes `TimberFunctionWrapper(array('MyNamespaces\Container', 'some_function'))`, however you can also pass a class `object` as the first parameter of the array.
**Impact**
Negligibly slower.
**Usage**
`TimberFunctionWrapper(array($classObject, …
=> Adding support for classes in Function Wrapper

lib/timber-image-helper.php
Fixes #829 
**Issue**
If you do something like `{{TimberImage('http://website.com/my-external-image.JPG')|resize(400, 200)}}` it will generate a new file with the extension lowercased, however it will return the original case of the extension. For example `42123710cb0cd8c9edba9ca4b6210f72-300x600-c-default.JPG` even though the file is `42123710cb0cd8c9edba9ca4b6210f72-300x600-c-default.jpg`
**Solution**
It's a very simple solution, and something that I think should be updated further down the road. It keeps track of if an image is external in `$external`, then checks if it has gone through a resize operation, if both are true `strtolower`s the whole string.
The other thing to consider is, we can't just blanket `strtolower` any external images, as if it isn't resized it will reference the …
=> Lowercasing extensions of externally reszied images

.github/ISSUE_TEMPLATE.md
This solves #870 by adding a template for issues.
Lots of random support queries were coming into GitHub, which should instead be directed to StackOverflow. Even "good" issues w actual bugs would come in without clear details and ways to reproduce
Use GitHub's new issue templates to provide issue-filers with guidelines and a format
None, just an extra file in the repo
No change
This should lead to a matching PR template; for which I love this format that @connorjburton introduced to us
=> ref #870 -- added issue template

composer.json
Sorry original PR was branched from a branch.
The composer file references http://wpackagist.org however that causes an error when doing `composer install` due to https://getcomposer.org/doc/06-config.md#secure-http.
Fix just changes the reference to `https`
=> Updating http reference in composer.json to https

tests/test-timber-dates.php
This solves #867 - also added test to confirm functionality.
```php
$context['amsterdam'] = new DateTime('now', new DateTimeZone('europe/amsterdam'));
```
```twig
{{ amsterdam|date('g') }}
```
Will return the wrong time.
The `date` filter does not honour the `DateTimeZone`
We add the offset of the timezone onto the date (offset can be negative, so `04:00 + -1 = 03:00`)
None
No change
There may be more instances of this, we need to be aware of honouring timezone offsets.
=> Ref #867 - Fixes timezone when using date filter

lib/image/timber-image-operation-resize.php, lib/timber-post.php, tests/test-timber-image-resize.php, tests/test-timber-post-preview.php
useful when cropping vertical 9:16 images or creating Material Design cards.
I think that the image used in unit tests should be changed before writing new tests for 'top-center' and 'bottom-center' positions
=> implementing new crop positions: 'top-center' and 'bottom-center'

tests/test-timber-function-wrapper.php
Very simple, just adds second test for `TimberHelper::function_wrapper` to make sure `array('ClassName', 'FunctionName')` works as the first parameter.
=> Adding second test for function wrapper

lib/timber-post.php
Fixes #677 
`post.parent.children` will return all children of that post, regardless of status, as described in the codex here. https://codex.wordpress.org/Function_Reference/get_children
Explicity requests `publish`ed children only.
Maybe someone somewhere is using this and doesn't realise their children are not published.. maybe but I doubt it.
No change
None
=> post.parent.children now will only return published posts

lib/timber-post.php, tests/test-timber-post.php
This solves #836. This needs review as it touches a few important bits of code. @jarednova 
Also still needs tests that I will write once functionality is complete.
If you use `TimberPost` in your PHP files and try to preview the page it won't show any previews.
If `$_GET['preview']` is set and the `nonce` verifies we then go onto to test if the current user _should_ be seeing this post/page, if they are we get the latest revision and return the ID of that post.
The ID will also fall back to the original post if a revision isn't found or the user doesn't have permissions to see the post preview.
Possibly bad ones if we miss something.
No change
Okay a few things:
1. I'm using `$_GET` - is there a wrapper around this? I don't see why `$_GET` wouldn't be fine in this situation, just …
=> [Needs Review] Ref #836 - Allow to preview when using TimberPost

lib/timber-post.php, tests/test-timber-post-preview.php, tests/test-timber-post.php
This picks up #876:
@connorjburton I made two changes I want to call your attention to.
First on `TimberPost::get_post_preview_id` I switched the assumption on true/false. For security reasons (admittedly, hypothetical) it's better practice to start with a no-access assumption. That way if something screwy happens with permissions, the code makes the assumption that viewing the post preview should _not_ be allowed.
On the test itself (`testPreviewContent`), PHPUnit assertEquals compares:
```
$this->assertEquals( Expected Thing, Thing to Test );
```
The test will still pass either way, but the formatting of errors/failures will read correctly. 
All this is just tweaks on your earlier work — give it a look and if you like what you see this should be good to (finally) merge!
=> 876 preview tests

lib/timber-post.php, tests/test-timber-post-preview.php
Fixes #130 
You can't customize what tags `get_preview` returns
Allows the `$strip` param to accept a string of tags to strip whilst keeping original `true`/`false` functionality and not effecting the `$strip` tag itself so when it's used later on in the function everything else works as before.
None
`get_preview(length, force, readmore, tags, end);`
None
=> Allowing allowable_tags customization

docs/wiki/getting-started-setup.md
the link is in the 3rd step here http://jarednova.github.io/timber/#use-the-starter-theme
=> docs: Fix broken anchor link

lib/timber.php
Fixes #511 
If you are using a plugin such as Display Widgets of Dynamic Widgets, the sidebar may be active but not actually containing content, as you can choose which widgets in a sidebar are shown on what page, however `is_active_sidebar` will only check if a sidebar has _any_ widgets.
We just `trim` the result so that we don't have any empty content.
Normally I wouldn't put a fix in for plugin compatibility (massive rabbit-hole) however this is literally just a `trim`.
None
No change
I can't see how this would effect any existing code, if you do a trim in `twig` as some people were suggesting in #511 it will still work.
=> Adding trim around get_widgets

lib/timber.php
Fixes #639
If you have an archive with no posts, yet use `Timber::get_pagination`, `next` will return a link.
Overrides the array property to an empty string if `total` is `0`
I can't think of any backwards compatibility issues here
No change
None
=> Fixing next link showing up in pagination with no posts

lib/timber-image-helper.php
Fixes #894 
Some JPG files are not deleted, when they were generated through [`tojpg` Twig filter](https://github.com/jarednova/timber/wiki/Image-cookbook#converting-images) that was used on a PNG file.
Change generated `tojpg` files to have `tojpg` in the filename.
Added two more calls to `delete_generated_files` with specific regex for the `tojpg`
Negligibly slower
No change
I tried combining the two calls to one, but couldn't get it to work with `glob` correctly.
=> Fixing issue with tojpg not being deleted

lib/timber-image-helper.php, tests/test-timber-image.php
Fixes #498
If your settings are to *not* upload in year/month folders, when you get file info the `subdir` will be `/` which causes a double `/` before the image filename, e.g
`http://site.com/wp-content/uploads//1024x1024-400x400x-c-default.jpg`
Don't register the `/` if it's on its own.
None
No change
I think this will fix #498, but they were reporting backwards slash, but I am thinking that is due to system environment.
=> Fixing extra slash on images not in year/month folders

lib/timber.php, tests/test-timber-twig.php
Fixes #863 
Tests (and possibly existing code in themes) using `compile_string` currently use `Twig_Loader_String` which is not recommended and deprecated since `1.18.1`
Hooks into the existing Twig environment and loads the template via that.
None
No change
None
=> Refactoring Twig_Loader_String existing Twig environment

docs/wiki/wp-integration.md, lib/timber-helper.php
The Wiki documentation of `TimberHelper::function_wrapper` contains an error regarding the new possibility to pass in Classes or Objects. They have to be passed in as an Array. Also the DocBlock of `TimberHelper::function_wrapper` does not reflect that change.
Updated the DocBlock (with the updated DocBlock that is shown in the wiki documentation) and added the `array()` part in the wiki documentation.
=> Fix function_wrapper docs

lib/timber-image.php, lib/timber-twig.php
**Ticket**: #496 
Users are experiencing an error `Not able to init in TimberImage with iid=` - this leads me to believe `TimberImage` is being initialised with an empty parameter, as `iid` is false.
Adds another error for if a user hasn't entered anything for the first parameter.
Extra error
Nope
This may solve the issue, or just expose a larger issue.
Not sure tests are necessary here.
=> Adding more descriptive errors for initing TimberImage without src

bin/deploy-to-wp-org.sh, bin/timber.php
**Ticket**: #911 
With the new Composer setup, usage as a WordPress plugin is no longer native.
This re-introduces the `timber.php` file (in the `bin` directory) to be used in the build script. When deploying to WP.org, this file is copied into the main directory so that it's read by the WordPress plugin page.
Not really. This will not interfere with the theme-based Composer installation.
Is it worth adding docs for the edge-edge case of someone installing through non-wp.org but who still want it to use Timber as a plugin versus a theme dependency?
To test, you'll need to manually move `/bin/timber.php` to `/timber.php`
=> Updated WP.org build script with timber.php file

lib/timber-twig.php
**Ticket**: #412 
Full range of translation functions aren't exposed to context
Expose rull range
Some users may already have added `translate` or other functions to their context, I assume this will override those functions?
All translation functions are exposed to context, e.g`{{translate()}}`
I don't think they are necessary, we would just be testing Wordpress' functions.
=> Exposing all translation functions

lib/Post.php
**Ticket**: #944 
ACF fields that container a post would return as `WP_Post`, not `Timber\Post`
If `get_field` returns an array, we run through each array element to see if it's either an array(1) or is an instance of `WP_Post`(2)
1. We run `$this->convert` again recursively till `$ele` is no longer an array
2. We pass the `WP_Post` into `Timber\Post`
None that I know of, if someone already has done this manually, it will just end up passing `Timber\Post` into `Timber\Post`
There is less usage as you won't have to cast `WP_Post` to `TimberPost` anymore
Performance I think should be good, I don't think `instanceof` or `gettype` are expensive?
No tests added, may add some after namespacing is merged.
=> ACF posts now return as TimberPosts

lib/Admin.php
Because of the methods removed in #934 — people could be surprised when elements of their theme doesn't work.
Add an upgrade warning so people with a perfectly-fine WordPress theme don't upgrade for the sake of upgrading. The warning urges people who have a legacy site to not upgrade and directs others to an [Upgrade Guide](https://github.com/timber/timber/wiki/1.0-Upgrade-Guide)
None
In the future, we'll need a bit of code to NOT show this when going from 1.0 to 1.1 and the best way to manage messages for different version bumps.
No automated tests included; but tested locally to ensure it shows up when it's supposed to show up
=> ref #934 -- added upgrade warning for WP.org

lib/PostGetter.php
**Ticket**: #935 
**Reviewer**: @
Passing an array for `post_type` causes a warning.
Checks if it's an array before doing `class_exists`
None
None
None
None
=> Fixing post getter array bug

lib/Term.php
Simple line removal to fix bug with "use" statement
#984
=> remove "use" statement for Term in the Term file

lib/User.php
**Ticket**: #983
User avatar just returned a URL.
Now returns a `Timber\Image`
If someone has already done `TimberImage(user.avatar)` it will just return the same `TimberImage`
`TimberImage(user.avatar)`
I am not sure the benefit of improving this any further, unless we have reason to.
None included
=> User avatar is now a TimberImage

lib/Image.php, tests/test-timber-image.php
If the `TimberImage` or `Image` function in twig was passed a `\Timber\Image` object it would cause a compile error.
If passed an `Image` object, the `\Timber\Image::init` function will now grab the ID and re-initialize
It would be bad practice to do this, but it's worse to have a silent error. 
No.
Rather than re-initialize, the `Image` object should be able to grab the public assignments of properties so that no new queries need to be run.
New Unit tests included demonstrating failing behavior and passing behavior
=> You can now re-initialize a Timber Image with a Timber Image

lib/Timber.php, tests/TimberImage_UnitTestCase.php, tests/Timber_UnitTestCase.php, tests/test-timber-context.php
**Ticket**: #977
Calling `get_context` inside the `timber_context` filter is common, and at the moment causes an infinite loop.
This would also not cache any data so is unnecessarily slow
Adds memoization to the `get_context` function so it will only run the filters once (Fixes infinite loop) and also is faster when using `get_context` multiple times.
Faster, fixes issue with infinite loop.
No change
This needs some real world testing, will get the guys on the ticket to give it a go.
No tests included.
=> Adding memoization to get_context

lib/Helper.php, lib/Post.php, tests/test-timber-helper.php, tests/test-timber-post.php
Many people (especially on the WordPress.org forums) have reported problems with the deprecated `TimberHelper::get_comment_form` function. Well of course they have, it was removed!
https://wordpress.org/support/topic/fatal-error-class-not-found-in-101?replies=2
https://wordpress.org/support/topic/get_comment_form-returns-empty?replies=4
... that said, the problem they're running into isn't entirely of their making. The `single.php` file in the Starter Theme had a call to `TimberHelper::get_comment_form` that I'm sure many developers left in w/o realizing what it was doing. I'd like to reduce 1.0 pain as much as possible
Restore the `Helper::get_comment_form` method (for now). But introduce a better method through `{{ post.comment_form }}` for folks to use.
A …
=> Comment form redux1

lib/Timber.php
**Ticket**: #991 and #979 
If you include Timber at root level it will throw a fatal error as wordpress is not available at that point and we make use of wordpress functions.
Defer setup until `WP` is available, we defer by calling the `init` function on each `compile` method, if the new constant `TIMBER_LOADED` is not defined.
We will see, early days on this one.
No change
I tried to make this as small of a change as possible to achieve the desired result and we should keep that in mind if we need to develop it further.
No tests included
=> Trying to fix init at root wp level

lib/Comment.php, lib/Core.php, lib/CoreInterface.php, lib/MenuItem.php, lib/Post.php, lib/PostType.php, tests/test-timber-comment.php, tests/test-timber-core.php, tests/test-timber-custom-fields.php, tests/test-timber-menu.php, tests/test-timber-post-type.php, tests/test-timber-post.php
**Ticket**: #992 
Need an API to access post type information that matches other methods on Post
`{{ post.type }}` can store and return this data
If a user has a custom field named "type" they're gonna have a bad time
`{{ post.type }}` and the old method `{{ post.get_post_type }}` still work
Should `{{ post.post_type }}` return this data too? At first I thought so, but then I changed my mind. Thoughts?
Tests included!
=> 992 post type labels

lib/Admin.php
The in_plugin_update_message was treating the [$plugin_data](https://developer.wordpress.org/reference/hooks/in_plugin_update_message-file/) parameter like an object, when it's actually an array.  As a result I was seeing a ` Trying to get property of non-object` error.
Changed the arrow syntax to square bracket.
Nah.  But it would be nice if there were some way to propagate this tweak to earlier versions.
=> Fixed in_plugin_update_message bug

lib/Twig.php
As the headline said, i removed some deprecated function calls.
=> Passing a name as a first argument to the Twig_Environment::addFunction method is deprecated since version 1.21

lib/Post.php, lib/PostPreview.php, tests/test-timber-post-preview-object.php
**Ticket**: #65
`{{ post.get_preview }}` is a hodge-podge of arguments. Too many arguments. And in an order that makes no particular sense.
Create an object to manage post previews!
`{{ post.get_preview}}` is unaffected. The `PostPreview` object should make it easier to add customizations down the line
It's easy and fun: `{{ post.preview.length(20) }}` or `{{ post.preview.length(20).force.read_more("Keep Reading") }}` or `{{ post.preview.length(25).end('...') }}`
`{{ post.get_preview }}` could be refactored to use the processing in the `PostPreview` object, but now as I think about it, it might just be best to leave it so that that the Preview object can evolve w/o backwards compatibility concerns.
Tests included!
=> 65 post preview

lib/Post.php, tests/test-timber-integrations.php
**Ticket**: #942
`post.has_field(fieldname)` doesn't exist
Add an alias to the `get_field` method that returns a `boolean` rather than `mixed`
None, new method
`post.has_field('field')` => `boolean`
There isn't any real benefit to this, it's mostly syntax sugar, but it is more inline with ACF itself.
Tests included, I hope they run...
=> Adding has field + tests

lib/Image.php, tests/test-timber-image.php
**Ticket**: #927
Passing an ACF image array would not return a full `Timber\Image` object.
Check if an array has been passed and if that array has an ID property, if it does grab the ID and continue.
`Timber\Image` instances initiated with an ACF image array will work properly.
No change
`init` method is getting ever larger, it seems to do some logic which should probably be moved out.
None included.
=> Catching acf image array

lib/ImageHelper.php
**Ticket**: #598 
If WP is in a sub-directory `TimberImage` will incorrectly strip out `home_url` (includes sub directory) instead of `site_url` (just includes protocol:host).
Change `home_url` to `site_url`
No change
This needs testing properly by people who have the issue
None included
=> Changing home_url to site_url to keep subdirectories

bin/phpunit-multisite.xml, lib/Site.php, tests/test-timber-multisite.php
**Ticket**: #568
A fix was made for the multsite `site.url` property that was reverted at a point afterwards.
Revert the revert as the issues seems to still exist according to the ticket
Should fix multisite urls
No change
None included
=> Revert a revert for multiste url fix

lib/QueryIterator.php, tests/test-timber-iterator.php
**Ticket**: #837
If you have a `Timber\QueryIterator` object, there is no way to get the total posts returned, for example of a search results page with the default `posts` object in context.
Add a method to return the private `_query.post_count` property
No impact
` {{ QueryIteratorObject.post_count }}`
There may be other properties that would be useful to expose. Also I am not sure on the reason behind returning a `QueryIterator` rather than a collection of `Timber\Post`s, you could then do `{{ posts | length }}` to get the total posts
None
=> Adding count property to queryiterator

lib/Cache/KeyGenerator.php, lib/ImageHelper.php, lib/MenuItem.php, lib/Post.php, lib/QueryIterator.php, lib/Timber.php, tests/bootstrap.php
The code is still relying on the old classnames without namespaces.
Changing oldclassnames to new namespaces names.
None.
No changes.
I'm quite sure I still missed some.
No changes. Everything is still passing.
=> Fix usage of old classnames

lib/Image.php, lib/ImageHelper.php
**Ticket**: #1043 
If you tried to resize an image with an uppercase extension it would return the URL with the uppercase extension, which would be fine if we didn't `strtolower` the extension when saving the resized image.
`strtolower` the extension that we get back from `pathinfo`
None
No change
=> Fixing uppercase extension

lib/Image/Operation/Resize.php
**Ticket**: None
I discovered a bug that I haven't seem reported anywhere, I got a fatal error when trying to resize an image.
If you look at the code before/after, you will see that we run `wp_get_image_editor` in both `run_animated_gif` and `run`, the result of that then gets passed into `get_target_sizes` which will then run `wp_get_image_editor` once again, and pass in the result of the previous `wp_get_image_editor`
Firstly I moved the errors further up the method so we catch any errors without throwing fatal errors on production sites.
Then I passed the result of `wp_get_image_editor` into `get_target_sizes` and didn't run that method again once we were in there.
Should fix this bug
No change
I couldn't find any other mention of this, so maybe it's my …
=> Fixing double image object issue

lib/TermGetter.php, lib/Timber.php, tests/test-timber-term-getter.php
**Ticket**: #386 
**Reviewer**: @jarednova @ste93cry
There was no wrapper for `get_term`
Adds wrapper
None
`Timber::get_term(params)`
This needs testing, I literally just added a wrapper, `get_terms` seems to do a lot more.
Needs a test
=> Adding get term

tests/test-timber-image-letterbox.php, tests/test-timber-image-resize.php, tests/test-timber-image-tojpg.php, tests/test-timber-image.php
Currently tests run can cause fatal errors in a case if they're running on PHP with no image processing extensions (GD, Imagick).
This pull request marks affected tests as skipped in a case if no such extensions are loaded.
Raise of chance on success tests run in more environments.
=> Avoid test to break if no image processing extensions are installed

lib/Core.php, lib/PostType.php
[import()](https://github.com/timber/timber/blob/master/lib/Core.php#L59) method in `\Timber\Core` may cause fatal error in PHP 7 in a case if it receives object containing protected / private properties as input. I've prepared [gist](https://gist.github.com/FlyingDR/72dea267a3e313a31b374932df226a0c) that demonstrates problem.
Problem arises when several factors are came together:
1. [get_object_vars()](https://secure.php.net/get_object_vars) function, used into method returns object property names for protected / private properties prefixed with `\0` character (see [comment](https://secure.php.net/manual/en/function.get-object-vars.php#47075))
2. Previous point by itself is not a problem without `(object)(array)$var` type casting used into …
=> Workaround against error caused by importing protected/private object properties in PHP 7

lib/Post.php, tests/test-timber-post-type.php
**Ticket**: #1070 and #1057 
Some errors were caused by #1003. This should resolve them:
- If a post had a custom field named "type", you would get the `PostType` object instead of the value
- If a post had a custom field named "_type" all hell broke loose
Return a custom field value if set for `post.type`
Version `1.0.5` can restore expected functionality, we can plan for how to do things best in `1.1.x`
None
We should consider if/how to disallow the names of certain custom fields
You betcha
=> ref #1070 -- ref #1057 -- resolve errors with {{ post.type }} fallout

lib/Loader.php
Currently `Timber\Loader` class collects location information from several methods and their checks and normalization is inconsistent. It results into duplicates into resulted set of paths in some cases, e.g. when using paths containing symlinks. Moreover prepared paths are re-normalized upon use ([twice](https://github.com/timber/timber/blob/master/lib/Loader.php#L215)) while it can be safely omitted if locations storage itself will be not accessible directly from outer code.
Provided patch unifies paths checks and normalization across information gathering methods and removes methods mean for internal use from being publicly accessed.
Minor performance gain and slightly better stability
=> Loader locations normalization

lib/User.php, tests/test-timber-user.php
**Ticket**: #1073 
As described in #1073, the user's hashed password exposed is in the TimberUser object.
Added an `include_pass` flag to the constructor and init functions, which is set to false by default.  Unless the flag is set to true, the user password will not be exposed in the user object.   
Would only affect users that are using that hashed password somewhere, which seems like an edge case.
The TimberUser constructor now accepts an optional second param, the `include_pass` flag.  
-
Tests are included!
=> Set user password to be hidden by default

lib/Twig.php, tests/test-timber-dates.php
**Ticket**: #1085 
Reviewer: @jarednova
Bug in the date filter where some timestamps were being dubiously evaluated with `strtotime()` instead of their actual value because some timestamps can be interpreted as differing dates by strtotime, such as strtotime('1457395200') => 101944277859.
Only use `strtotime` on numeric values that are 8 characters in length (assuming they will be in format YYYYMMDD). 
Timestamps that are 8 chars in length will suffer, but this is preferable to previous behaviour. Most dates in WordPress will probably not be timestamps
Added a test with a timestamp that `strtotime` will interpret as a valid, different date.
=> Fix issue where timestamps could be erroneously converted by strtotime

lib/ImageHelper.php, tests/test-timber-image-resize.php
WPML language identifier breaks the ImageHelper
https://github.com/timber/timber/issues/405
Use site_url() instead of home_url()
This might break some things that the current tests don't cover.
The test mocks the filter added by WPML since WPML is not a free plugin one could easily install using composer. Without the home_url() -> site_url() change the test fails.
=> 405 wpml image url fix

lib/Loader.php
This change adds extra parameters to the `timber/loader/render_data` and `timber/output` filters so more context is available when using the filters.
=> Add extra contextual parameters to render filters

lib/Helper.php, tests/test-timber-helper.php, tests/test-timber-pagination.php
**Ticket**: # https://github.com/timber/timber/issues/1109
Trailing slash is not set appropriately for paginated links
Use `user_trailingslashit`
Pagination links may be affected.
Code works with my install, generating the paginated links appropriately, but a bunch of tests are failing and I have no idea why/how to fix them.
Tests are included, but they are failing!
=> Handle trailing slashes properly

lib/Loader.php, lib/Twig.php, tests/test-timber-twig.php
**Reviewer**: @jarednova
There was no escaping for `esc_url` or `wp_kses_post` natively in Twig (or Timber)
I added escapers as described in the [Twig Docs](http://twig.sensiolabs.org/doc/filters/escape.html#custom-escapers)
I'm not sure if `wp_kses_post` should be an escaper or if it should be it's own filter a la `wpautop` what are your thoughts?
I added the code in `Timber\Twig` and it acts as an analog to the filters, seems like the logical place for this to live.
I also added an extra filter `timber/twig/escapers` which is pretty much an analog to `timber/twig/filters`
Should be minimal impact.
```twig
<a href="{{ post.get_field('custom_link')|e('esc_url') }}">My Link</a>
```
```twig
<p>{{ post.get_field('wysiwyg_field')|e('wp_kses_post') }}</p>
```
This is pretty straightforward, we …
=> add escaping for esc_url and wp_kses_post

lib/PostGetter.php, tests/test-timber.php
**Ticket**: #819
As described in the ticket, Timber::get_post using an ID may not return anything when a post with a custom type is requested, in contrast to the WP `get_post` function.
Instead of using the `get_posts`  method, which will only get post types with `exclude from search` set to true, just get posts directly using `new $PostClass()`.  The new post constructor uses Wordpress' `get_post`, which is pretty much a direct database hit to get a post based on ID and circumvents a lot of the logic applied to `get_posts`.  There's also a conditional in there to handle post previews.
- 
nope!
This use of the `maybe_get_preview` function here is a little funky -- it's intended to accept and return an array, which makes sense in the context of a `PostsCollection` …
=> Edited get_post method to get posts directly by id

lib/PostGetter.php, lib/PostsCollection.php, lib/Timber.php, tests/test-timber-post-getter.php
**Ticket**: #1149
In Timber 1.1.2 you can't use classmap array when retrieving single post.
Get post_type and figure out the class to be used before instantiating it. This is handled by static method `get_post_class` which is also used in `PostCollection`. Added possibility to set classmap by filter `Timber\PostClassMap`.
Backward compatible.
`get_post` usage is now the same than prior 1.1.2 version.
There is need to investigate if `get_post_class` method could be used for example in method `get_posts()` of `\Timber\Term\`
Tests included and passed
=> Allow usage of classmap in get_post

lib/Post.php, tests/test-timber-filters.php
Unable to edit the "Read more" link in full, e.g. to add extra elements (div, li, etc)
Using the wordpress filters it's possible to create a filter that we can then use in our functions.php to customize the link in full
```
function read_more_link( $link ){
$post = get_post();
$link = '<div><a class="read-more" href="'. get_permalink($post->ID) . '">Read more...</a></div>';
return $link;
}
add_filter( 'timber/post/get_preview/read_more_link', array($this, 'read_more_link') );
```
=> Possibility to change "Read More..." link using filters

lib/Admin.php
**Ticket**: #1160
See #1160
Replacing the paragraphs with line breaks bring the update information in line with 4.6 changes to shiny updates
The impact should be minimal. The double line break functions similarly as a paragraph. It's not as "semantic" as before but that's debatable since now the entire update message is wrapped in a single `<p>` tag automatically as of 4.6. Wrapping the different sections in a `<div>` could be ideal since they are block level, but `<div>`s are hoisted out of `<p>` tags in most browsers.
Here is what the proposed change looks like visually in 4.6
Here is what is looks like with the proposed changes on 4.5.3 (and below presumably)
=> Replace paragraph tags with line breaks in plugin update row

lib/Timber.php, lib/URLHelper.php, tests/test-timber-url-helper.php
The url helper was missing the ability to tell what HTTP scheme it was in. 
This fixes that by adding URLHelper::get_scheme() to check if HTTPS is on or off.
This removes the hardcoded HTTP scheme in Timber::get_context()
No special usage
There's the possibility of adding a check to URLHelper::get_scheme() to see what port is being used, but it's not guaranteed that port 443 will be encrypted.
Test for this method are included.
=> Added get_scheme URL helper

lib/QueryIterator.php, tests/assets/iterator-loop-test.twig, tests/test-timber-iterator.php
**Ticket**: # 
The special Twig `loop` variable [requires the `Countable` interface to be implemented](http://twig.sensiolabs.org/doc/tags/for.html#the-loop-variable) when iterating over an object for some loop properties to work as expected (read: exist).
`Timber\QueryIterator` does not implement nor inherit this interface, so when iterating over it in Twig, some properties of the `loop` variable are not there.
The solution is to simply implement the interface on the `QueryIterator` class.  It requires a single `count` method.  The existing `post_count` method remains and is used by the new `count` method.
I have no reason to believe that this would be a backwards-incompatible change.  If anything, it improves the experience of using Timber by filling the gap in expected …
=> Add Countable interface to QueryIterator

lib/Post.php, tests/assets/password-form.twig, tests/test-timber-post-password.php
**Ticket**: #217 
Usage....
New filter for `functions.php`
```php
add_filter('timber/post/content/show_password_form_for_protected', function($maybe_show) {
return true;
});
```
```php
add_filter('timber/post/content/password_form', function($form, $post){
return Timber::compile('assets/password-form.twig', array('post' => $post));
}, 10, 2);
```
=> ref #217 #285 -- added PW support for post content, but not by default

lib/Filter.php, lib/Twig.php, tests/test-timber-helper.php, tests/test-timber-twig.php
Add separate `Filter` class for commonly used filters. In this case add useful filter for trimming text
string to a certain amount of characters.
Decouple `Twig` class. Move all filter methods like `add_list_separators` , `time_ago`. (Not included in this pull request).
Create new class `Filter`. Add `trim_characters` method. Modify `Twig` class, add new `Twig_SimpleFilter`
Uses `mb_strimwidth` (PHP 4 >= 4.0.6, PHP 5, PHP 7) , wordpress functions `__()` for localization and
`wp_strip_all_tags` for striping all tags from input text.
By default string is trimmed to 60 characters. 
```
<p class="post-content__text">
{{ post.post_content|excerpt_chars }}
</p>
```
You can specify desired characters amount 
```
<p class="post-content__text">
{{ post.post_content|excerpt_chars(130) }}
</p>
``` …
=> Add excerpt chars filter

lib/Post.php
**Ticket**: # 
At the moment you can't pass an array of post types to the children function of the Post class.
Allow passing arrays.
Should not affect backwards compatibility. Wordpress already supports querying for multiple post types.
You can pass an array to children()
I have only done some brief testing which seemed to work fine.
If needed I can help by adding a test.
=> allow passing an array of post_types to Post->children()

lib/ImageHelper.php
**Ticket**: # 
Generates files not affected when Wordpress regenerates thumbnails
Delete generated files for an image/attachment when Wordpress is called to regenerate thumbnails so that images generated by Timber can be regenerated when next called
All generated images for an attachment would be deleted and would be recreated when first accessed.
Backward compatible.
Just for folks to know that if they regenerate Wordpress thumbnails that any resized images created by Timber will be deleted and will only be regenerated when first accessed.
No tests.
Without the code, generated images remain.
With the code, generated images are deleted for an image/attachment.
=> Delete generate files for image when metadata generated

lib/Post.php, tests/test-timber-post.php
**Ticket**: #1221
**Reviewer**: @jarednova / @connorjburton?
See #1221.
- Test for `Post->terms()` return class
- Test for `Post->get_terms()` return class
- Receive parameter for `Post->get_terms()` and pass it
More backwards compatibility with pre-1.0 versions.
No changes.
The `$TermClass` parameter could be better documented (this is missing right now), but that's probably better as a separate issue.
Tests are included.
=> Post->get_terms() return class

lib/ImageHelper.php
**Ticket**: # 
When Wordpress is in a different directory other than the default, (for example when using [Bedrock](https://github.com/roots/bedrock), images are not found by the ImageHelper class.
Replace uses of site_url() with get_home_url()
The change is designed to have no impact.
Will need to make sure this has no unintended side effects on multisite installs.
Tests are already in place.
=> Fix images when wordpress is not installed in default location

lib/ImageHelper.php, tests/test-timber-image-resize.php
**Ticket**: #1227 
We might have gotten a little ambitions with replacing `site_url` with `get_home_url()`. I found some errors in tests relating to WPML and external images. This splits the tests to better measure and resolves errors
=> 1227 image test fix

lib/ImageHelper.php
Unfortunately the reverting in #1229 has caused issues with resizes when uploads is not in a standard location. This attempts to fix it again, and not break WPML.
=> fix resize for urls when upload directory is not in default location

lib/Menu.php
fix #1230 
TimberMenu($slug) did not work correctly for menu slug input, because ```get_menu_id_from_terms``` was not reachable in case wordpress locations exist and ```get_menu_id_from_locations``` fails in finding the menu id.
=> fix get menu by slug

lib/Site.php
Use Wordpress internal function to restore current blog instead of manually doing it. Solves issue with Yoast SEO metabox on multisites. 
I'm not sure if my changes will break other functionality. But I've done some testing on our site and not encountered any problems at all. We use ACF, WPML and many more plugins and it seems like it hasn't affected them.
=> Fix for Yoast SEO metabox on multisite #1129

lib/Menu.php
**Ticket**: # 
TwigMenu menu.items and menu.get_items() returns menu sorted by the title and not menu_order
Use get_pages() with parameter array('sort_column' => 'menu_order')
May impact sites that relied on menu items sorted alphabetically
No usage changes
Allow sort column to be passed to API.
Current test has passed because menu title with menu_order 1 was Bar Page, should probably be renamed.
=> Menu items order

lib/Post.php, tests/test-timber-post.php
Child posts with inherit status are not loaded with post.children
Add ```post_status=inherit``` to get_children query.
None
Attachments with post.number are now correctly loaded
```post.children``` returns also the thumbnail making ```post.children``` cumbersome it in twig templates. So, what do you think about excluding it from the method it self?
Done
=> load children inheriting published status

lib/Twig.php
**Ticket**: # 
Passing the string `'core'` to the `$twig->getExtension` method was deprecated in v1.26 and will be removed in 2.0. The API now requires that the fully qualified class name be used instead.
Changing the string `'core'` to `'Twig_Extension_Core'`
Shouldn't have any effect, very minor change.
N/A
Deprecation notice is gone and the code works without error, can't get more ideal than that!
There were no tests for this string previously and I didn't add any. Based on the deprecation notice, an app will fail without this change if `2.0 >= $twig_version `. I did not test this.
=> Deprecated Twig getExtension argument

README.md
Pine is a CLI installer for timber which installs WordPress & Timber with a single command.
I've just added an-other link to related projects section so that people reading the docs see this new tool.
=> added pine to related projects

lib/MenuItem.php
**Ticket**: # 
When looping through menu items, you are not able to obtain the referenced post thumbnail image.
This adds a function to expose the post thumbnail url.
This change provides additional functionality.
When looping through a menu you can now use `{{item.thumbnail}}` to obtain the post thumbnail.
=> Adds Menu Item Thumbnail

lib/Comment.php
Avatar method in the comment class is ignoring filters set up previously (like 'pre_get_avatar_data).
Add filter to avatar method.
Very low, improving consistency with WordPress core.
Transparent for users.
=> Use 'pre_get_avatar_data' filter for avatars

composer.json, composer.lock, lib/Image.php, tests/test-timber-image.php
**Ticket**: #429
#429 and #1131 describe issues where images stored on Amazon S3 do not load from S3 when Timber is activated
Apply a widely-used patch directly to `Timber\Image`: 
```php
// Add this to functions.php
function fix_timber_s3_src( $src, $ID ) {
$size = '';
$attachment_src = wp_get_attachment_image_src($ID, $size)[0];
$fixed_src = $attachment_src ? $attachment_src : $src;
return $fixed_src;
}
add_filter( 'timber_image_src', 'fix_timber_s3_src', 10, 2 );
```
Makes is cleaner! But also could have fallout based on what's being over-written
None
This does NOT solve the resizing issues described in #429 
Tests pass locally, no new tests though
=> ref #429 -- fixed server location to build-in filter fix

lib/Image.php
With the changes introduced in https://github.com/timber/timber/pull/1320, Timber doesn’t return the full source of an image when the `src` method is called without a parameter. Instead, it returns the default size of `wp_get_attachment_image_src()`, which is `thumbnail`. @davidmaneuver already mentioned this in https://github.com/timber/timber/pull/1320#commitcomment-20979891.
As I understand it, the default size should be `full`, because otherwise filters like the following would resize the thumbnail src instead of the full size.
```twig
```
would result in a src like
```
http://example.org/wp-content/uploads/2016/03/dog-150x150-c-default-640x0-c-default.jpg
```
Change default parameter for `$size` from `''` (empty) to `'full'` in `Image::src()`.
Restores default behaviour?
No …
=> Return full size of image by default

lib/ImageHelper.php
**Ticket**: #1346 
Bad response when uploading media files in Windows
Use `preg_quote()` to escape path to the file.
No impact.
No usage changes.
Make sure that `preg_quote()` is being used elsewhere in the codebase as well.
The code is hard to unit test in different platforms.
=> Fixed HTTP error when uploading media files in Windows (#1346)

lib/ImageHelper.php
It took me a while to get this one sorted out. This is (probably) happening since the big Timber-Update (from 0.22).
If a wp-setup with an external WP_CONTENT_DIR (ie. site.dev/content instead of site.dev/wp-content) in combination with an external WP_SITEURL (ie. site.dev/wp instead of site.dev/) is used, the analyze_url function creates a faulty path (/site.dev/wp/wp/content/uploads/..) instead of /site.dev/content/uploads..). This breaks the resize function, which therefore will only return the original file src.
In analyze_url we first check, if the site_url is contained in baseurl. If not, the site_url can't be used to build the path and therefore we create the path based on the home_url and the images relative path. 
Could break the whole image-resize processing if this approach …
=> [Fix] Wrong image path breaking timber resize when using external wp-content-dir (WP_CONTENT_DIR)

lib/Timber.php
On PHPStorm the `Timber\Timber::render('views/view.twig')` issues a warning `Expected array got string`
Updated doc block to accept string as well
=> fix doc block to avoid IDE warnings

docs/wiki/_cookbook-text.md
With the new version 2 of Poedit, it’s now easier to internationalize a Timber theme. I updated the documentation accordingly:
- Differentiated between using Poedit 1 and Poedit 2
- Added the HTML attribute caveat to Poedit 1 section (http://stackoverflow.com/a/38834931/1059980)
- Listed internationalization functions that are wrapped by default in [Twig.php](https://github.com/timber/timber/blob/master/lib/Twig.php)
- Applied coding standards to code examples
=> Update Internationalization section in docs

lib/Image/Operation/ToJpg.php, tests/test-timber-image-tojpg.php
// First, check if the filetype is a valid one. Processing an invalid filetype
// results in an exception, which is not really useful.
// See issue: "Timber throw exception when trying to convert TIFF to JPEG #1192"
**Ticket**: #  #1192 
Timber throw exception when trying to convert TIFF to JPEG #1192
First, check if the filetype is a valid one
=> Process ToJPG only if the filetype is supported

lib/Site.php
Instead of wrapping `language_attributes`, which echoes what `get_language_attributes` returns, we can directly use `get_language_attributes`.
=> 1387/Do not use function_wrapper where we don’t have to

lib/Helper.php, lib/Timber.php, tests/test-timber-wp-functions.php
**Ticket**: https://github.com/timber/timber/issues/1387
Developers should get a warning when they still use `Helper::function_wrapper`.
This pull request puts a `Helper::warn` call into the `function_wrapper` method:
> function_wrapper is deprecated and will be removed in 1.4. Use {{ function( \'function_to_call\' ) }} instead or use FunctionWrapper directly. For more information refer to http://timber.github.io/timber/#functions
Many developers still use `function_wrapper` to expose functions to Twig. This solutions is some kind of compromise. It replaces instances in Timber where `Helper::function_wrapper` is still used by using `FunctionWrapper` directly.
The only remaining use case I saw for `Helper::function_wrapper` in Timber is `Timber::get_widgets()` …
=> 1387/Deprecate function_wrapper helper and introduce warning

.travis.yml, lib/ImageHelper.php, tests/Timber_UnitTestCase.php, tests/assets/thumb-test-relative.twig, tests/test-timber-image-helper.php, tests/travis.php.ini
Unfortunately pr #1355 broke the image resizing functionality for us. This is already mentioned by some other people here.
Our setup uses bedrock with its custom wordpress directory structure. WordPress itself is located in a subdirectory `/wp`, the content folder is in `/content`. 
The problem is, that in the previous fix, not only relative, but also absolute urls were prefixed with the `home_url`. This resulted in a url something like `http://example.orghttp://example.org/some-image.ext`.
Revert the previous fix and use `network_home_url` instead of site url. This url needs to be untrailinsgslashed for some reason. Maybe this can help #1056 as well.
Unfortunately all different scenarios are quite hard to test and would make the test suite even more complex. This solution seems to be …
=> Custom WordPress directory image resize

lib/PostGetter.php, lib/Timber.php
**Ticket**: #1425 
See ticket
- Fix param and return types
- Add description for function, parameters and return for Timber::get_post()
- Add missing return value to PostGetter::get_post()
=> Improve inline documentation for get_post()

composer.json
Based on #1412 and some other anecdotal reports. Twig 2.0 should be downgraded to experimental support — there's just too much going on to verify, even with automated tests.
In this PR I'm removing Twig 2.0 as a dependency; does anyone know if there's a way to indicate "experimental" or "try at your own risk" compatibility?
=> Disable Twig 2.0

lib/URLHelper.php
**Ticket**: # 
When using WPML with a custom wp content directory (bedrock), images URLs are being returned like `https://example.org/us/app/uploads/sites/2/2017/06/599a117bad71440a5b4f98e3807afc70.jpg`
Note the `/us` in the URL. The correct location is not to have the `/us` in the URL, like this:
`https://example.org/app/uploads/sites/2/2017/06/599a117bad71440a5b4f98e3807afc70.jpg`
I attempt to filter our the language code from the URL if it set in the function `file_system_to_url`
Should all tests pass, there should be no impact.
Usage should be transparent and backwards compatible.
I noticed there is a test already for `testWPMLurlRemote`, and `testWPMLurlLocal` - perhaps these don't work? Or don't work for installs where wordpress is installed differently.
=> fix urls of images when using WPML with language in directory setting

lib/Loader.php, lib/Timber.php
- Add descriptions for parameters and return values.
- Apply [WordPress Inline Documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/).
- Add examples.
- Improve type hinting for IDEs.
I don’t know what the benefit of the `fetch` function is, if the only difference to the `compile` function is that it applies an additional filter `timber_compile_results`. Is this for backwards compatibility?
=> Improve documentation for render and compile functions

lib/Post.php, tests/test-timber-integrations.php
When a developer tries to use get_field on a relationship or repeater field, Timber returns an array with instances of TimberPost. However, that didn't happen for Post Object fields, and a WP_Post was returned instead.
In the convert function used by get_field, a if condition was added to check if the argument given is an instance of WP_Post (and not an array of course), and returns an instance of TimberPost.
None that I'm aware of.
Ability to use get_field() on a Post Object field and get a TimberPost
None
````
{% set post_obj = post.get_field('single_post') %}
{{ post_obj.thumbnail.src.('medium) }}
````
The last line would fail because `post_obj` wouldn't be a TimberPost, but a WP_Post
=> Enable Post::convert() to convert also single WP_Posts

lib/Comment.php
**Ticket**: # 
Known arguments for avatar (size, default) are not passed to the filter, so they are missed by the functions hooked into the filter (for example, returning an image of the wrong size).
Add known args  to filter method.
Small, and bringing behaviour up to expectation.
=> Add known arguments to avatar filter

tests/test-timber-loader.php
Our hoster notified us about possible security issues with the `open_basedir` override (`Atomicorp.PHP.Bypass.OpenBaseDir`). It's commented out so removing the code doesn't change anything. There's also no reason that the code should be there in the first place.
Removing dead / commented out code.
No notifications of virus scanning softwares about vulnerabilities in the test-timber-loader file.
=> Remove dead code from test-timber-loader

docs/getting-started/setup.md, docs/getting-started/themeing.md, docs/getting-started/video-tutorials.md, docs/guides/acf-cookbook.md, docs/guides/cookbook-images.md, docs/guides/cookbook-text.md, docs/guides/cookbook-twig.md, docs/guides/custom-page-templates.md, docs/guides/debugging.md, docs/guides/escapers.md, docs/guides/extending-timber.md, docs/guides/filters.md, docs/guides/functions.md, docs/guides/pagination.md, docs/guides/performance.md, docs/guides/routing.md, docs/guides/sidebars.md, docs/guides/template-locations.md, docs/guides/testing.md, docs/guides/wp-integration.md, docs/upgrade-guides/1.0.md
With the upcoming new documentation that switches from a onepager to single pages, not all headings are on the same page. This means that headings need to have a different hierarchy.
This pull request optimizes the heading structure:
- Fix hierarchy levels.
- Remove headings where not needed, e.g. to announce language before code examples or where they were used for styling purposes.
- Remove links from headings because they break links in the table of contents. Instead, add the links to the text.
- Remove colons from then end of headings.
- Add some more headings to provide a better structure for the document.
- Add empty lines before and after headings.
- Remove manual table of contents from beginning of documents.
- Remove unnecessary whitespace where spotted.
---
This pull request …
=> Fix headings

lib/URLHelper.php
**Ticket**: # 
PHP Warning:  strstr(): Empty needle in /web/app/plugins/timber-library/lib/URLHelper.php on line 130
In wp-cli context  self::get_host() can be empty therefore strstr($url, self::get_host() generate a warning
checking that the needle is not empty
=> fix gethost can be empty and generate a warning

lib/Loader.php
The Twig Loader is accessible via get_loader(), and exposing the $loader property makes the class vulnerable to alterations after initialization. Even via get_loader() it is possible to modify the loader, but not replacing the loader object, which could be done via the WordPress hooks already.
Renaming the new init() method to create_twig_loader(), and modifying it to return a newly created Twig Loader object, which the controller stores in the private $loader property once and for all, internal integrity is insured and overloading made possible…
=> Rename init() to create_twig_loader(), and move cache filters to controller.

composer.json
There are still entries related to the old docs in `composer.json`:
- Link to wiki in `support`. The wiki will be deprecated, so this can be removed. Instead, we should use a link to the new docs.
- Package suggestions in `suggest` that are not needed anymore.
- Entry in `repository` that is not needed anymore.
=> Documentation: Update composer.json

.github/PULL_REQUEST_TEMPLATE.md, bin/timber.php, readme.txt
With the changes in #1476, #1489, #1491 — I want to ensure theme developers are informed about risks to their setups with the upgrade
The readme includes a new `**Change for Theme Developers**` lead-in for a change that might affect someone's WP setup
Hopefully it makes upgrade processes smoother!
The new PR Template describes what we're looking for with each PR. It now includes a "Documentation Requirements" section so that PR-ers submit with readme.txt changes included
Yes!
Will the bolding show-up in the WP upgrade modal (in the plugins section)? Not sure...
@gchtr: if this looks good, please merge and we'll make the official 1.4.0 release!
=> 1.4.0 Release Notes

docs/guides/cookbook-text.md
- Shorten section about functions and link to Functions Guide.
- Remove deprecated sections debugging (now handled in Debugging Guide).
This commit also deprecates the wiki page called «Text Cookbook».
Eventually, the Text Cookbook can be deprecated completely as well, because all content can be handled better by other guides.
=> Update documentation for Text Cookbook

docs/guides/debugging.md
- Improve structure
- Use Markdown markup for images
- Add description for `get_class` filter.
This commit also deprecates the wiki page about Debugging.
=> Update documentation for Debugging

CONTRIBUTING.md, README.md
This pull request aims to have a single source for contributing guidelines by only using CONTRIBUTING.md and deprecate contributing guidelines in the wiki.
**README.md**
- Update link to CONTRIBUTING.md
**CONTRIBUTING.MD:**
- Small improvements.
- Remove broken link to blades theme.
- Add entries for answering questions on Stack Overflow and on the Gitter channel.
=> Deprecate contributing guidelines in wiki, only use CONTRIBUTING.md

docs/guides/cookbook-images.md
- Improve wording
This commit also deprecates the wiki page for the Image Cookbook.
=> Update documentation for Image Cookbook

docs/guides/performance.md
- Improve structure
- Delete table of contents inside document
This commit also deprecates the wiki page about performance.
=> Update documentation for Performance

README.md, docs/guides/functions.md, docs/guides/internationalization.md, docs/guides/wp-integration.md, lib/Admin.php, lib/Helper.php, lib/Image.php, lib/ImageHelper.php, lib/Timber.php, readme.txt
- A lot of links still point to the wiki pages.
- Some content in readme.txt (for the [Plugin page](https://de.wordpress.org/plugins/timber-library/)) seems to outdated.
- Update links still pointing to the wiki.
- Copy over descriptions from README.md.
- Display links to project page, GitHub repo and documentation more prominently.
- Delete sections that are covered mainly in the README.md of the GitHub repository. This includes the sections "Related Projects", "What does it look like", "Who is it good for?" and "Want to read more?".
- Delete support entry in FAQ in favor of main == Support == section.
- Apply coding standards.
I deleted a bunch of sections to make the readme.txt for the plugins page lighter. Maybe I’m going too far here, but I thought it might better to reduce the …
=> Update readme.txt and links to documentation

docs/guides/woocommerce.md, docs/guides/wp-integration.md
Update documentation for WooCommerce
- Apply coding standards, improve whitespace (spaces instead of tabs for markdown)
This commit also deprecates the wiki page about WooCommerce.
---
Update documentation for WordPress Integration
- Apply coding standards, improve whitespace (spaces instead of tabs for markdown)
This commit also deprecates the wiki page about WordPress Integration.
=> Update documentation for WordPress Integration and WooCommerce guides

docs/getting-started/setup.md, docs/getting-started/themeing.md, docs/getting-started/twig-tools.md, docs/getting-started/video-tutorials.md
- Apply coding standards, improve whitespace (indentation, spaces instead of tabs for markdown)
- Fix links
This commit also deprecates the wiki pages in the *Getting Started* section.
=> Update documentation for Getting Started guides

docs/getting-started/setup.md
After the Themeing guide was renamed to Theming in #1540, there’s a broken link in the Setup guide.
Fix link.
I already pushed that change to the docs. So there’s nothing more to do.
=> Fix link after site was renamed in #1540

lib/ImageHelper.php
**Ticket**: #1461
Repeated calls to `get_home_url()` noticeably slows down performance with the polylang plugin. 
Cache the value of `get_home_url()` and also avoid closures as they are difficult to unhook downstream.
On a site I was building earlier with quite a few images page load went from 4.3s to 2.6s. See #1461 for XHProf comparisons.
No.
Check one:
None except if the `relative` key is actually needed at all for `wp_upload_dir()` calls.
None added.
=> Fix polylang performance issue by caching calls to get_home_url()

lib/PostCollection.php, lib/PostsIterator.php
This pull request prepares `Timber\PostCollection` to be more versatile and possibly make it easier to integrate third party plugins into Timber that still rely heavily on the loop.
The `Timber\PostsIterator` class acts as the base for a default WordPress environment, because it sets the `$post` global when looping over an array of posts.
Sometimes other plugins rely on other globals, that are not set when using `Timber\PostsIterator`. WooCommerce for example relies on `$product` global. By making it possible to use a different Iterator class in certain circumstances, it would be easier to integrate third party plugins. Here’s how an Iterator for WooCommerce could look like:
```php
/**
* Class ProductsIterator
*
* @package Timber\Integrations\WooCommerce
*/
class ProductsIterator extends …
```
=> Prepare Timber\PostCollections to work better with integrations

lib/Theme.php
**Ticket**: #1503
Theme version is missing as public property in `TimberTheme`.
Add theme version as public property `version` to `TimberTheme`.
None.
Theme version can be accessed in Twig with `{{ theme.version}}`.
=> Add public theme version to TimberTheme

lib/Image/Operation/Letterbox.php, lib/ImageHelper.php, tests/test-timber-image-letterbox.php, tests/test-timber-image.php
You can't use letterbox with a transparent background. 
Handle transparent background when using letterbox on a png file. 
None that I am aware of. 
There's now no default color when using letterbox. 
I wrote a test to check if the image has transparency. The test passes. No regressions seen on other transformations.
=> Letterbox transparent background

docs/guides/escapers.md
**Ticket**: #1557 
This adds documentation to `escapers.md` to clarify Timber's default behavior
=> ref #1557 -- document escaping strategy

docs/getting-started/_index.md, docs/guides/_index.md, docs/upgrade-guides/_index.md
**Ticket**: https://github.com/timber/docs/issues/6
Page titles for index pages couldn’t be set in docs.
This pull request adds `_index.md` files for the different sections (Getting Started, Guides, Upgrade Guides) of the documentation, so that titles used in the `<title>` tags and for the `<h1>` tags can be set individually.
None
None
The current build of the docs is based on this pull request and includes the new index files. So when this request is merged in, there’s no need to rebuild the docs.
None
=> Add index files for better page title in docs

README.md, docs/guides/debugging.md
**Ticket**: #1443
Here comes a very nice plug-and-play extension from @nlemoine that can add a benefit to a lot of developers 🍻!
- Added a section for the [Debugging Guide](https://timber.github.io/docs/guides/debugging/) about different options for formatted debug output.
- Added link to related projects section in README.
=> Add Timber Debug Extension to documentation and related projects

lib/Twig.php, readme.txt, tests/test-timber-term.php
**Ticket**: #1159 
If you create a term in php... 
```php
$term = new \Timber\Term(34, 'arts');
```
the same args will fail in twig
```twig
{% set term = Term(34, 'arts') %}
```
Create a handler in `Timber/Twig` to see if the user is intending to use a taxonomy as opposed to a Term class
No backwards compatibility issues (or, will revise to ensure they're aren't) unless a user used the _same_ name for a Term class AND a taxonomy (including same capitalization)
Added in readme
Definitely adds some bloat/complexity. 
Written, but will ensure 100% coverage before merging
=> ref #1159 -- handles `Term` in Twig to match PHP constructor

docs/guides/pagination.md
**Ticket**: #N/A 
First example calls PostQuery() without Timber namespace, causing an "Uncaught Error: Class 'PostQuery' not found" error.
Include Timber namespace in example PostQuery() call.
No impact to codebase. Improves reliability of documentation.
None.
None.
None.
=> PostQuery() example call missing Timber namespace

lib/Site.php
`site_url` ≠ `home_url`
Timber doesn't distinguish `site_url` (the path to WordPress) from `home_url` (the path to home). 
In a regular usage, they are often the same but if you're using a specific folder structure such as Bedrock, and more globally when using WordPress in a subdirectory, they will be different. 
Provide both values in the `Timber\Site` class.
None, `url` still refers to `home_url`.
You can now use `{{ site.home_url }}` or `{{ site.site_url }}`. 
For example (the reason of this PR), the [comment form action URL](https://github.com/timber/starter-theme/blob/master/templates/comment-form.twig#L4) is presently wrong. The right URL is actually `{{ site.site_url ~ '/wp-comments-post.php' }}`
None.
=> Timber\Site: provide (real) site_url

CONTRIBUTING.md, phpcs.xml
**Ticket**: #1561
Coding Standards need to be documented and there needs to be an easier way to check and fix violations, maybe even automatically. WordPress just recently [applied the WordPress Coding Standards to the whole codebase](https://make.wordpress.org/core/2017/11/30/wordpress-php-now-mostly-conforms-to-wordpress-coding-standards/).
Define and document the coding standards and provide a way for developers to check for errors in coding style automatically.
- Introduce a new `phpcs.xml` file, which is a custom ruleset for [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) that inherits from [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards). The WPCS (WordPress-Coding-Standards) project provides sniff rules for PHP_CodeSniffer to enforce …
=> Define coding standards and introduce custom ruleset to apply and check them

lib/Integrations/ACF.php, lib/Post.php
**Ticket**: #1597 
No support for `get_field_object`
It just adds the missing support
It adds two methods. 
In Post object there is a `get_field_object` (with new filter) and in ACF Integration there is 'post_get_meta_object' and a new `add_filter`
You use it just like `get_field`:
```php
post.get_field_object('field_name')
```
Now it's working only with posts, but if you think it will be useful I can write term and user version too.
I think the tests should be simmilar to `get_field`
=> #1597 get_field_object support

lib/Helper.php, lib/Twig.php
What if you want to get an specific item of an array?
**wp_list_filter** is a native WordPress function that filters a list of objects, based on a set of key => value arguments. Perfect for this situation!
In WordPress [documentation](https://codex.wordpress.org/Function_Reference/wp_list_filter) there aren't examples of it in action, but [here](url) there is a good one
```twig
{# Getting two specific posts from a wp-query, post-1 and post-2 #}
Post-1: {{ posts | filter('post-1') }}
<br />
Post-2: {{ posts | filter('post-2') }}
```
=> An easier way (filter) to get a specific item of an array

lib/Post.php
**Ticket**: #375 (builds on PR #876)
If a custom post type is registered and sets `capability_type`, the current code does not correctly resolve permissions for the purposes of previewing changes to an already published post.
For example, I have a custom post type of `article`, but with `capability_type`=>`page`:
`'edit_' . $query->queried_object->post_type . 's',` resolves to `edit_articles`, rather than the correct `edit_page`.
Use `get_post_type_object`->`cap` to get the actual name of the capability
This should not break anything for anyone
None
`get_post_type_object($query->queried_object->post_type)` feels a bit clunky
Needs test?
=> Fix get_post_preview_id for custom post types that use capability_type

lib/Twig.php, tests/test-timber-twig-objects.php
Maybe there are developers out there who’d like to use `PostQuery` directly in Twig?
I thought about this when working on the WooCommerce integration, because there I have only reduced access to PHP templates.
Make `PostQuery` available as a function in Twig.
PHP files could be very lean:
```php
use Timber\Timber;
Timber::render( 'index.twig', Timber::get_context() );
```
But the whole idea probably only works well for simple use cases.
I already added the following to the Upgrade Guide for 2.0.
> You can also use PostQuery in Twig. You can pass in your arguments either as a query string, or define the parameters in an argument hash (in Twig, [key-value arrays are called hashes](https://mijingo.com/blog/key-value-arrays-in-twig), and you use curly braces `{}` instead of brackets `[]` for …
=> 2.x Make PostQuery available in Twig

lib/URLHelper.php, tests/test-timber-url-helper.php
**Ticket**: #1625  
Resized images on WPML-translated pages have urls that contain the language query string which prevents them from displaying and throws an error.
WMPL overwrites `home_url()` therefore using `site_url()` is safer
=> fixes #1625 - WMPL Image resize url issue

lib/Comment.php
`{{ comment.reply_link() }}` function always returns link, even if `max_depth` of comments is reached. This is due to `depth` parameter always set to `1`, which is wrong behavior. For child comments (replies), this parameter should be set to its new depth level, not `1`.
In result, current usage of `{{ comment.reply_link() }}` ignores `max_depth` level set in Wordpress settings, as this level is never reached.
Pass new depth value (current level + 1) instead of always `1` to Wordpress built-in `get_comment_reply_link()` function.
No impact.
No changes.
=> Fix depth parameter of comment in reply_link()

docs/getting-started/setup.md, docs/guides/cookbook-images.md, docs/guides/cookbook-text.md, docs/guides/functions.md, docs/guides/internationalization.md, docs/guides/performance.md, docs/guides/wp-integration.md
The upcoming documentation will be versioned for v1 and v2 of Timber. The latest documentation can always be found under <https://timber.github.io/docs/>. The documentation for v1 will live under `https://timber.github.io/docs/v1/`. The links used to link between documentation are absolute now, so links under `/v1` would always point to the latest versions of the docs, instead of v1.
This pull request makes the links relative, so that links between documentation works as intended.
=> Documentation: Use relative links for linking between doc pages

lib/Twig_Function.php, tests/test-timber-post.php
**Ticket**: #1632
From 2.4.0, Twig does not allow `Twig_Function` class to be extended. Triggers PHP notices if using Twig ^2.4.0
Alias class and map it to new Twig class `\Twig\TwigFunction`.
Locally tested with Twig ^1.0|2.3.0|^2.4.0, looks fine.
None.
Require Twig ^2.4.0. PHP 7+ is now available on any decent hosting provider.
Sorry, no. I don't know how to deal with multiple versions of a package with `phpunit`.
=> Alias Twig_Function from Twig 2.4.0

lib/Image/Operation/Resize.php, readme.txt, tests/test-timber-image.php
Currently the code in `Resize.php` checks for Imagick for resizing animated GIFs and gives a warning, but then proceeds to process with Imagick — even though it's already determined it's not there.
Return false when`Imagick` isn't there so we know no animated gif was created
Should resolve errors on existing installations. Tested on a real-life site with this issue.
Nope
Added a testing modification so that we can simulate when Imagick isn't available; this involves creating a constant that the method tests for
=> when Imagick isn't available we should return false

lib/PostGetter.php
Do not instantiate a new instance of $post_class_use
**Ticket**: #1660 
This solves the double-instantiation of the post class wrapper from Timber::get_post
Instead of checking is_a on an instantiated object, I am checking is_subclass_of
Should be backwards compatible, slight performance improvement if the Post Class wrapper's constructor is heavy.
None
None
Existing test cases should cover
=> Fix double instantiation of post class in Timber::get_post

lib/Helper.php, lib/Post.php
Documentation generated from doc-blocks includes profanity on public facing page. Lets clean it up 🛀 
Updating doc-blocks to improve online documentation.
Docs probably need to be re-generated and deployed. No impact other than a re-wording of two doc-blocks.
None
Personal values and opinions aside. It just looks better for open source projects to use friendly language on public facing documents.
N/A
Thanks guys! Loving using twig inside WP. Honestly without the comments helper templates you've created I would never ship on time. I even agree with the language I'm changing here, the `$args` array is the messiest thing I've ever worked with.
=> Update public langage in Helper.php and Docs.php

lib/Image/Operation/Resize.php, tests/test-timber-image-resize.php
**Ticket**: #1657 #857 
This takes @gchtr's recommendations in #857 and implements a starting point for quality manipulation using WP's tools (the `wp_editor_set_quality` filter). There are also tests to verify the behavior.
I'm partial to the concerns about the number of args we're currently asking `resize` to handle. We're now on to arg number 5. I'm torn about the best way to proceed, but I do want to at least move ahead with coverage and handling WP preferences
=> ref #1657 -- added test and using WP's quality filters

lib/PostCollection.php, lib/Timber.php, tests/test-timber-post-collection.php
**Ticket**: https://github.com/timber/timber/issues/1580#issuecomment-360980331
Since namespaced classes were introduced in 1.x, we’re trying to promote the use of the namespaced classes. Until now, there was backwards compatibility through class aliases. Version 2.x would be a good moment to ditch this.
However, one alias would make sense for ease-of-use: `Timber` as an alias for `Timber\Timber`. This is useful because we won’t have to write `Timber\Timber::render()`, but can still use `Timber::render()`.
- Remove method `Timber::backwards_compatibility()`. Move alias for `Timber\Timber` to `Timber::init()`.
- Remove class aliases for `Timber\PostCollection`.
There will be fatal errors for developers who use non-namespaced class names in PHP. A section in the upgrade guide that will be …
=> 2.x Remove backwards compatibility for non-namespaced class names

docs/guides/acf-cookbook.md, docs/guides/cookbook-images.md, lib/Twig.php, tests/test-timber-image.php, tests/test-timber-term.php, tests/test-timber-twig-objects.php
**Ticket**: https://github.com/timber/timber/issues/1580#issuecomment-360980331
In Twig, the following functions still exist: `TimberPost`, `TimberImage`, `TimberTerm`, `TimberUser`. For PHP, we replaced all those instances of non-namespaced functions. To make it more consistent, let’s deprecate these in Twig as well. The shorter versions that work perfectly fine (even without Timber\ as a prefix) already exist: `Post`, `Image`, `Term`, `User`. We can leave them as they are.
- Deprecated `TimberPost`, `TimberImage`, `TimberTerm`, `TimberUser` in Twig. They don’t return anything.
- Updated tests.
- Updated guides where some of these function names were still used.
Yes.
=> 2.x Deprecate non-namespaced functions in Twig

phpcs.xml
**Ticket**: #1603 
Taking up the discussion about coding style and personal preferences in https://github.com/timber/timber/pull/1603. I propose to remove these rules, my reasoning can be found here: https://github.com/timber/timber/pull/1603#issuecomment-354163527. Sorry for being a little pedantic about this.
Remove sniffs that deviate from the WordPress Coding Standards without a strong reason that would justify that they stay.
=> Remove sniff that deviates from WordPress Coding Standards

docs/guides/acf-cookbook.md, lib/Comment.php, lib/Image.php, lib/Integrations/ACF.php, lib/Post.php, lib/Term.php, lib/User.php, tests/test-timber-filters.php, tests/test-timber-integrations.php, tests/test-timber-post.php
**Ticket**: #1580, picking up on #1621
Streamline filter and function names.
Consider the following functions, which each have two newly added filters, adapted from their old (underscored) filter names:
**Post::get_post_custom()**
- `timber/post/pre_get_meta`
- `timber/post/get_meta`
**Term::get_term_meta**
- `timber/term/meta`
**User::get_custom()**
- `timber/user/pre_get_meta`
- `timber/user/get_meta`
**Comment::get_meta_fields()**
- `timber/comment/pre_get_meta_fields`
- `timber/comment/get_meta_fields`
**Post::get_field()**
- `timber/post/pre_get_meta_field`
- `timber/post/get_meta_field`
**Term::meta()**
- `timber/term/meta/field`
**User::meta()**
- `timber/user/pre_get_meta_field`
- `timber/user/get_meta_field`
**Comment::get_meta_field()**
- `timber/comment/pre_get_meta_field`
- …
=> 2.x Streamline method and filter names for getting meta data

phpcs.xml
Line lengths are inconsistent
Per @gchtr's suggestion, introduce a line length rule into the `phpcs.xml` file to help standardize line lengths
Might introduce some additional warnings in Scrutinizer
=> Enforce Line Length Rule

lib/Site.php, tests/test-timber-site.php
**Ticket**: #1580 
Up until now, site option values could be retrieved through `{{ site.option_name }}` or `{{ site.meta('option_name') }}`. The term `meta` doesn’t fit very well for a site option, because the value doesn’t live in a meta database table, but in `wp_options`. It would be more intuitive to have the following methods available for retrieving site options:
- `{{ site.option_name }}` (leave as is)
- `{{ site.option('option_name') }}`
- Add `option()` method that retrieves a site option through `__get()`.
- Deprecate `meta()` method in favor of `option()`.
- Update DocBlocks.
- Added test for new `option()` method.
- Updated test for `meta()` to catch deprecation.
=> 2.x Update methods to retrieve site option

lib/MenuItem.php, tests/test-timber-menu.php
**Ticket**: #1629
There is no easy way to check whether the «Open link in new tab» option is checked on a menu item in the backend.
- Introduce a new method `MenuItem::is_target_blank()` that checks whether the post meta entry `_menu_item_target` is set to "blank".
- Add fallback return value of `null` for `MenuItem::meta()`.
- Add documentation for `is_target_blank()` and `is_external()` to use them in combination.
None.
Item targets can now be checked with
```twig
<a href="{{ item.link }}" {{ item.is_target_blank ? 'target="_blank"' }}>
```
And in combination with `MenuItem::is_external()`:
```twig
<a href="{{ item.link }}" {{ item.is_target_blank or item.is_external ? 'target="_blank"' }}>
```
I added a test to check for the different states:
- No `_menu_item_target` meta value set on …
=> 2.x Introduce is_target_blank method for MenuItem

docs/guides/functions.md
Under some configuration, adding a filter like the one below:
```php
add_filter( 'timber/twig', function( \Twig_Environment $twig ) {
$twig->addFilter( new Twig_SimpleFilter( 'bar', function ( $value ) { return "foo"; } ) );
} );
```
Fails with `Call to a member function addFunction() on null`
WordPress filters return an object otherwise NULL is assumed what would replace the `$twig` object.
Fix documentation and respect WP best practices.
=> WP filters return object

lib/Menu.php
**Ticket**: #1709 
I'd like to make the instantiation of `$MenuItemClass` instances more modular and overrideable in subclasses of `Menu`.
Create a new protected method, `create_menu_item`, that is solely responsible for instantiating Timber-flavored menu items.
Refactor `order_children` to call `create_menu_item` instead of instantiating directly.
All the polymorphism.
If I've done everything right, this should be a pure refactor with no effect on behavior.
This PR is literally the pinnacle of perfection and there is no possible way to improve it.
srsly tho idk, p simple
If this breaks any unit tests, I'll buy someone a beer.
=> #1709 break $MenuItemClass instantiation into own method

lib/Post.php, tests/test-timber-post.php
**Related to Ticket**: #836  
When previewing a post that utilizes ACF fields, it appears that Timber is inconsistently handling the revision ID when populating the custom field values in the `TimberPost` class. To get ACF fields to show up properly when previewing a post, you need to use `{{ post.get_field('custom_field') }}`, as using `{{ post.custom_field }}` won't output the previewed value.
In [PR 876](https://github.com/timber/timber/pull/876) some code was added to check if the user is previewing a post, and then returning the ID of the revision that is used as the preview. However, this check was only happening if no post ID was passed to the `TimberPost` instance.
Adding another check to the `determine_id()` method to see if the user is previewing a post, regardless of whether or …
=> Previewing changes made to ACF fields

docs/guides/internationalization.md
**Ticket**: #1465 
Add a section in the internalization guide about a method to generate POT files with a gulp script. This might be helpful for developers who do not want or can’t work with Poedit.
Thanks to @luism-s for coming up with the idea and for sharing it!
=> Documentation: Add new method for generating POT files

docs/guides/escapers.md
I've removed a rogue semicolon.
=> Fix "esc_url" escaping example

docs/guides/menus.md, lib/MenuItem.php, tests/test-timber-menu.php
**Ticket**: #1629 and #1701
Picking up on the discussion that we had in #1701 whether it would make sense to have an `item.target` method.
- Added a new method `item.target` for menu items that can be used instead of `item.is_target_blank` and adds a little more flexibility for developers.
- Updated documentation for menu items. See the updates to the menu guide for what’s possible.
None.
Makes handling menu item targets more versatile.
Yes. I added tests, they ran successfully.
=> 2.x Introduce target method for MenuItem

docs/guides/menus.md, lib/Menu.php, readme.txt, tests/test-timber-menu.php
**Ticket**: #1704 
Current solutions for getting the current menu item outside the main nav loop involve looping over all menu items explicitly. This is clunky.
Add a `Menu::get_current_item()` method that returns the current item, or the closest ancestor.
Timber is more awesome now.
No breaking changes; strictly new code. I did add a note to the changelog for 2.0. Oh and MOAR DOCS. :)
It'd be nice to add a `$depth` parameter in the future, to limit the depth of the tree traversal: e.g. calling `get_current_item(1)` (or 0?) would only scan the top menu level for the current/ancestor item. (I think the `depth` constructor option is 1-based? In any case it should be consistent with that.)
Once we have that it'd be trivial to implement a `get_current_top_level_item` helper, which is a …
=> Add Menu::get_current_item() helper

docs/guides/menus.md
**Ticket**: #1704 
Just a quick follow-up to #1716 and #1724 fixing the helper method names in the docs.
Thanks!
=> #1704 fix current_* helper refs in Menu docs

lib/Term.php
Use standard field name https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters
**Ticket**: # 
Using id field in WP_Query args impact in third party plugin (hooking at 'pre_get_posts' for example)
Change `id` ot `term_id` - standard name.
=> Term_id field name in Term::get_posts

lib/Post.php
Wrong PHPDoc `@return` types for `Post.id` and `Post.thumbail()`
Fix PHPDoc `@return` types
No impact
=> Update PHPDoc @return for $id and thumbnail()

lib/Theme.php
https://github.com/timber/timber/issues/1739
In order to turn off the `parse_url()['host'] `and `self::get_host()` check, we pass ` force = true`, so that `Timber::path ()` works correctly when the site is opened with the port number ,
It should not be, because in `URLHelper::get_rel_url()` it is passed `Theme::link()`
No changes
=> Them::path() use `force = true` to work with specifying the port

docs/guides/woocommerce.md
See Issue #1381. This PR adds the text of the error message so that google searches will lead to this guide.
=> added woocommerce error detail

docs/getting-started/theming.md, docs/guides/acf-cookbook.md, docs/guides/cheatsheet.md, docs/guides/context.md, docs/guides/cookbook-images.md, docs/guides/menus.md, docs/guides/pagination.md, docs/guides/performance.md, docs/guides/sidebars.md, docs/guides/woocommerce.md, lib/Helper.php, lib/Image.php, lib/Post.php, lib/Site.php, lib/Theme.php, lib/Timber.php, lib/User.php, tests/test-timber-context.php, tests/test-timber-function-wrapper.php, tests/test-timber-gettext.php, tests/test-timber-hooks.php, tests/test-timber-menu.php, tests/test-timber-post-getter.php, tests/test-timber-post.php, tests/test-timber-request.php, tests/test-timber-sidebar.php, tests/test-timber-site.php, tests/test-timber-theme.php, tests/test-timber.php
**Ticket**: #1639
This pull request refactors Timber’s context and improves compatibility with third party plugins.
As lined out in #1639, Timber’s current behaviour can lead to compatibility problems with plugins such as BuddyPress or WooCommerce, because…
- `the_post` hook is called whenever a `Timber\Post` object is instantiated.
- Loop variables are not set for singular templates.
I figured that a way to fix both problems would be to use Timber’s context function, because that’s the function we always call in a template. Using a WordPress hook like `template_redirect` could be tricky, because developers probably will set different posts as the main post for singular templates.
That’s why I added the necessary logic to mimick WordPress’s behavior for singular templates:
- Sets …
=> 2.x Refactor context and improve compatibility with third party plugins

.travis.yml, docs/guides/wp-integration.md, lib/Twig.php, tests/assets/test-action-context.twig, tests/test-timber-twig.php
**Ticket**: #1528
Timber adds an `action` function for Twig like this:
```php
$twig->addFunction( new Twig_Function( 'action', function( $context ) {
$args = func_get_args();
array_shift( $args );
$args[] = $context;
call_user_func_array( 'do_action', $args) ;
}, array( 'needs_context' => true ) ) );
```
This function will always add the context as the last parameter in the hook, so that it can be used like this:
```php
<?php
add_action( 'my_action_with_args', 'my_function_with_args', 10, 3 );
function my_function_with_args( $foo, $bar, $context ){
echo 'I say ' . $foo . ' and ' . $bar;
echo 'For the post with title ' . $context['post']->post_title;
}
```
As I see it, this was added so that developers can add their own actions and receive the context, should they need it in the hook.
Like …
=> 2.x Remove action context

lib/Pagination.php
**Ticket**: #1758 
If a user is going to call `Timber\Pagination\get_pagination` they need to do so with an argument, even an empty one
```php
$context['pagination'] = Timber\Pagination::get_pagination( array() );
```
This is likely because the preferred method is:
```php
$context['pagination'] = new Timber\Pagination(); //works
```
This isn't a good solution (even calling `\Timber\Pagination` directly is generally not recommended). But it was in the starter theme for years this way (and tutorials, etc.) so I think we should make this less preferred method as easy-as-possible.
None.
Nope. 
Ideally consider making `Pagination` a protected class that can't be called directly. If someone wants pagination they almost certainly want the posts with them. Closing off this external access point …
=> Default to an empty array for get_pagination

docs/getting-started/twig-tools.md
Just fixed wrong capitalization with PhpStorm in the docs :)
=> docs: Fix wrong capitalization with the term "PhpStorm"

lib/ImageHelper.php
**Ticket**: #1797 
Version 1.8.0's `is_svg` method includes checking for whether or not a file is an SVG and includes a call to PHP's `mime_content_type`. Unfortunatley, this PHP method is not available in all installs and might require a PECL installation or enabling via PHP.ini:
https://stackoverflow.com/questions/14809054/mime-content-type-function-not-working
I rolled my own `mime_content_type` method using the `finfo` class.
I fear the performance on this might not be as good as the native method, but I haven't tested to validate
None
- Maybe `ImageHelper::\_mime_content_type` could call the native if it's available and only use the "homemade" component if it's not
- Maybe this is all stupid, and we should just check for the presence of `.svg` or `.SVG` in the file name and call it a …
=> Add homemade mime_content_type method to ImageHelper

CONTRIBUTING.md
**Tickets**: #1795, #1803
I felt like there’s not enough info about how Inline Documentation is translated to the Reference in the documentation.
- Added section about inline documentation that matches how inline documentation is translated to the Reference in 2.x. This includes the info that I initially put into [Documenting hooks](https://github.com/timber/timber/wiki/Documenting-hooks) in the wiki.
- Made some smaller improvements.
- Added a Table of Contents for faster navigation.
This might be interesting for @marciojc.
=> Document inline documentation standards in CONTRIBUTING.md

docs/guides/escaping.md, docs/upgrade-guides/2.0.md
Almost identical to https://github.com/timber/timber/pull/1841, so please look there for details.
Differences:
- This PR doesn't add a fallback if `autoescape` is set to `true`.
- This PR adds a note about the change in the Upgrade Guide.
=> 2.x: Update escaping docs

docs/guides/escapers.md, lib/Loader.php
As discussed [here](https://github.com/timber/timber/pull/1786#issuecomment-433835735), `autoescape = true` has been deprecated since Twig 1.21 in favor of `autoescape = 'html'`.
This PR updates the docs to reflect this change, and adds a fallback to automatically change `Timber::$autoescape = true` to `Timber::$autoescape = 'html'` if applicable.
No impact.
It is recommended to update `Timber::$autoescape = true` to `Timber::$autoescape = 'html'` to ensure compatibility with Timber 2.x.
N/A
N/A
=> Update autoescape option

README.md
There is something wrong with dependancy status badge - https://screenshots.firefox.com/uz9fx7fkydqkGfop/github.com
And it redirects to https://afiliados.medicapanamericana.com/user/projects/574e40e6e298f30048059b9f - it looks wrong.
=> Removing Dependency Status

lib/Twig.php
**Ticket**: #1828 
Currently the `maybe_convert_array` utility method is only applied in one instance when there are multiple class instances that could take advantage of it rather than explicitly repeating the same logic over and over.
Replaces repetitive code with more sustainable method that had been created in a prior PR.
Will make code more maintainable and should have no effect on the behavior since the logic is the same, just re-used rather than re-declared.
N/A, Twig Functions will still behave the same 😄 
I renamed a couple of the arguments in favor of consistency in code styling.
Existing unit tests should cover this PR since none of the actual functionality has changed.
=> Implementing maybe_convert_array to all class functions in Timber/Twig

README.md, docs/guides/debugging.md
**Ticket**: #1852
As discussed in #1852, there are not many debugging options in Twig. 
We found [an extension](https://github.com/ajgarlag/AjglBreakpointTwigExtension) that can be hooked easily into Timber. And @boris-djemrovski went ahead and made [an extension](https://github.com/djboris88/timber-commented-include) that adds HTML comments for every Twig include 🔥🙌.
This pull requests documents these two extensions and how they can be used in Timber.
None. Only nicer debugging options 😎.
None.
None.
I tested both extensions in a local project. It’s mostly just plug and play.
=> Add new debugging tools for Twig

lib/ImageHelper.php, tests/test-timber-image-helper.php
**Ticket**: #1855
If for some reason PHP is unable to access files in the relevant directory for deletion (say, permissions not allowed), that error is unhandled and creates an error in Timber
Wait to see what files are returned from `glob` and process accordingly
No backwards issues. This will likely solve a "silent error" that's not disrupting site behavior — but addling lots of log entries
No usage changes
Could investigate further as to _when_ this would be invoked and handle different situations differently (most likely, with better error messaging).
No new tests which will likely create a decrease in coverage %
=> Bail if glob error in file delete sweeper

lib/Post.php, lib/PostPreview.php
**Ticket**: #1870
How should we document the chainable `{{ post.preview }}` method?
Add documentation to all the methods of the `PostPreview` class.
No custom DocBlock tags like `@method`. Lots of examples. Hopefully better documentation for post previews.
None.
None.
=> Improve documentation for post previews

lib/Post.php, tests/test-timber-post-type.php, tests/test-timber-post.php
**Ticket**: https://github.com/timber/timber/issues/1823#issuecomment-453276787
With the new approach to fetch meta values outlined in #1823, there’s no need to check for existing custom meta values.
Remove the checks.
Probably (hopefully) none. The `$custom` property will be protected in the future (upcoming pull request), so proper error messages will be shown when updating to 2.x.
None.
None.
Removed deprecated tests.
=> 2.x Remove deprecated checks when fetching embedded media from post content

lib/Timber.php
Add deprecated and link tags
#1825
=> Deprecate Timber::get_pagination

docs/upgrade-guides/2.0.md, lib/Comment.php, lib/Post.php, lib/Term.php, lib/User.php
- The `Term` class is still missing a `timber/term/pre_get_meta_values` filter.
- Preventing the automatic fetching of all meta values only works by passing a non-empty array. If a developer wanted to disable fetching meta values, they’d have to invent an array item, like `array( 'something' )`. That’s not very intuitive.
- Some issues in DocBlocks.
I improved the DocBlocks for the filters and added some more descriptions.
I changed the method for fetching all meta data for posts from `get_post_custom()` to `get_post_meta()`. The difference is that `get_post_custom()` will fetch the post ID of the current post if not provided, while `get_post_meta()` requires a post ID to be present. In the context of a `Timber\Post` object, we always require a post ID, so it’s safe to use …
=> 2.x Streamline get_meta_values() for classes that implement MetaInterface

lib/Integrations/ACF.php, lib/Post.php
In preparation for the pull request of the pull request for #1823, I found that there are two methods in the ACF integration that practically do nothing. The `post_get_meta()` method additionally has a filter. They were added in https://github.com/timber/timber/commit/9f04ff62bfb4716beffc00d5731ee3b24dc256c2 and in https://github.com/timber/timber/commit/933f8ded923d150be316d7bf62b4cfd92f3fb3f8.
Remove the methods and the filter call.
None.
None.
None.
Ran tests. All good.
=> 2.x ACF integration cleanups

lib/Comment.php, lib/User.php, readme.txt, tests/test-timber-user.php
**Ticket**: #1866
Adds to new methods to `User`:
- `roles()` - an array with role slugs and names
- `can()` - checks if user is having a capability
Just added the code after discussion with @gchtr in #1866  
Shouldn't have any. It's something new.
Everything is described in the examples provided in inline documentation.
=> Adds roles() and can() method

lib/Post.php
**Ticket**: #1882
Some small fixes for the PostPreview documentation in version 1.x
- Grammar.
- The `` was hidden in the documentation because it’s an HTML comment 🙈. Let’s make it visible through backticks 😎.
- Automatic linking with `@link` and `@see` will only be available for version 2.0 of Timber. So let’s add a direct link to the class documentation here.
=> Add some fixes for the PostPreview documentation

docs/getting-started/twig-tools.md
Removed Lisa Templates as: 
"This plugin was closed on November 7, 2018 and is no longer available for download. Reason: Author Request."
First off, hello! Thanks for submitting a PR. We love/welcome PRs (especially if it's your first). Have any questions? Read [this section in CONTRIBUTING.md](https://github.com/timber/timber/blob/master/CONTRIBUTING.md#pull-requests) 
Lisa Templates link in docs goes to dead link on wordpress: 
"This plugin was closed on November 7, 2018 and is no longer available for download. Reason: Author Request."
removed link and section header (as would be redundant).
minimal.
mild docs change.
n/a
=> Removed Lisa Templates from twig-tools.md

lib/Helper.php, lib/Integrations/CoAuthorsPlus.php, lib/Post.php, lib/TermGetter.php, lib/Twig.php, lib/User.php, tests/test-timber-site.php, tests/test-timber-twig-objects.php
Scrutinizer flagged a number of documentation and commenting issues in the current 2.x branch. This resolves a number of them. 
Most significantly though, I discovered that in deprecating a bunch of Twig functions in `lib/Twig.php` functionality was removed. In 2.0 Twig code like:
```twig
{{ TimberPost(maybe_post).title }}
```
should now be written as:
```twig
{{ Post(maybe_post).title }}
```
However, these methods (`TimberPost`, `TimberTerm`, etc.) had not been properly deprecated until now. Thus, I think we should send the deprecation notice (which 2.x currently does) though still maintain present 1.x functionality (for now)
Restore functionality for these deprecated methods and update tests accordingly
None
We should totally kill these functions in 3.x now that they've been properly …
=> Jan 26/scrutinizer fixes

lib/Image.php, lib/Integrations/CoAuthorsPlusUser.php, lib/User.php, tests/test-timber-user.php
**Ticket**: #1730
Author avatar only used default size. As described in the issue "Now, I know I can do `post.author.avatar.src | resize('128x128')` but it won't stretch the image if base size is 96px."
I just added a possibility to pass arguments to `get_avatar_url`
It's fully backward compatible.
The only change is that user can pass an array as argument - it's documented, so everything should be clear.
There wasn't any tests for avatar before - I'm not sure is there anything to test.
=> User avatar resize

lib/User.php
**Ticket**: #1928
Some smaller things that can be improved for the new `User::avatar()` function.
Fix some issues in the DocBlock:
- Title cases.
- DocBlock tag order.
- Removed unnecessary quotes for hash notation in Twig (`{ size: 150 }`).
- Removed closing tag for `<img>`, because `<img>` is a void element and [must not have an end tag](https://www.w3.org/TR/2012/WD-html-markup-20120320/img.html#img-tags).
- Use Markdown for URL so it will actually be a link in the documentation.
- Fix return type. Because `Timber\Image::__toString()` returns the image source, directly outputting an image without `src()` (like in the example) works.
None.
None.
None.
None.
=> Fix DocBlock issues with new User::avatar() method

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
- I’ve found that I always have to change the heading levels in pull requests, if I add a little more text than usual. Let’s use `<h2>` for all the headings! They are not humongous, but add more structure and readability, in my opinion.
- Recently, I saw that some issues and pull requests were opened with text that should probably be commented out, so I added some HTML comments.
- Call me pedantic 😜.
=> Improve GitHub templates

docs/upgrade-guides/2.0.md, lib/User.php
In reviewing #1928 I noticed a bunch of excess code that was mucking-up the `Timber\User` class. Stuff that should be removed for 2.x, but left in place for 1.x users (in case there was any edge-edge-edge case stuff happening).
Remove it!
There could be some backwards compatibility issues for someone (for example) who was relying on `User::name` being a property vs. methods or some weird stuff I added long long ago (substituting "name" and "display name" for example.
No new tests, but all should still pass
=> Remove some Timber/User overhead

docs/guides/menus.md, docs/upgrade-guides/2.0.md, lib/Comment.php, lib/Menu.php, lib/MenuItem.php, tests/assets/child-menu.twig, tests/test-timber-menu.php
`Timber\MenuItem` hadn't received some of the same ❤️ as other classes. There were deprecated methods that weren't removed and methods with old names that needed to be deprecated
- Removed `MenuItem::thumbnail` (deprecated since 1.5.2)
- Deprecated `MenuItem::get_children` (follows the same pattern as `Timber\Post` and others), update docs accordingly
- Fix how `Timber\MenuItem::meta` method worked. Wasn't fully covered and had an inaccessible code block. This is necessary to ensure ACF data and others that attach metadata directly to the `nav_menu_item` can get data out
Should fix potential issues and bring this class's coverage up and in line with other classes
Noted new deprecations in `upgrade-guides/2.0.md`
There are grander issues with the menu #1820. This is potentially helpful in …
=> Cleanup of MenuItem

lib/Timber.php, tests/test-timber-context.php
**Ticket**: #1784 
Amongst the 2.0 API changes is `Timber::get_context` ==> `Timber::context();`. To help users prepare I wanted to update the starter theme to use `Timber::context();`. However, because this method doesn't exist yet, it triggers a fatal error
Make an alias for `Timber::get_context()` at `Timber::context();`. This will allow me to update the starter theme. My goal is to minimize the number of deprecations a user has to deal with when/if they upgrade their theme to 2.0
No impact on any existing code, just a bonus method out there
We could consider actively encouraging users to start using `Timber::context();` by updating the docs and adding a deprecation notice to `get_context`. For now, I've left it at the lowest common denominator of "it's here, but no pressure man".
This …
=> Alias Timber::get_context as Timber::context

docs/guides/cookbook-images.md
**Ticket**: #429, #404 and #1672
There have been requests to better document the limitations with Timber’s image functions.
Let’s try to list the limitations in the image guide.
- Adds new section about the limitations when using a CDN. In #429, several people mentioned it doesn’t work with `resize()`. But then, it wouldn’t work with `letterbox()`, `tojpg()` and `towebp()` either, right? Here’s where I’m not entirely sure.
- Adds changes proposed in #404 and #1672, that are only in the 2.x branch for now. I wanted them to be in the master branch, too.
- Moves the «Using WebP images» section into the «Converting images» section.
None.
None.
Improving Timber’s overall image experience will eventually make these updates useless. Hopefully.
None.
=> Improve Image Guide

composer.json
The current version of timber requires `upstatement/routes` r0.4. This version of `routes` requires an older version of `altorouter`, and that version of `altorouter` does a reset of `$_REQUEST` that causes some problems with other plugins (e.g. https://twitter.com/seanstickle/status/1103481154785693697).
@jarednova over at Upstatement released 0.5 of `upstatement/routes` today that updates the version of `altorouter` that is used. This PR just bumps the version of `upstatement/routes` to 0.5.
No expected impact. The changes to `upstatement/routes` since 0.4 have been minor -- just bumping the version of `altorouter` and adding a priority param (https://github.com/Upstatement/routes/commit/50401742278333746ccdf3e11dec222d31e9fe4c).
=> Bump upstatement/routes package to 0.5

composer.json
In the unit tests, we sometimes require other PHP files, e.g. in **test-timber-term.php**:
https://github.com/timber/timber/blob/7385f93457e27f1139a1b0e9d4efb8c202e75320/tests/test-timber-term.php#L172
When using `classmap`, Composer autoloads these classes whenever `class_exists()` is called, not only when we require them:
https://github.com/timber/timber/blob/7385f93457e27f1139a1b0e9d4efb8c202e75320/composer.json#L51-L54
In #1931, I wrote a test where I needed a particular class to exist only for a particular test. For the other tests, the class **shouldn’t** exist.
That test failed in Travis, because I didn’t use `composer dump-autoload` locally before running the tests and so in Travis, the class was found and triggered the error, while locally I didn’t see that error.
I looked for an …
=> Prevent autoloading of tests/php folder

CONTRIBUTING.md, composer.json, phpcs.xml
**Tickets**: #1795, #1677, https://github.com/timber/timber/pull/1930#issuecomment-466715389
All dependencies required for checking the coding standards with `phpcs` should be added as dev dependencies.
- Fixed sniff that was only added to 2.x in #1677.
- Added `composer lint` script.
- Updated composer.json with new dependencies. Sort lines alphabetically in `require-dev`.
- Updated CONTRIBUTING.md
It will be easier for developers who want to check the coding standards.
`./vendor/bin/phpcs` should be used instead of `phpcs`. To make it even easier, `composer lint` can be used.
- **Travis** – As soon as we fixed all the coding standard errors with the release of 2.x, we can add checking against coding standards to Travis. Otherwise, we would be flooded with error messages 😱. There’s some …
=> Make phpcs a dev requirement in composer.json

docs/guides/cookbook-images.md
**Ticket**: #1925
Let’s rewrite the CDN limitation section again based on the new information provided by @palmiak. It looks like when Maciej talked about «Push CDN», he was talking about the same as the following section by Jared:
> However, there may be some CDN setups that work fine with the above filters (for example: one that’s merely watching the contents of the `wp-content/uploads` directory and copying it to the CDN). For example, the filters seem to work fine with the default setups for WPEngine and Pantheon.
I changed the text to first hint about the differences between Push and Pull CDN and then describe how this relates to Timber.
=> Improve notes about CDN limitations

docs/guides/woocommerce.md
This fixes the issue with the shop page not displaying any products.
Declare WooCommerce support in your functions.php file
None, just a documentation update.
It may be worth considering adding some basic woocommerce support directly in the Timber Starter Theme
=> Update WooCommerce guide with missing step

lib/PostGetter.php, lib/QueryIterator.php, tests/test-timber-post-getter.php
... to prevent fetching too many posts when using stickies.
This fixes #1812 and makes sure that `Timber::get_posts()` produces the same output as WP `get_posts()` when using sticky posts.
**Ticket**: #1812
See my bug report: when using sticky posts; the incorrect amount of posts in returned.
I've added a method `set_query_defaults` to `QueryIterator` which is hooked at  `pre_get_posts`. The method sets `ignore_sticky_posts` to `true` if not set otherwise.
This is the same behaviour as WP `get_posts`, see `wp-includes/post.php:1759`.
Other than fixing this bug, no impact, presumably.
I've added  `testGettingPostsWithStickiesReturnsCorrectAmountOfPosts`  in `test-timber-post-getter.php`
If you comment out the new `add_action set_query_defaults` at `QueryIterator.php:26` the test will fail. …
=> Set ignore_sticky_posts=true as default wp_query argument

lib/Comment.php, lib/Post.php, tests/test-timber-comment-thread.php, tests/test-timber-post-comments.php
In WordPress 4.9.6 with the GDPR updates, WordPress no longer displays the "comment awaiting moderation" message without the user agreeing to accept cookies when posting a comment. This could leave an anonymous visitor confused about whether or not their comment was properly submitted to the site. In WordPress 5.1 an update was made to display the visitor's comment along with the moderation message immediately after a comment was submitted - https://core.trac.wordpress.org/changeset/44659 however Timber does not yet support this update.
This PR adds some handling to the `comments()` method in `Timber\Posts` to check if `wp_get_unapproved_comment_author_email()` exists and if so, check if the comment thread should display unapproved comments made by the visitor.
This should allow anonymous …
=> Add support for non-cookied comment awaiting moderation message

lib/Image.php
**Ticket**: # 
Small mis-spelling in the documentation of responsive images
Two quick string replacements
=> Correct typo in documentation of responsive images

lib/Loader.php, tests/test-timber-loader.php
**Ticket**: Resolves #1705 
A single whitespace before or after a template name (with the string) can cause the whole site to WSOD. While linters etc are great, if we can be a little more forgiving why not?
Use trim within the template loader. 
There should be no negative impacts, as filenames that begin or end in whitespace would generally be invalid, and everyone would be writing them without the whitespace, as it would cause a WSOD.
Timber's `render` and `compile` functions will now trim whitespace around template names before attempting to locate them.
Is it worth showing a warning when this happens? We could just silently allow it, but a warning could also be useful, perhaps via one of the helper functions.
If the dev is using a variable for the template name, they might like to know …
=> Template trim fix

tests/test-timber-post.php
**Ticket**: #1617 
There’s at least one failing test that appears when testing against newer versions of WordPress.
For example, the test `TestTimberPost::testPostWithVideo()` will fail, because with newer versions of WordPress, the embed will look different. Instead of 
```html
<iframe width="500" height="281" src="https://www.youtube.com/embed/Jf37RalsnEs?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
the result will include a title attribute
```html
<iframe title="Building sane, reusable WordPress templates with Twig and Timber - WPCampus 2017" width="500" height="281" src="https://www.youtube.com/embed/Jf37RalsnEs?feature=oembed" frameborder="0" allow="accelerometer; autoplay; …
```
=> 2.x Fix failing test

composer.json, lib/FunctionWrapper.php, lib/Image.php, lib/Twig.php
**Ticket**: #1972
We missed some deprecated Twig class names in #1963.
Use the new namespaced Twig class names. We should be save to do this when we require Twig versions that already support the new class names Timber’s composer.json. For this, I upgraded the required Twig version from `^2.0` to `^2.4` (Namespaces were introduced in 2.4: https://github.com/twigphp/Twig/blob/328d2aeba0b92002570b769706f500089ef6e1db/CHANGELOG#L161).
There should be no impact.
None.
None.
Ran tests locally.
=> Ref #1972 – Twig deprecated features

docs/guides/debugging.md
Great news! With the newest version of PhpStorm (2019.1), it’s possible to [set breakpoints in Twig files](https://blog.jetbrains.com/phpstorm/2019/05/twig-and-blade-templates-debugging-2/).
I added a section about this in the docs.
Happier developers.
None.
This pull request is actually what led me to #1997, because I had to look at the code to figure out how to enable Twig caching. If we change the way how we make it possible to change environment options, the docs will have to be updated as well for 2.0.
I tested it with PhpStorm. It works! It’s nice! 🎉
=> Add docs section about Twig breakpoints in PhpStorm

.travis.yml, bin/install-wp-tests.sh, tests/bootstrap.php
**Ticket**: #1983
As discussed with @aj-adl in https://github.com/timber/timber/pull/1983#issuecomment-490613098.
This pull request adds a fallback for when the `WP_TESTS_DIR` is not defined, which considers the `TMPDIR` environment variable.
As soon as this pull request is merged, #1983 should be auto-merged as well.
More failsafe testing setups.
None.
None.
Manually tested in my local non-VVV testing setup.
=> Ref #1983 – Fix bug when WP_TESTS_DIR is not defined

lib/PostGetter.php, readme.txt, tests/test-timber-post-getter.php
**Ticket**: #1987
Adds an additional filter that will give devs a chance to use get_posts in classic Timber way or in WP way.
Adds an extra if + filter that can be set to true or false.
It should solve issues like #1987 and on the hand will provide with quite easy way to solve #1812 
```
add_filter( 'timber/post_getter/wp_get_posts', '__return_true' );
add_filter( 'timber/post_getter/wp_get_posts', '__return_false' );
```
This is a temporary fix until we'll figure out what to do with `Timber::get_posts()`.
Also - I'm not sure about the filter name. Making those name is hard :(
I added add_filter in tests so the test would run in WP way.
=> Filter for not forcing the WordPress way of get_posts.

docs/guides/comments.md, lib/CommentThread.php, lib/Post.php
**Ticket**: #1971
As noted, the only example of how to do nested comments is buried in the tests
Put an example in!
Expands the example in `Timber\Post::comments` showing a nested example. The same example appears in the a new docblock for `Timber\CommentThread`.
Is this the right place? Originally I had it just in CommentThread — but since that's not really intended to be a public class, it felt wrong. This solution provides where I think people are most likely to discover it: with `{{ post.comments }}` which they interface with, and `CommentThread.php` in case someone is looking through the files
=> Added big example to top of CommentThread class — with nesting

lib/Post.php, readme.txt, tests/test-timber-post.php
**Ticket**: #2012
In #2012 @aj-adl proposed a way to skip Timber from fetching meta values through `get_post_meta()` via the `timber_post_get_meta_pre` filter. Turns out that in 2.x, I added pretty much the same behavior, just with a new filter:
https://github.com/timber/timber/blob/35279e5fa8911c52854f2d268fc028bcf76c2313/lib/Post.php#L574-L624
I wasn’t sure whether this was over-optimization, but hey, here we have a use case already 😎.
This pull request builds on #2012 to replicate the behavior that we’re going to add in 2.0 in the master branch so that this feature can be used now.
None.
See #2012.
None.
None.
=> Ref #2012 – Update skipping get_post_meta() to match behavior in 2.0

composer.json
**Ticket**: #2020, #2016 
Conflicts with versions of Twig are causing issues with WPML (and potentially other plugins)
Revert the Twig 1.x version to 1.3.4 (same as Timber 1.9.4), release as a hotfix
Minimal, only matters if someone has started to use Twig 1.35+ features in the last 24 hours that 1.9.5 has been out
None
- In the future we should ensure that dependency upgrades are reserved for minor version releases (so that should have come in 1.10)
- We should still plan to ship 1.10 with the newest Twig 1.x version
=> ref #2020 -- revert Twig version

lib/Menu.php, lib/MenuItem.php, readme.txt, tests/test-timber-menu.php
**Ticket**: #1959
See #1959.
This pull request:
- Adds a `theme_location` property to the `Timber\Menu` class that is set when the menu is registered with a theme location.
- Adds a `menu` property to the `Timber\MenuItem` so it’s possible the parent menu object from a menu item. For this, the parent menu object is passed to the constructor of `Timber\MenuItem`.
- Adds an `options` property to the `Timber\Menu` class that holds an array of default options that can be adapted through `Timber\Menu`’s constructor. It also remove the `Timber\Menu::set_options()` method and moves its content back to the constructor. I thought there’s no need to have a separate function for this.
- Passes down the new `options` property as an object for the `$args` parameter in the nav_menu_css_class filter.
- …
=> Menu optimizations

composer.json, lib/Timber.php, readme.txt
**Ticket**: #2020 #2016 
A cascade of issues starting with us releasing 1.9.4/5 as patches instead of minor versions. Upgrading Twig collided with WPML's included Twig version wrecking havoc across sites
Release 1.10.0 as non-WPML compatible (until we can find a permanent solution). Recommend to sites running WPML that they run 1.9.2 instead (and pull 1.9.3, 1.9.4 and 1.9.5 from Packagist and WP.org to reflect this)
It's probably going to be annoying for WPML users (for now). But everyone else will be happy.
- We could do a big hunt and make a (more) stable version of Timber at 1.9.6; but there'd be few upsides versus 1.9.2 and it would be a fair amount of work. This hypothetical version would have a number of quirks that could make it very unstable or create other issues for us to chase …
=> Release of 1.10.0 and resolution of WPML errors

lib/Comment.php, lib/Post.php, lib/Term.php, lib/User.php, tests/test-timber-comment.php, tests/test-timber-post.php, tests/test-timber-term.php, tests/test-timber-user.php
**Ticket**: #1617 
There were failing tests after merging in #2014. And it made me realize that for the meta functionality, I added way too few tests.
This pull request first streamlines the functionality of what the `get_meta_values()` does across Post, Term, User and Comment objects. I figured it’s actually good this is coming together step by step, because when I started out with working on meta for 2.x, I was hard to get an overview.
Now, all objects import all meta values into a `custom` property. And all `get_meta_values()` functions do pretty much the same, including the same variable pattern etc.
I also added tests for the different objects. The tests that were introduced in #2012 are really good to test the `timber/{object}/pre_get_meta_values` filter (Thanks, @aj-adl!). 
Fewer …
=> Streamline get_meta_values functions across objects

lib/MenuItem.php, tests/php/custom-menu-item-class.php, tests/test-timber-menu.php
**Ticket**: #2024 #1988 
Inadvertent breaking change introduced by new `Timber\MenuItem` constructor definition in `1.10`
Set a default `null` value for the menu
Filtering CSS classes (and other things that a user might do with menu info) won't work
None
Probably something that we don't need to bring into 2.x
No new tests
=> ref #2024 -- patch for custom MenuItems

lib/Core.php
**Ticket**: #478, #1904
See #478. 
@acobster I realized I can create a pull request from the branch in your repository. I went ahead and did this, so we won’t forget about this and so that I can resolve the failing tests and maybe improve the documentation about this. Thanks for your work on this!
Prevents infinite loops when:
- a `meta()` method wouldn’t exist.
- an inaccessible method is called.
By never calling `__get()` from `__call()`, but replicating the logic we need, we can circumvent an infinite loop.
The following check is removed from `__get()`:
```php
if ( property_exists( $this, $field ) ) {
return $this->field;
}
```
With the check removed, we are not allowed anymore access properties that are normally inaccessible (protected or private properties). Inaccessible properties …
=> [WIP] 2.x Improve magic methods in Core

lib/CommentThread.php, readme.txt
**Ticket**: #1731 
Manual ordering args were overridden by class's value
Make class's value the default, can now be overriden by user defined value
This will only cause an issue in the case where someone's failed attempts to override were unsuccessful — now they'll succeed
No new tests
=> ref #1731 -- apply suggested fix for comment order override

lib/Menu.php, readme.txt
**Ticket**: #1974 
The last WPML language switcher menu item was picking up the prior item's classes
While we want to use the `WP_Post` object (as opposed to the Timber-based object) to pull classes from, we need to clear its value to prevent the issue from occurring
This fixes #1974 (including @mgarabedian related issue). Unlike #2009, this isn't WPML-specific
None
I tested locally against a real WPML instance and verified the fix. I don't think new tests are necessary since this removes a bug vs. creating a feature
=> 1974 wpml menu fix

docs/getting-started/setup.md
Clarified which directory Composer should be used in.  Also added clarification for the scenario of using Composer with the starter theme instead of the WordPress.org install.
**Ticket**:  #2039 
Trying to use both the Composer install instructions _and_ the starter theme instructions resulted in some confusion when it came to activating the Timber plugin.
Added clarification for that specific use case.
Possibly less headaches from new users, less support tickets.
It's odd that the starter theme has a composer.json file that is using an older Timber version and uses that package type that installs it as a plugin rather than the Composer autoload mechanism.  I'm not really sure the best solution.
=> Add clarification to Getting Started docs

lib/Image.php
There seemed to be a few "dead" functions within `Timber\Image` that were non-public and unused. Originally I removed these in #2026. But as @gchtr pointed out, there are some good reasons to just deprecate before removing them entirely
~Remove~ deprecate them!
If someone has extended the Image class in some way, they may be relying on those functions for a custom operation. If this is the case, the functionality is still easily replicated through the non-deprecated methods that this will alert users to
None
We should deprecate these corresponding functions in 1.x
No new tests. Image-related tests passed locally
=> Deprecated some internal image functions

docs/guides/performance.md, docs/guides/routing.md
Added some documentation around `Timber::$cache` based on [this discussion](https://github.com/timber/timber/issues/399#issuecomment-512699932).
I was not sure whether to include a more comprehensive solution to clearing the cache on a live website. I was thinking along the lines of:
```php
<?php
Routes::map('maintenance/clear-twig-cache', function() {
if (is_user_logged_in()) {
$loader = new Timber\Loader();
$loader->clear_cache_twig();
echo 'Twig cache cleared.';
exit(0);
}
});
```
...but since I'm not fluent in PHP / WP conventions, I'm not sure whether this is an idiomatic approach to the problem.
=> Add details regarding Timber::cache to docs

docs/guides/testing.md
In setting up a new computer, I discovered that VVV no longer does some WordPress testing stuff automatically. This PR updates with info on how to setup and configure the tests manually given the new scripts
=> Updated VVV testing instructions based on current VVV setup

lib/Theme.php
Hello I would like to improve `Timber\Theme` object. 
I need to get the theme author name but the current Timber could do that.
Detail: https://github.com/timber/timber/issues/2049
Introduce new property for the [Theme](https://github.com/dtvn/timber/blob/master/lib/Theme.php).
```PHP
/**
* @api
* @var array return an array of theme information (ex: author, author URI)
*/
public $meta;
```
Collect data for `$meta` in `init` function:
```PHP
$this->meta = [
'theme_uri' => $this->theme->get('ThemeURI'),
'desc' => $this->theme->get('Description'),
'author' => $this->theme->get('Author'),
'author_uri' => $this->theme->get('AuthorURI')
];
```
This code does no harm things or have great impact on the core. It just simply get more data from `wp_get_theme()`. Totally safe.
See **Solution**, …
=> Add meta property for Timber\Theme

lib/Menu.php, tests/test-timber-menu.php
**Ticket**: #2000
Custom metadata stored via ACF on a WordPress menu was not accessible in templates
Since WordPress borrows the meta table and object for its menus, we should do the same. This PR simply adds a test and has `Menu` extend `Term` rather than `Core`
Seemingly very light. The class inheritance of the `Menu` item changes, but nothing else
None
A second thought/voice on whether this change in class inheritance could have larger negative consequences. This definitely feels like a very elegant solution, but a downside is that now `Menu` has some functions/properties with it that might not be meaningful or relevant to it being a `Menu` and not a `Term`
Wrote a new test to validate the meta behavior; all other tests pass
=> Meta data for Menu object

lib/Twig.php
_let's try this from the proper base branch 🤦‍♂_ 
see : https://github.com/timber/timber/pull/2062
This adds on `class_exists( 'Twig\Extension\EscaperExtension' )`
[As of Twig 2.11, the Twig\Extension\CoreExtension::setEscaper() and Twig\Extension\CoreExtension::getEscapers() are deprecated. Use the same methods on Twig\Extension\EscaperExtension instead.](https://twig.symfony.com/doc/2.x/deprecated.html#extensions)
=> Twig\Extension\CoreExtension::setEscaper() is deprecated

lib/Loader.php
**Ticket**: #2084
A false debug status seems to screw with something in new Twig versions, triggering a WSOD
Don't tell the Twig Environment the value of `WP_DEBUG`
Let's see — more investigation required following the results of automated test and review of Twig source (and changes in recent versions)
None
Let's see what Twig debugging is doing and whether it should be accessible from the Timber or WP layers
No new tests
=> Remove debug attribute sent to TwigEnvironment based on #2084

lib/Admin.php, lib/Timber.php
**Ticket**: #2112
The view details link on the plugins screen is 'hardcoded' and is always relative to root. If you install WPP in a subfolder it'll break.
Solution explained [here](https://github.com/timber/timber/issues/2112#issue-524300512)
None
None that I can see
No
=> Fix non-relative site url

lib/Twig.php
**Ticket**: #2120
In #1594 we made a custom `filter` filter (confusing yet?). Not long after, Twig introduced its own `filter` filter with a similar behavior (though different syntax):
https://twig.symfony.com/doc/2.x/filters/filter.html
Deprecate the filter in 1.x — I'm going to do another PR to remove it from 2.0 all together
No usage change. 1.x users would still use the "old" syntax to use `filter`. I can't think of a good way to let someone disable our custom `filter` filter w/o doing a whole mini-production
In a perfect world we would do that mini-production, but I think we should focus on ...
a) acknowledge the issue
b) truly resolve in 2.0
=> ref #2120 #1594 -- deprecate custom filter filter

composer.json, lib/Helper.php, lib/Twig.php, tests/test-timber-helper.php
**Ticket**: #2010 
Twig and Timber have filter called `filter` and now we have a problem.
Adds new filter called `wp_list_filter` and adds backward compatibility and warning to normal `filter`.
User's that use the `filter` and with string or array as second param will get a warning.
The twig filter works a bit different - https://twig.symfony.com/doc/3.x/filters/filter.html.
Not yet
=> Twig filter

lib/ImageHelper.php
**Ticket**: #2118
There are some situations where a double slash can occur (server or setting-specific?) in an image path. This removes them.
Make sure the original URL doesn't end with a trailing slash. THEN apply one
This seems to be a more elegant way of ensuring there aren't double slashes at a concatenation point, without applying the brute force-style `TimberURLHelper::remove_double_slashes` that was commented-out
None!
There could be another place in the code that's causing the error seen in #2118 — but this one seems promising
No new tests required, let's see what Travis says ...
=> Prevent double slashes in URLs

.editorconfig
PhpStorm flagged a syntax issue in the **.editorconfig** file. Apparently, listing multiple patterns with commas doesn’t seem to be possible?
```ini
[*.txt,wp-config-sample.php]
```
Create separate rules instead of separating rules by comma.
Rules should be applied.
None.
None?
Nope.
=> Fix .editorconfig syntax

lib/Helper.php
The `Timber\Helper::deprecated()` function contains some code that is unnecessary. And I saw some other optimizations that would make the function more readable.
- Remove check for `__()` / handling of translated strings. We don’t have any translatable strings in Timber. Otherwise, we would need to have a `timber` text domain that we would have to add to strings.
- Remove unneeded check for `WP_DEBUG`.
- Use bailout instead of if-wrapping.
- Add info about using `@expectedDeprecated` in tests.
None.
None.
None.
Nope.
=> 2.x Improve Helper::deprecated()

tests/test-timber-meta.php
**Ticket**: #2073 
Fixing some failing comment tests!
Comments were being created w/o relationship to a post object. This meant when `CommentFactory::get_comment_class` went to try and figure out what class to use it was like, "well I can't match this up to a class b/c it doesn't have a post associated with it (thus no `post_type`)
Making this a PR to your branch so that you can double-check that I did things right and this is your intent
=> 2.x factories test fixes

lib/Helper.php
**Ticket**: #2146, #2154
There are many test errors in 2.x, because I got a bailout wrong in #2146. Sorry for that.
Fix bailout.
Tests should work again.
None.
None.
None.
=> 2.x Fix deprecated() function

tests/Timber_UnitTestCase.php, tests/test-timber-meta.php
**Ticket**: #2153
See #2153 
Add a test helper for adding a self-removing filter. I didn't end up implementing the same for `add_action` since there are very few calls in the tests at this time. We can always add that in the future if desired.
Affects tests only, and allows for cleanly refactoring existing tests. Pure refactor; doesn't change production or test functionality.
None.
Let's just switch direct `add_filter()` calls over as we find time.
Why, yes!
=> #2153 add a test helper for auto-removing filters

composer.json, docs/upgrade-guides/2.0.md, lib/Admin.php, tests/test-timber-admin.php
**Ticket**: #2151 
As discussed in #2135, we're dropping support for WordPress versions prior to 5.3 in 2.x. To do this, we need to let people know.
Let 'em know! Through the upgrade guide, ensuring the `require-dev` in composer is correct (we can't do comments/annotations in here, but this is one way to indicate) and an admin notice in case someone is running a WP version that's older than 5.3.
Once inside of the `Admin` class I realized we could get rid of the bulk of what's here since it modifies the plug-in entry for Timber (which we're also not supporting in 2.x, in favor of Composer/Packagist only)
This helps let devs know to upgrade their WordPress.
We could copy over some of this code into 1.x (perhaps upon the last release to WP.org) to let people know that there won't be any …
=> Provide notice for min. WordPress version

lib/Timber.php, tests/test-timber-filters.php
Just a few touch-ups on some missing test coverage, uncovered a small error stemming from the removal of `Timber::fetch`
=> A little more 2.x test coverage

.travis.yml, tests/test-timber-post-getter.php
We can easily cut down the number of tests that are run on 2.x builds w/o sacrificing utility
Remove two extra PHP 7.2 builds. Also removed part of a weird test that didn't really tell us anything, but failed 1% of the time just due to the math matching up.
Tests should run about ~5 mins faster in total by dropping these
None.
Everything passes locally ...
=> Some quick testing fixes

lib/Post.php
**Ticket**: #2137
In version 4.6, WordPress added additional parameters for some of the filters that we also apply.
Let’s update the applied filters with the new parameters. And add some more documentation.
But behold. Sometimes these filters expect a `WP_Post` object as the last parameter. I think we can’t return `$this` / the `Timber\Post` object, because that could lead to compatibility issues in case any plugin uses this filter.
- `get_the_date` – Expects `int|WP_Post` The post object or ID.
- `get_the_modified_date` – Expects `WP_Post|null` WP_Post object or null if no post is found.
- `get_the_time` – Expects `int|WP_Post` The post object or ID.
- `get_the_modified_time` – Expects `WP_Post|null` WP_Post object or null if no post is found.
As you can see, `get_the_modified_date` and …
=> 2.x Optimize post date filters

docs/guides/class-maps.md, docs/guides/users.md
**Ticket**: https://github.com/timber/timber/pull/2160#issuecomment-572745383
We already have new guides for Posts and Terms in #2073. We should have one for Users as well.
Add Users Guide and clarify working with User Class Maps.
None.
None.
None?
None needed.
=> 2.x Add a Users Guide

lib/Helper.php
**Ticket**: #621
Errors dropped into the nginx/apache error log are not easily traced back to Timber.
Prefix errors that come from Timber with `[ Timber ]`
None. Will change the look of some error logs I guess?
Note
Should other warnings/output be similarly indicated?
No new tests
=> Prefix error_log output with "[ Timber ]"

lib/Post.php, readme.txt, tests/test-timber-integrations.php
**Ticket**: #2143 
A field named "content" made by ACF overwrites the Post objects `$post->_content` variable because ACF uses an underscore naming pattern.
Rename `$post->_content` ==> `$post->___content` to avoid the collision.
Anyone relying the current "buggy" code will have their shit broke.
Even though the meta/raw_meta stuff in 2.x is still fixed — we should make sure a similar `_content` issue isn't present there.
Wrote a new test to confirm buggy behavior and that this resolves
=> Fix bug where field named "content" could overwrite post.content

.travis.yml, lib/Comment.php, lib/Image.php, lib/Integrations/CoAuthorsPlusUser.php, lib/MenuItem.php, lib/Site.php, phpstan.neon
This branch / PR is meant to handle compliance with PHPStan Level 1 issues. Per @szepeviktor's [comment](https://github.com/timber/timber/pull/2165#issuecomment-573457549) in #2165, we won't be able to do anything about the `apply_filters` argument count errors (due to how WP declares that function) but we can get our house in order with declaring properties on various Timber classes.
=> phpstan: Level 1 compliance

lib/PostGetter.php
**Ticket**: #2199 
`PostGetter::get_posts` can return `null`. When calling `reset()` on the result, we get an error because it's not an array or iterable.
Add a sanity check for iterability
Should be none, just another check
None
No explicit test added for the scenario.
=> Apply patch from #2199

lib/PostGetter.php
When a Class Map filter is used and Timber doesn’t find a post type in the Class Map, it will output a notice:
```
[ Timber ]posttype not found in Array
```
I think that the notice is unnecessary, because it’s possible to only add certain post types to the Class Map and let Timber fall back to the default `Timber\Post` for the ones that are not defined. I think the notice might even be confusing.
Remove the error log. And fix a small spelling error.
None.
None.
I wonder if there’s some other thinking to this, that I didn’t consider yet?
No.
=> Remove useless error log for Class Maps

lib/Timber.php
Autocompletion fails with phpStorm because it can't derive the correct class.
This helps with autocompletion when working with phpStorm.
=> Add Timber\Post class as a return type to query_post

lib/Timber.php, tests/test-timber.php
**Ticket**: #2169
This pull request adds on top of #2169. But because I had to change more than I thought, this comes in a separate pull request so we can discuss it first.
In https://github.com/timber/timber/pull/2169/commits/302e08b78937fcc7ec0505d1e1592b78a38e4e99, you changed the order the posts were created. This go me thinking. If we want to check for the oldest post and make sure we ignore the post ID, which is an indicator of the order the posts were created in, then the post expect to be returned [shouldn’t be the first to be created](https://github.com/timber/timber/commit/8705f311e6fcdd854673d001bcec2d1a8f02a2b6).
In https://github.com/timber/timber/pull/2169/commits/58d24dd9657674f277fd6e7c6b155a580321f2c6, you changed the parameter in the test to `any`, which is not the same …
=> 2.x Improve Timber::get_post_by()

lib/URLHelper.php, tests/test-timber-url-helper.php
I'm using https://github.com/humanmade/S3-Uploads to handle file upload.  `Timber\URLHelper::remove_double_slashes` is breaking `resize` filter for any image with `s3://` prefix
I'm just adding s3 to the schemes whitelist
Shouldn't break anything
None
Maybe build url without scheme first, remove double slashes then prepend url scheme.
Yes
=> Fix s3 url

lib/Helper.php, lib/Post.php, tests/test-timber-helper.php, tests/test-timber-post.php
**Ticket**: https://github.com/timber/timber/pull/2073#issuecomment-586538864, #2145
In https://github.com/timber/timber/pull/2073#issuecomment-580343556 and the following comments, we discussed whether we should use Exceptions or work with calls to `Helper::doing_it_wrong()`.
This pull request pulls out the `Helper::doing_it_wrong()` function I added in #2145 and adds improvements.
I would like to go with the solution that @acobster suggested in https://github.com/timber/timber/pull/2073#issuecomment-586538864 and move the calls to `doing_it_wrong_run` and `deprecated_function_run` in front of the bailout check with `WP_DEBUG`.
To say it in @acobster’s words:
> This gives folks an escape hatch for refactoring (which I consider the main use-case for `doing_it_wrong` to begin with) where …
=> 2.x Improve error handling

lib/URLHelper.php, tests/test-timber-url-helper.php
Handling image resizing for images with gs:// url
Extending url whitelist with the 'gs'.
none
Changes are same as it was in the case of s3 urls. Basically just copy-paste.
The very same test as in the case of testDoubleSlashesWithS3.
=> Extending for Google Storage

lib/Helper.php, lib/Timber.php, tests/test-timber-loader.php
**Ticket**: #2224 
If the twig file doesn't exist than it fails silently.
Throwing a warning if a template doesn't exist.
Shouldn't have any. `compile()` still return false
=> Throws warning on invalid template

lib/Twig.php, readme.txt, tests/Timber_UnitTestCase.php, tests/bootstrap.php, tests/test-timber-dates.php, tests/test-timber-site.php
**Ticket**: #2214
The `time_ago()` method has two parameters that aren’t translated yet.
Use WordPress Core translations when default parameters are used.
I’ve thought about whether relying on the Core Translations is a good idea, because it’s actually not advised by WordPress. WordPress suggests introducing your own text domain for your translations, because WordPress translations might change.
I then checked what translations Timber actually uses, and it’s really only a couple of Core Translations:
- `%1$s %2$d`
- `%1$s`
- `&hellip;`
And then there are translations that are never really used, because they are only used as defaults:
- `&laquo; Previous`
- `Next &raquo;`
https://github.com/timber/timber/blob/a882871a2174e4d17fbccdb7448a9df9366f72d8/lib/Pagination.php#L115-L116
I think …
=> Make strings in time_ago() translatable

lib/Loader.php, lib/Timber.php, lib/Twig.php
**Ticket**: #1754
To make gettext extraction work, the `Timber\Twig` class needs to be instantiated without a WordPress environment. For this, we need to remove / work around WordPress functions in the `Timber\Twig::add_timber_functions()` method.
This pull request
- Moves the hooks out of the constructor.
- Moves the `timber/twig` filter to the `Timber\Loader` class.
There should be no impact.
By moving the `timber/twig` filter into the `Timber\Loader` class, we make sure that custom functionality is added to the Twig Environment as a last step, which is probably what most would expect.
If a duplicate filter or function is added to Twig, the order doesn’t matter, there will always be a `LogicException`. However, if your custom function or filter causes the error, the error log would …
=> Gettext extraction

lib/Loader.php, lib/Twig.php
**Ticket**: #2238
Just as I expected, the filters weren’t merged properly, probably because of earlier filter refactors involving big DocBlocks.
Move the filters to their proper place.
None.
None.
None.
None.
=> 2.x Fix gettext-extraction merge bugs

docs/guides/wp-integration.md
Missing examples to how to use **Twig** `filter` tag in template file. 
Examples have been added to doc.
This examples are useful with **WooCommerce** integration when you need to pass a large amount of code inside a filter. Better for readability.
=> Add example to apply_filters in doc

docs/guides/class-maps.md
**Ticket**: #2089
There are some improvements that we can make to the Menu Class Maps.
According to what was proposed in #2089 
- The menu class map should receive a menu object (a `WP_Term`) instead of a `$location` string.
- Removes the `$location` parameter from the Menu Item Class Map, because that is already present through `$menu->theme_location`.
- Adds more examples for how to use the Menu Class Maps.
None.
None.
\-
No.
=> 2.x Menu docs optimizations

docs/guides/class-maps.md, docs/guides/menus.md, docs/upgrade-guides/2.0.md
**Ticket**: #2089
As discussed in https://github.com/timber/timber/issues/2089#issuecomment-629852632, we need documentation for the new Pages Menu.
Add documentation in the Menus Guide, the Class Maps Guide and the Upgrade Guide.
A new API to create a menu from the existing pages dynamically:
* A `Timber\PagesMenu` class. 
* A `timber/pages_menu/classmap` filter.
* A `Timber::get_pages_menu()` function.
I didn’t come up with big examples, because I think this will feature will be mainly for simpler sites, where custom classes might often not be needed anyways. Or may I just felt like a lazy dog.
No.
=> 2.x Add documentation for new Pages Menu API

lib/Post.php, tests/test-timber-post-content.php
**Ticket**: #2218
Using a Gutenberg "More" block you can set an option for "Hide the excerpt on the full content page":
However, Timber doesn't respect carry this through to the single content page because it's handled for in some way outside of `the_content` filters and other things used by Timber (in tests the `twentynineteen` theme handled correctly.
I wrote a function in `Timber\Post` that handles for this (edge?)case
This will correct a bug. All old tests pass, I'd consider it fully backwards-compatible. (The only theoretical error is if someone used the tags generated by Gutenberg in a manual way hoping for them to have the opposite effect).
None.
We could fully reverse-engineer how WP is doing it so that it hooks into the exact logic. I'm comfortable with this step unless something …
=> Resolve issue with more tags from Gutenberg

tests/test-timber-shortcodes.php
Added test to verify the basic `|shortcodes` filter to confirm the basic functionality for #2268
=> Add test to verify #2268

docs/v2/getting-started/setup.md, docs/v2/getting-started/video-tutorials.md, docs/v2/guides/context.md, docs/v2/guides/cookbook-images.md, docs/v2/guides/cookbook-text.md, docs/v2/guides/custom-fields.md, docs/v2/guides/functions.md, docs/v2/guides/internationalization.md, docs/v2/guides/performance.md, docs/v2/guides/wp-integration.md, docs/v2/upgrade-guides/2.0.md
Before I merge in https://github.com/timber/docs/pull/12 to put the new documentation online, I want to fix some links.
- Always use absolute URLs with `https://timber.github.io/docs/`, so that the URLs also work when we click them in GitHub and not lead to 404s.
- Make sure we use `https://timber.github.io/docs/v2/` for version 2 docs. As soon as we release v2, we will have to revert that and use `https://timber.github.io/docs/v1/` for version 1 docs.
=> 2.x Fix some URLs in documentation

docs/v2/guides/extending-timber.md
With 2.x, the concept of extending Timber with your own classes is becoming more prominent and relevant, especially because everything will evolve around Class Maps. While the new [Class Maps Guide](https://github.com/timber/timber/blob/2.x-docs-api/docs/v2/guides/class-maps.md) is good for showing the different Class Maps and how to work with them, we could still show some more real-world examples for how to use your custom methods.
You can look at the updated [Extending Timber Guide](https://github.com/timber/timber/blob/2.x-docs-extending-timber/docs/v2/guides/extending-timber.md).
What’s new:
- I started out with an example for a more basic custom method in a custom class and how to add it to the Class Maps.
- Added an example for how to move from adding to `$context` to using a …
=> 2.x Update Extending Timber Guide

lib/Loader.php, readme.txt
**Ticket**: #2217 
When using the `{{ dump() }}` function with WP_DEBUG set to false, the site throws Fatal error: Uncaught Twig\Error\SyntaxError: Unknown "dump" function. This causes a problem if one of these statements is accidentally committed and then rendered in an environment that does not have debug set to true - whether that's production, staging, or even another dev's local install.
Supply a dummy definition to `{{ dump() }}` so no fatal error results
Should make it easier for when a dev has forgotten to remove a dump function (which they should). But a WSOD seems like an excessive punishment.
None.
One could argue this promotes laziness, but I think it helps match the reality that many of us code against. In terms of the solutions discussed in #2217, this is the "lightest …
=> Provide a non-functional definition for Twig's `dump` function

docs/guides/hosts-servers.md, lib/ImageHelper.php, tests/test-timber-wp-vip.php
The WordPress VIP team requested the ability to disable file writes in order to make Timber play nice with their tech stack.
Add a `timber/allow_fs_write` filter that any dev can control. Defaults to true.
Should have no backwards compatibility effect. This defaults to true, so it will have the same behavior in all existing installs.
Rather than create a guide _just_ for WP VIP, I added a new guide for "Hosts & Servers" that describes the steps WP VIP users will need to consider. This can be expanded as people contribute any platform-specific notes (both hosts like Pantheon, but also services like AWS/Azure).
1. For WP VIP: we should investigate how `resize` can play with the [Photon API](https://developer.wordpress.com/docs/photon/api/). Shouldn't be too hard, but I think it's for a …
=> WordPress VIP Compatibility Requests

README.md
We have **two** coverage status providers.
@jarednova Looks very nice.
=> Fix coverage chaos in README

.travis.yml
Basically conditionals should be avoided in all CI workflows.
CI jobs should be listed explicitly.
I plan to remove `$COVERAGE` after this one gets merged.
=> Get rid of IMG_LIBS variable in Travis config

docs/v1/getting-started/getting-started.json, docs/v1/guides/guides.json, docs/v1/reference/reference.json, docs/v1/upgrade-guides/upgrade-guides.json, docs/v2/getting-started/getting-started.json, docs/v2/guides/guides.json, docs/v2/hooks/hooks.json, docs/v2/installation/installation.json, docs/v2/integrations/integrations.json, docs/v2/reference/reference.json, docs/v2/upgrade-guides/upgrade-guides.json
Currently, when searchin the Docs, the sections are messed up, because I obviously used a selector that isnt’t unique on a page.
In the following example, you can see that a search for "Comments" is marked under the sections "Upgrade Guides" and "Contributing".
This is because the section title is determined by the `.navMain-sectionTitle` selector, which appears multiple times. Algolia obviously has no way to know which section we’re in.
This pull request changes the the title in the data from `title` to `sectionTitle` so we can reference it in the sidebar and use a unique CSS class that hopefully solves this issue. If we’d continue using `title`, it would always be overriden by a page’s title. So I had to use another name.
Hopefully fixes search.
None.
None yet.
I already put the changes …
=> 2.x Docs – Update section data to fix doc search

docs/v2/guides/pagination.md, lib/Post.php
When looking at a couple of issues here in Timber, I felt that there was often confusion about pagination, because there are actually 3 types of pagination (that I know of).
I tried to describe the different sorts of pagination and provide examples for how to use them. You can have a look at the updated guide here: https://github.com/timber/timber/blob/2.x-docs-pagination/docs/v2/guides/pagination.md.
I also updated some of the DocBlocks for the related methods.
I’m doing the pull request against the `2.x-docs-api` branch (#2073), because this affects the pagination for posts, which should work with `Timber::get_posts()` in the future. In v1, it only worked with `Timber\PostQuery`.
Hopefully, this will provide better guidance.
None.
I wonder whether we actually need …
=> 2.x – Improve documentation for pagination

docs/v1/guides/gutenberg.md, docs/v1/guides/hosts-servers.md, docs/v2/guides/gutenberg.md, docs/v2/guides/hosts-servers.md
This pull request fixes two things.
1. Adds the *Hosts & Servers* Guide that was added in #2250 to version 2 of the docs as well.
2. Optimizes the Gutenberg guide by including the official name "Block Editor" and adding a missing `order` parameter.
None.
We need to remember that if we change documentation in `master`, we need to port it over to `2.x` as well, because `2.x` is the current master for the [live documentation](https://timber.github.io/docs/).
=> 2.x Guides optimizations

lib/Helper.php, lib/Twig.php
**Ticket**: #2301
As pointed out by @gchtr:
This issue was raised in https://wordpress.org/support/topic/args-passed-to-twig_array_filter-must-be-an-instance-of-twigenvironment/.
In this commit, they changed the parameters from
```php
function twig_array_filter($array, $arrow) {}
```
to
```php
function twig_array_filter(Environment $env, $array, $arrow) {}
```
Yes, they prepended a parameter. This now conflicts with the patch we introduced in Timber 1.14.0, in #2124 to be exact. The tricky thing would be to get the Twig environment in there. Or maybe we need to take a completely different approach.
Simply replace the call to the native PHP `array_filter` function. I copied the third parameter of the `\ARRAY_FILTER_USE_BOTH` constant as well to match what Twig is doing internally.
Fixes a …
=> Update Helper.php / twig_array_filter

docs/v2/getting-started/introduction.md
**Ticket**: https://github.com/timber/learn-timber-theme/issues/1
"Learn Timber Theme" is a clearer name than "Getting Started Theme"
Let’s rename it.
None.
None.
None.
I tested the `composer create-project` command. It works.
=> 2.x – Rename "Getting Started Theme" to "Learn Timber Theme"

lib/Helper.php
#2301
The recent changes made in #2301 triggered many errors in my templates (`array_filter` running on `PostColelction` object). I use `filter` a lot and I use it against `PostCollection` which isn't an array. 
Implement the native `twig_array_filter` method: https://github.com/twigphp/Twig/blob/1fb577363d3e3b5ce1b737b3255f2491b5f80833/src/Extension/CoreExtension.php#L1588-L1593
It shouldn't because that method was used before that change.
None.
=> #2301 Keep Twig native `filter` parity

lib/ImageHelper.php
**Ticket**: #2216
After having sideloaded an external image, the temporary file created by download_url is not deleted.
This deletes the temporary file after it has been uploaded to wordpress.
No impact, bug fix.
None
None
No unit tests added.
=> fix #2216: delete sideloaded image tmp files

lib/Image.php
`webp` isn't in the list of recognized image extensions. So `webp` images will fail `Image::is_image()` check
Add it!
Should resolve unseen issues of it upper-level functions failing.
None
We've been unable to test against Webp previously on Travis. This would be a good time to figure that out (I've been able to test locally successfully, it seems to be because of how the Travis PHP build is configured)
We've been unable to test against Webp previously on Travis. This would be a good time to figure that out (I've been able to test locally successfully, it seems to be because of how the Travis PHP build is configured)
=> Add webp to recognized image extensions

lib/Loader.php
If `WP_DEBUG` is disabled, a Fatal Error will be thrown: "Class 'Timber\Twig_Function' not found". This just fixes the name so we're using the right class.
I'm just starting to integrate our budding 2.x alpha on a real project, and this is the first thing I ran into. Looks like a code path that's probably not covered by the tests, but I don't have time to figure out how to test using different constants. But the fix is about as simple as it gets.
`use` the correct `Twig\TwigFunction` class within Loader.
The thing will work now! :smile: 
None
How can we test this reliably? Is it worth it?
None for now.
=> upgrade Loader to use renamed Twig\TwigFunction

composer.json
Up until some time ago, there wasn’t any stable release for [twig/cache-extension](https://github.com/twigphp/twig-cache-extension). But luckily, now [there are](https://github.com/twigphp/twig-cache-extension/releases). Let’s use them.
Better control and predictability for when a new version of `twig/cache-extension` comes out.
None.
None.
Should be covered by existing tests.
=> 2.x Use stable release of twig/cache-extension

lib/Twig.php
**Ticket**: #2327
After seeing #2327, I checked whether we forgot some other deprecated Twig classes, and found one instance, which I’m changing with this pull request.
None.
None.
None.
Should be covered by existing tests.
=> 2.x Update deprecated Twig class

docs/v2/guides/posts.md
**Ticket**: #2311
As one of the final documentation issues in #2073, we should document JSON serialization of posts that was added in #2311.
Take a stab at adding an example with a book post.
Even more insights about posts and advanced Timber coding.
None.
@acobster I hope I got everything right!
Also, in https://github.com/timber/timber/pull/2311#issuecomment-677820224 you had an idea to implement `jsonSerialize()` in `Timber\Post`.
> > Yeah, in addition to providing some sensible default behavior in `Timber\Post` (I just wanted to avoid touching Post too much in this PR, and just focus on collections). Child implementations can easily call `parent::jsonSerialize()` to get the data to use as a basis, so we should capture that in the docs.
> 
> Right, good idea! We should definitely also …
=> 2.x Document post serialization

lib/Timber.php, lib/Twig.php, tests/test-timber-image.php
**Ticket**: #2333
Discussed in detail in the linked issue and in #2316 .
Aliases and docs for `::get_image()` and `::get_attachment()` and corresponding Twig functions.
A slightly bigger but less confusing API.
MOAR METHODS
We threw out the idea of adding `::get_images()` and `::get_attachments()` (plural) for consistency. I don't see as strong a reason to have these in there, and they're potentially even more confusing because of the potential for getting back a mixed bag of concrete classes.
Yes, test all the things!
=> 2.x images api

composer.json, docs/guides/performance.md, lib/Cache/KeyGenerator.php, lib/Cache/WPObjectCacheAdapter.php, lib/Loader.php
resolves notice : 
> Package asm89/twig-cache-extension is abandoned, you should avoid using it. Use twig/cache-extension instead.
fixes : https://github.com/timber/timber/issues/2347
=> replace : asm89/twig-cache-extension

lib/Post.php
**Ticket**: https://github.com/timber/timber/issues/2337
Using `{{post.content}}` in a Post that contains a "Read More" block from Gutenberg with the option to hide the excerpt enabled sometimes does NOT hide the excerpt on full content page.
Added an additional check for `'"noTeaser":true'` tag to cover the possibility that it contains double quotes.
This should be 100% backwards-compatible, as it only adds a `strpos(...)` check with a `||` operator. The change will only correct the bug for instances of WordPress that use double quotes to surround `noTeaser` tag part.
None.
While repeating chunks of code (in this case `strpos(...)`) is not ideal, I tend to think that this is less error-prone in this case since dealing with quotes in a variable content can often lead to unexpected …
=> Adding double quotes check when using Read More block from Gutenberg

lib/Loader.php
In the process of trying to override the `\Twig\Loader\FilesystemLoader` passed over on the WordPress filter `timber/loader/loader` it is required to pass over `$paths`, and `$rootPath` as arguments to the Loader class as seeing here: 
https://github.com/timber/timber/blob/master/lib/Loader.php#L149
```php
$fs = new \Twig\Loader\FilesystemLoader($paths, $rootPath);
```
The problem lies in the fact that the provided filter doesn't pass over the needed variables to accomplish this:
https://github.com/timber/timber/blob/master/lib/Loader.php#L150
```php
$fs = apply_filters('timber/loader/loader', $fs);
```
This can be resolved by simply passing over the required variables like in this PR:
```php
$fs = apply_filters('timber/loader/loader', $fs, $paths, $rootPath);
```
There should not be any …
=> Pass more variables to the `timber/loader/loader` filter

lib/Helper.php, lib/Loader.php, lib/Site.php, lib/Twig.php, tests/test-timber-helper.php
Functionality that was deprecated in 1.x can be removed in 2.x. And I see that not every was catched by THE PURGE in #2323.
Search for `@todo` tags that tell us to remove 1.x functionality and actually remove it.
Breaking Changes.
Were already covered in 1.x.
Any?
Maybe we still need to update some tests. Let’s see.
=> 2.x Remove functionality deprecated in 1.x

lib/Timber.php, tests/test-timber.php
Here's something I've had kicking around in my head for a while. :)
In [Conifer](coniferplug.in/), which we use on pretty much every WP site at SiteCrafting, we have the nice convenience of being able to pass extra data to `Conifer\Site::context()`, which delegates to `Timber::context()` and just adds this merging capability on top. It means that this code:
```php
$data = Timber::context();
$data['extra'] = 'stuff';
```
Becomes:
```php
$data = $site->context([ 'extra' => 'stuff' ]);
```
I usually err on the side of not expanding an API if you can help it, but this is extremely convenient and I've found it makes template code way more readable, especially when you have a lot of extra stuff you need to get into your view data from your template. It turns a bunch of separate, imperative …
=> support passing extra args to Timber::context()

lib/Site.php
**Ticket**: #1908 
In a multisite environment `Timber::get_sites()` returns the same locale for all sites in backend (and frontend also, if user is logged in). This also happens while using `new Timber\Site()`.
When using `get_bloginfo( 'language' )`, then `determine_locale()` is used, which considers the language set in the user profile. This could lead to all the sites returning the same language when a user overwrites it in their profile on all sites. 
Using `get_locale()` is way more predictable, because it always uses the language setting used for a site.
No problems expected.
Use `Timber::get_sites()` and new Timber\Site() as before.
=> Multisite Timber::get_sites() returns same locale for all sites (#1908)

lib/Twig.php, tests/test-timber-twig-number-format-filter-default.php, tests/test-timber-twig-number-format-filter.php
Hello Timber team!
You took care of `date` filter but `number_format` seemed forgotten.
Grabs WordPress locale settings (`decimal_point`, `thousands_sep`) and set [Twig number format](https://twig.symfony.com/doc/2.x/filters/number_format.html).
No locale was set before this. So Twig applied the default PHP locale. If someone set custom `number_format` on the filter level, it will still work as exptected.
Not that I'm aware of. This setting didn't exists before and is automatic now because it depends on `$wp_locale`. 
Use PHP Locale would be great.
Yes, taken from Twig's tests and adapted.
=> Make number_format support WordPress locale

composer.json
The version of upstatement/routes (0.5) used by Timber is mishandling URLs when using it with a multilingual plugin like WPML, as shown on this issue from the lib repository: [https://github.com/Upstatement/routes/issues/12](https://github.com/Upstatement/routes/issues/12)
Bump upstatement/routes to latest version (0.8).
The 0.6 release was motivated by this exact issue: [Fix issue with WPML](https://github.com/Upstatement/routes/releases/tag/0.6) Since then no breaking changes have been introduced.
No expected impact. Not much has changed other than this bug fix and some dependencies updates.
[Comparing 0.5...0.8 · Upstatement/routes](https://github.com/Upstatement/routes/compare/0.5...0.8)
=> Bump upstatement/routes package to 0.8

lib/ImageHelper.php, lib/Integrations/WPML.php, lib/URLHelper.php, tests/test-timber-url-helper.php
**Ticket**: #2356 
site_url() returns a wrong url on bedrock based installations, since site_url() returns https://yourdomain.com/wp since the WP installation lives in this directory.
Relevant file structure of a Bedrock based project:
├── Other stuff, no relevant for this PR.
└── web                        → Web root (document root on your webserver)
├── app                    → **wp-content equivalent**
│   ├── mu-plugins   → Must use plugins
│   ├── plugins         → Plugins
│   ├── themes         → Themes
│   └── uploads         → Uploads
├── wp-config.php    → Required by WP (never edit)
├── index.php           → WordPress view bootstrapper
└── wp                     → **WordPress core**
When using home_url() this issue is resolved.
In my initial issue I found out that changing …
=> fix two cases where site_url() was used instead of home_url()

tests/test-timber-twig-date-function.php
There's a routine test around date comparisons that fails ~2% of the time due to some fraction of a second elapsing between two calls to the unix epoch timestamp.
Round things by 10 to reduce/eliminate this scenario.
No more randomly failing tests (at least for this one, hopefully)
None
Updated/renamed one test and the docblock info
=> Fix a very annoying test

docs/v2/upgrade-guides/2.0.md, lib/Post.php, lib/PostExcerpt.php, lib/PostPreview.php, tests/test-timber-filters.php, tests/test-timber-post-excerpt-object.php, tests/test-timber-post-excerpt.php, tests/test-timber-post-preview.php, tests/test-timber-post.php, tests/test-timber.php
Functions that were deprecated in 1.x can be removed in 2.x. `Post::get_preview()` is one of these candidates.
- Delete the method and update tests.
- Add an `@api` tag to the `PostPreview` class so that it appears in the documentation, because currently, it’s missing.
Breaking change.
`Post::preview()` or `new PostPreview()` should be used.
When using `$preview = new PostPreview()` in PHP, you’ll have to do `(string) $preview` for it to be converted to string (so that `__toString()` kicks in), because `PostPreview::run()` is protected. I don’t like this API very much. Are there better solutions?
- `$preview->to_string()`?
- `$preview->get()`?
- others?
There’s a failing test because when we use an empty string as the value for the `readmore` option, a Readmore link will still be added. …
=> 2.x Clean up post preview

.github/ISSUE_TEMPLATE/config.yml
This adds an additional link to the issue template chooser that directs people to Stack Overflow for support questions.
I already added it over at the [timber/docs](https://github.com/timber/docs/issues/new/choose) repo, where it looks like this:
Relevant documentation for the template chooser can be found here: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> Create config.yml for issue templates

docs/guides/menus.md
**Add 2 code samples, which show how to use the global $context for more than one menu.**
1. Declare plural menus in `functions.php`.
2. Use one menu of several in Twig markup.
The `docs/menus.md` did not have an example, in which more than one menu was declared in the global `$context`. As such, I created two menus, but with the latter overriding the former at `$context['menu']`. This led to the behavior that only one menu was available in the markup.
Write a Markdown file with examples showing how to declare more than one menu. Use the example menu in Twig markup.
This Pull Request does not affect the PHP codebase. It is an addition of 30 lines to `/docs/menus.md`.
I do not think there are usage changes. Please correct me if I am wrong.
The `menus.md` file will look more fleshed out as …
=> 📝 Add to menus.md: Code samples using > 1 menu

docs/v2/upgrade-guides/2.0.md, lib/PostExcerpt.php, tests/test-timber-post-excerpt-object.php, tests/test-timber-post-excerpt.php
**Ticket**: #2365, #1345
When using Timber’s excerpt functionality, the read more link is always added – even if the post’s content isn’t longer than the excerpt.
First, there are two new options for post excerpts that can both be passed to the `Post::excerpt()` function as well as when using `new PostExcerpt()`:
- `always_add_read_more` – Controls whether a read more link should be added even if the excerpt isn’t trimmed (when the excerpt isn’t shorter than the post’s content). The default is `true` in order to not break backwards compatibility.
- `always_add_end` – Whether the end string should be added even if the excerpt isn’t trimmed. The default is `false`, because to me, that was a bug before.
More thoughts about why I chose these defaults can be found in …
=> 2.x Add options to better control read_more and end behavior in post excerpts

docs/v1/guides/acf-cookbook.md, docs/v2/upgrade-guides/2.0.md
Some documentation issues.
- Fix an issue with anchor links while building the docs when a Markdown heading contains "".
- Fix instances of where I used the new `get_image()` function in documentation for Timber v1, where it should still be `Image()`.
None.
Current documentation at https://timber.github.io/docs/ is already built from this branch.
None.
=> 2.x Documentation fixes

docs/v2/getting-started/a-post-archive.md, docs/v2/getting-started/introduction.md, docs/v2/guides/cheatsheet.md, docs/v2/guides/context.md, docs/v2/guides/cookbook-images.md, docs/v2/guides/cookbook-twig.md, docs/v2/guides/custom-page-templates.md, docs/v2/guides/extending-timber.md, docs/v2/guides/filters.md, docs/v2/guides/functions.md, docs/v2/guides/menus.md, docs/v2/guides/pagination.md, docs/v2/guides/performance.md, docs/v2/guides/sidebars.md, docs/v2/guides/template-locations.md, docs/v2/guides/woocommerce.md, docs/v2/guides/wp-integration.md, docs/v2/index.md, docs/v2/integrations/advanced-custom-fields.md, docs/v2/upgrade-guides/1.0.md
Documentation formatting.
- Removes a couple of horizontal rules (`* * *`) we don’t need.
- Optimizes where we add `<?php` in front of PHP code examples. In general: when it’s a whole template file, there should be an opening tag, otherwise, the surrounding text should suggest what language it is, e.g. when it’s introduced with a filename (single.php, functions.php, etc).
- Uses more consistent file name formatting by using bold formatting instead of code formatting.
- Fixes a couple of newline inconsistencies.
- Fixes a couple of incorrect array declarations, when an array was declared by assigning a key.
More consistency. A little less clutter.
None.
None.
None, documentation only.
=> 2.x Documentation optimizations

docs/v2/integrations/advanced-custom-fields.md
**Ticket**: #2382
I added some optimizations for #2368 
- Moved new content from section about Reapeater Fields to Flexible Content Field section.
- Used `include()` function instead of `include` statement, as this is recommended by Twig, see https://twig.symfony.com/doc/3.x/tags/include.html.
- Added some syntax optimizations.
=> #2382 Optimizations for "How to split into chunks flexible content fields"

docs/v2/integrations/advanced-custom-fields.md
Add an example on how to split into small chunks flexible content fields thanks to `acf_fc_layout` value, it could be a way to build a landing page for instance.
It may be related to this issue [#90](https://github.com/timber/starter-theme/issues/90)
What do you think about it?
=> How to split into chunks flexible content fields

.github/SUPPORT.md, CONTRIBUTING.md, README.md
Gitter is mostly tumbleweeds. Even if it weren't, we don't have the ability to provide the "live" support that Gitter's interface suggests.
Remove the refs (and replace with GitHub Discussions an a few spots)
We should also probably post a message and/or turn off the Gitter instance.
None needed
=> Replace Gitter refs with GitHub Discssions

lib/Term.php, tests/test-timber-term-factories.php
**Ticket**: #2386 
There's a dormant `Term::from()` method hiding out. Sort of a primordial implementation of Factories. Of course, we now have real Factories so it can go.
Since it was public and `@api` I've deprecated the function
I'm guessing it's a narrow number of users who were using this. The deprecation notices/warnings should help them find their way
Re-enabled the tests that were connected. Since it's deprecated, I'll make it test the new Factories equivalents
=> #2386 Remove dormant Term::from() methods

docs/v2/guides/terms.md, docs/v2/upgrade-guides/2.0.md, lib/Timber.php, lib/Twig.php, tests/test-term-factory.php, tests/test-timber-term-factories.php, tests/test-timber-theme.php
**Ticket**: #2359 
There's `Timber::get_post_by`, `Timber::get_user_by` ... — let's wrap it up with `get_term_by`
Copy the pattern from other get_x_by and apply it!
More poly-morphizing
@acobster suggested in the write-up that we can improve upon WP functionality by better processing the `taxonomy` value. I agree. Even when writing the tests I was thrown off by its requirement even when there's only one term with a certain name.
Wrote a new test `testTermBy`
=> Introduce Timber::get_term_by() method

docs/v2/guides/context.md, docs/v2/upgrade-guides/2.0.md, lib/Timber.php, tests/test-timber-context.php
Default `Timber::context()` behavior has some nice handling for singular/archive templates, but I'd expect it would handle other common scenarios, such as search and term pages as well.
Handle `is_category()`, `is_tag()`, `is_tax()`, and `is_search()`.
`$context['posts']` is now set in all cases listed above. For term archives, `$context['term']` also gets set.
No API changes; fewer instances where you need to set `posts`/`term` explicitly.
Are there more scenarios we want to cover?
Yes.
=> Handle search, tax queries in ::context()

.gitignore, lib/Image.php, tests/test-timber-theme.php
**Ticket**: # 
Load image dimensions also for SVG files.
Modify `Timber\Image\get_dimensions()` function and add new private function `svgs_get_dimensions()` to retrieve dimensions. from svg file.
Shouldn't touch performance or backward compatibility, just a new feature.
No usage changes accept that getting image.width and image.height will work for SVGs without a need to write own wrapper for it (thanks to @palmiak for helping hand!).
I'm not sure how to run your test suite :( but if you'll point me the right way, I could write one.
Otherwise:
* all tests related to getting png/jpg width & height should pass
* test the same with an SVG with height and width parameters only
* test the same with an SVG with view box parameter only
=> Get dimensions also for SVG images

.travis.yml
There is no default `after_success:` action.
=> Remove stray line from CI

composer.json, phpstan.neon
The thing is there are critical errors in the 2.x branch.
e.g.
#2433 and
```
------ -------------------------------------------------------------------------------------
Line   Integrations/CoAuthorsPlusUser.php
------ -------------------------------------------------------------------------------------
49     Access to an undefined property Timber\Integrations\CoAuthorsPlusUser::$user_email.
------ -------------------------------------------------------------------------------------
------ -----------------------------------------------------------------
Line   Menu.php
------ -----------------------------------------------------------------
115    Constructor of class Timber\Menu has an unused parameter $slug.
------ -----------------------------------------------------------------
```
=> Update PHPStan configuration

lib/Post.php
**Ticket**: #2433
This method was supposed to be removed in THE PURGE.
🔪 
💀 
None.
Are there more? I did a quick sweep of the `Post` class and didn't find any (other than some minor formatting I tweaked here).
No tests needed since this is dead code. This should actually increase coverage.
=> Remove unused method Post::check_post_id()

docs/v2/guides/context.md, docs/v2/guides/cookbook-images.md, docs/v2/guides/gutenberg.md, docs/v2/guides/pagination.md, docs/v2/guides/performance.md, docs/v2/guides/sidebars.md, docs/v2/guides/wp-integration.md, docs/v2/integrations/advanced-custom-fields.md, docs/v2/upgrade-guides/2.0.md, lib/Helper.php, lib/Image.php, lib/Site.php, lib/Theme.php, lib/Timber.php
**Ticket**: #2368
Now that we can pass an array directly to `Timber::context()`, it’s probably worth updating the documentation to the new format in a couple of cases.
Update documentation.
I think it’s actually more readable in a couple of places.
None.
I doesn’t make sense to change the format everywhere, especially if there is advanced logic involved.
None.
=> #2368 – Update context format in documentation

lib/Factory/MenuItemFactory.php, lib/MenuItem.php, tests/test-timber-menu.php
**Ticket**: None
This addresses a couple issues:
1. MenuItemFactory::build() is less specific than it could be, causing PHPStan to complain.
2. MenuItem constructor is still public, allowing for direct instantiation which would forgo Class Maps.
None.
Consistent with the rest of the Factory usage.
There are other Factories whose return values from `::build()` could also be more specific. These are out of scope here.
Existing tests cover this functionality and are currently passing for me.
=> Fix MenuItem creation

lib/Factory/PostFactory.php, lib/Image.php, tests/test-timber-image.php
Fixes behavior and test failures with SVG dimension loading in 2.x.
After merging in #2421, I inadvertently created a behavior conflict w how factories detect whether an image is an image (and whether an SVG counts as one). This manually moves some code from 1.x and adds a small modification to `Factory/PostFactory` to resolve this change.
As @gchtr notes, there could be a performance opportunity with `wp_check_filetype` to cache the results so we don't have to hit that function again and again
=> Add patch for SVG dimensions

docs/v2/upgrade-guides/2.0.md, lib/URLHelper.php, tests/test-timber-url-helper.php
PHPStan considers implicit null returns a bug:
```
------ ---------------------------------------------------------------------------------------------------                                                                                                        
Line   URLHelper.php                                                                                                                                                                                             
------ ---------------------------------------------------------------------------------------------------                                                                                                        
533    Method Timber\URLHelper::get_params() should return array|string but return statement is missing. …
```
=> URLHelper::get_params() return value

lib/Image.php, readme.txt, tests/test-timber-multisite.php
**Ticket**: #1312 
`Timber/Image::wp_upload_dir()` caches the result of `wp_upload_dir()`. This causes problems when `switch_to_blog()` is used.
Add a check whether we are in a multisite and whether we are in a switched site context. In that case, never return a cached result.
None.
None.
We could think about whether the result should be cached at all or if we always should use a plain `wp_upload_dir()` call, because of all the side effects that might be involved.
To miminize performance impacts, we could think about passing the second `$create_dir` parameter as `false`, which would skip the checks whether the correct folder already exists. Of course we would have to check whether the check is already made by other functions earlier.
To actually remove the `Timber/Image::wp_upload_dir()` …
=> Fix bug when using switch_to_blog() in combination with Timber images

lib/Post.php, readme.txt
The returned value of the `Post::thumbnail()` method is considered to be `\Timber\Timber\Image` as we already are in the `Timber` namespace and `Timber\Image` is missing a leading `\`. This is making tools such as PHPStan to fail.
The solution is to use the same type as the `Post::get_thumbnail()` method, which is directly using the `Image` class from the current namespace.
It will improve compatibility with static analysis tools such as PHPStan.
Nothing to update (I think).
=> Fix the `thumbnail()` method return type

docs/v2/guides/routing.md, docs/v2/upgrade-guides/2.0.md
**Ticket**: #2446, https://github.com/Upstatement/routes/issues/29
It might not have been clear enough that we can still use the routing Timber always had with Timber v2.
Improve documentation.
– 
None.
None?
Nope, just docs.
=> 2.x Improve routing docs

docs/v2/upgrade-guides/2.0.md
When installing and trying out Timber v2, you might have to use checks for a specific Timber version if you still want to support both versions.
Add a hint in the Upgrade Guide.
None.
None.
None.
No. just docs.
=> 2.x Add hint about checking for Timber’s version

docs/v2/guides/terms.md, docs/v2/upgrade-guides/2.0.md, lib/Timber.php
**Ticket**: #1617
There were still some todos for terms, and also some issues.
- Add changes for terms to the Upgrade Guide.
- Fix some issues that we forgot or changed in the meantime.
None.
None.
1. In the documentation for [Querying Terms](https://timber.github.io/docs/v2/guides/terms/#querying-terms), I once wrote that there will be `TermCollections` that work similar to `PostCollections`. I guess I’ll have to remove that part, because we don’t have term collections yet?
2. In the same section, I wrote "If you don’t pass in any argument, Timber will use the global query.". Currently, that’s not what we do. Instead, we get terms from all all queryable taxonomies. So, we could probably do something similar to what we already do in …
=> 2.x Improve documentation for terms

tests/test-timber-multisite.php
**Ticket**: #1617
A new test with #2478 causes issues in 2.x because Image::wp_upload_dir() is removed.
Test against the generated URL rather than what's stored in this (no longer existent) variable
Just a change to a test, no functional code. I don't think the test covers anything "real" at this point since that var isn't being cached; but didn't want to toss the test just in case.
None
As I type this, I realize I should confirm against resizing too
=> Fix a test failing with 2.x + Multisite

lib/Timber.php, tests/test-timber-context.php
**Ticket**: #2470
When no `page_on_front` is set, Timber tries to run `setup()` on a post that doesn’t exist, which leads to errors.
Check for a post before running setup.
Fixes a bug.
None.
I thought about whether I should add different checks there, like using `get_option('page_on_front')` or using [@nlemoine’s suggestion](https://github.com/timber/timber/issues/2470#issuecomment-911970671). But then I thought: why think about all the various cases we could run into if Timber already provides an easy way to check whether there’s a post – by using `Timber::get_post()` itself.
Yes.
=> 2.x Fix bug when page_on_front is not set in some cases

lib/Integrations/ACF.php
Just a tiny fix, internally, use Timber fully qualified namespace.
=> Use Timber full path

lib/Image/Operation/Letterbox.php
**Ticket**: None
The letterbox class does not support webp images.
Add support for webp images
The 'imagewebp' & 'imagecreatefromwebp' functions were added in PHP 5.4. The Timber Wordpress page reports a minimum PHP version of 5.6, however, the current composer.json shows 5.3. I'm not sure if the composer.json is out of date or not.
There should be none
See Impact
There doesn't seem to be specific tests for the different extensions.
=> Add webp support to letterbox filter

.github/workflows/test.yml, tests/test-timber-widgets.php
Tests are broken, because of an error with PHP 8.1 in **wp-includes/block-supports/layout.php**. Here’s the relevant trac ticket: https://core.trac.wordpress.org/ticket/55119. The recommendation is to not use PHP 8.1 yet:
> WordPress core is not fully compatible with PHP 8.1 yet, there are still some deprecation notices. If you need a workaround, I would suggest switching to PHP 8.0 for now.
Disable testing against PHP 8.1 when [WordPress doesn’t officially support it yet](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) and let’s see if something else is broken, too.
=> 2.x Fix tests

.github/workflows/test.yml
**Ticket**: #2562 
There appears to be an unrelated failure occurring due to `trunk` changes in WP on #2562. This begs the question — why test against trunk at all?
Swap `trunk` for `latest`
We'll be a bit behind should a breaking change come in WP's functions (whereas before we could have caught it before formal release). However, 
None
Should we maybe keep one trunk test in the matrix and allow failures?
=> Test against Latest WP Version instead of Trunk

composer.json
**Ticket**: #2543
- We should probably allow both version for `composer/installers` as also suggested in https://github.com/timber/timber/pull/2543 and https://github.com/timber/timber/pull/2546#pullrequestreview-894393017.
- We’re using an old pipe format for Composer versions.
- Allow both versions `^1.0` and `^2.0` for `composer/installers`.
- Use modern pipe format using ` || ` instead of `|`. See https://getcomposer.org/doc/articles/versions.md#version-range for more information.
Better compatibility in various environments.
None.
No.
No.
=> Improve composer version ranges

composer.json, docs/v2/guides/performance.md, docs/v2/upgrade-guides/2.0.md, lib/Cache/KeyGenerator.php, lib/Cache/WPObjectCacheAdapter.php, lib/Loader.php, tests/test-timber-cache-extra.php, tests/test-timber-cache.php
**Ticket**: #2407
Following the discussions in #2486, I think I may have a solution for replacing the `twig/cache-extension` package.
This pull request:
- Removes the `twig/cache-extension` package.
- Removes all interfaces that it provided, but keeps the classes that used them.
- Adds the `twig/cache-extra` in composer.json’s `suggest` field.
- Adds tests to test the support for the `twig/cache-extra` package.
- Updates Timber’s Cache Key Generator to not use any of the characters that are forbidden to use as cache keys with the `twig/cache-extra` package.
- Adds documentation about using the `twig/cache-extra` package.
- Adds the relevant information in the Upgrade Guide.
- Breaks compatibility for people who use the `{% cache %}` tag in Twig.
The `{% cache %}` works a little different. …
=> 2.x Remove twig/cache-extension, add support for twig/cache-extra

lib/Post.php
**Ticket**: #2501
Timber was overwriting the post global with a Timber post object.
- Overwrite the post global with a WordPress post object.
- Overwrite the post global only if necessary.
Fixes unexpected behavior.
None.
See #2501.
No.
=> 2.x Don’t overwrite post global

tests/test-comment-factory.php, tests/test-post-factory.php, tests/test-term-factory.php, tests/test-user-factory.php
**Ticket**: #2572
#2572
Update the tests where class maps are tested.
Found an instance in the user class maps where a wrong class was returned because the CoAuthors Plus Integrations adds a filter that is also applied in the user tests:
https://github.com/timber/timber/blob/69aebbf42b9df6661129a6d92f6290691aa58529/lib/Integration/CoAuthorsPlusIntegration.php#L22-L24
None.
None.
Yes.
=> 2.x Use assertTrue() and get_class() instead of assertInstanceOf() in certain tests

docs/v2/guides/twig.md, docs/v2/upgrade-guides/2.0.md
**Ticket**: #2482
We should mention that Twig also has some deprecations.
I didn’t mention all the relevant deprecations, like the filter or the spaceless tag. Let’s see what issues come by people who find it hard to find a solution.
=> 2.x Update Upgrade Guide with Twig deprecations

composer.json
**Ticket**: #2584 
Changes in WP 6.0 broke how the underlying Routes library handled requests
Deploy the fix from that library! https://github.com/Upstatement/routes/pull/41
Compatible w/ both WordPress 5.* and WordPress 6.0
None
=> Use newest version of Upstatement/routes

docs/v2/upgrade-guides/2.0.md, src/PostQuery.php, tests/test-timber-post-collection.php
**Ticket**:
- Fixes #2605.
The [`get_query()` method](https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/PostQuery.php#L50-L56) didn’t make it over to 2.x.
This pull request:
- Adds the missing method and renames from `get_query()` to `query()` to match the naming convention.
- Deprecates the `get_query()` method.
- Adds a test.
- Updates the Upgrade Guide.
Mentioned in the Upgrade Guide.
–
Yes.
=> 2.x Add missing query() method to `Timber\PostQuery`

docs/v2/upgrade-guides/2.0.md, src/Attachment.php, tests/test-timber-attachment.php
**Ticket**: #2610
- Fixes #2607
This pull request iterates on the work by @xavivars in #2610 (thanks, @xavivars). For 2.x, we missed that the caption of an attachment is set while initializing it. See this excerpt from 1.x:
https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/Image.php#L215-L217
This pull request:
- Adds a test to confirm the bug in #2607.
- Removes the `Attachment::$caption` property and instead adds an `Attachment::caption()` method. I think this is the approach we choose more and more: Using methods instead of countless properties we have to initialize.
- Updates the Upgrade guide.
- Adds the `wp_get_attachment_caption` filter, which is used in the equivalent WordPress core function …
=> 2.x Remove `Attachment::$caption` property in favor of `Attachment::caption()` method

src/User.php, tests/test-timber-user.php
**Ticket**: #2532 
fixes issue where `{{user.can('capability', arg)}}` doesn't work because arg is not passed to user_can
Spreads arguments from `\Timber\User::can` to `user_can` function 
No backward compatibility breaking changes (besides fixing the issue at hand)
The following now work:
```twig
{% if user.can('edit_post', post.id) %}
{# do something with privileges #}
{% endif %}
```
```twig
{% if user.can('edit_term', term.id) %}
{# do something with privileges #}
{% endif %}
```
```twig
{% if user.can('edit_user', user.id) %}
{# do something with privileges #}
{% endif %}
```
```twig
{% if user.can('edit_comment', comment.id) %}
{# do something with privileges #}
{% endif %}
```
The way timber 2.x tends to use this now is with `\Timber\Core::can_edit` …
=> 2.x user can args

.github/workflows/test.yml, bin/deploy-to-wp-org.sh, bin/timber.php, composer.json, readme.txt, tests/assets/test-shortcodes.twig, tests/test-timber-loader.php
Resolves:
- #2654
- #2655
- #2652
- #2661 
When the plugin version 1.21.0 of Timber was released, we accidentally included Twig 2.15.3 instead of Twig 1.44.7. This caused a lot of bugs for sites that auto-updated the Timber plugin (not recommended). We deactivated the 1.21.0 as the default release to disable that version from being found by auto-updates.
As a solution, this pull request makes sure that Twig version 1.44.7 is used when deploying the plugin version of Timber. When Timber is installed through Composer, the 2.x will still be installed.
We also added a new test configuration that tests PHP 8.0 and PHP 8.1 with version 1.44.7 of Twig by using `prefer-lowest` when installing Composer dependencies (thanks @nlemoine).
Unfortunately, I didn’t manage to get this fully working with …
=> Fix bugs with latest plugin release 1.21.0

src/Timber.php, tests/test-timber.php
Resolves:
- #2509
`Timber::render()` and `Timber::compile()` allow full file paths. This isn’t mentioned in the DocBlock.
Improves the description for the `$filenames` parameters and add a quick test.
None.
None.
None.
Yes.
=> 2.x Update descriptions for compile and render methods

composer.json, readme.txt
**Ticket**: https://github.com/timber/timber/issues/2672
There was an error with versioning in the composer.json file allowing Twig 3.4.3 to be installed. This introduces breaking changes like a missing `filter` tag.
Make version selector more strict.
This pull request fixes the errors that people are seeing in https://github.com/timber/timber/issues/2672 because we will revert to Twig 1.44.7 or 2.15.3.
None.
This is a small hotfix and might be considered version 1.22.1?
Yes.
=> Ensure Twig 3.x is not installed

src/Post.php, tests/test-timber-post-content.php
Resolves:
- #2589
When the nextpage block was used, Timber doesn’t correctly split the content. The block on the second and subsequent pages are not properly converted, because there’s a stray `` block closer when we explode only on ``.
A nextpage block looks like this:
```html
```
Take nextpage logic from WordPress to make it work with `` only as well as nextpage blocks.
Should be backwards compatible.
None.
WordPress ignores `` if it’s at the beginning of a block. I added a test for this behavior as well.
Yes.
=> 2.x Fix bug with nextpage block

docs/v2/guides/users.md, docs/v2/upgrade-guides/2.0.md, src/User.php, tests/test-timber-user.php
Setting public properties for user meta fields results in `{{ user.first_name }}` to return null. Because those properties are not `WP_User` properties and thus not imported.
Since those properties are declared, Twig will not retrieve them either: https://twig.symfony.com/doc/3.x/templates.html#variables
Remove public properties matching user meta so `__call` in `Timber\Core` is actually called.
None.
You can now do `{{ user.first_name }}`, `{{ user.last_name }}`, etc.
Just changed the test with description to ensure this works fine.
=> Fix User entity

docs/v2/upgrade-guides/2.0.md, src/Attachment.php, src/CoreEntity.php, src/ExternalImage.php, src/FileSize.php, src/Helper.php, src/Image.php, src/ImageDimensions.php, src/ImageInterface.php, src/Loader.php, src/Timber.php, src/URLHelper.php, tests/test-image-dimensions.php, tests/test-timber-helper.php, tests/test-timber-image-helper.php, tests/test-timber-image.php, tests/test-timber-integration-wpml.php, tests/test-timber-twig.php
**Ticket**: #2627 
Adding a `Timber\ExternalImage` class, compatible with `Timber\Image` when using it in Twig, to get feature parity with Timber 1.x
A new class, `Timber\ExternalImage`, that implements `Timber\ImageInterface`, compatible with `Timber\Image`
There is some common logic that has been extracted from both `Timber\Image` and `Timber\Attachment` into their own classes, to avoid code duplication and being able to use it from `Timber\ExternalImage`.
Not yet.
=> External image (Fixes #2627)

src/Request.php
While working on fixing some PHPStan issues, I found that the `Timber\Request` class extends `Timber\Core` and implements `Timber\CoreInterface`.
In the current state of Timber, I don’t see any reason why it should do so. Even when it was introduced in #853, it wasn’t clearly stated why it should extend `Timber\Core`.
The method required by `Timber\CoreInterface` are added as empty functions and they look like they were added only to serve the interface. But this request helper class doesn’t have anything to do with a Timber core object that usually matches core functionality in WordPress.
Make `Timber\Request` not implement `Timber\CoreInterface`.
This might break backwards compatibility with any class that extends `Timber\Request`. We will have to add a note to the Upgrade Guide.
None. …
=> 2.x Make Timber\Request not implement Timber\CoreInterface

docs/v2/upgrade-guides/2.0.md, src/Comment.php, src/Core.php, src/CoreEntityInterface.php, src/Menu.php, src/MenuItem.php, src/Post.php, src/Term.php, src/User.php, tests/test-timber-comment.php, tests/test-timber-menu.php, tests/test-timber-post.php, tests/test-timber-term.php, tests/test-timber-user.php
Resolves:
- #2645
When using `{{ term.can_edit }}`, Timber should use the correct permission check for a term. The same goes for other core objects like comment and users.
This pull request
- Moves `can_edit()` to the specific Timber object classes.
- Adds `can_edit()` to the `CoreEntity` interface.
- Adds new `edit_link()` functions to `Comment` and `User` class.
Accurate capability checks.
None.
Checking the permissions on the `Menu` and `MenuItem` feels a bit weird first. They can’t be edited through the usual edit screens and need a check for the `edit_theme_options` capability. The question now is: Does it make sense to have the `can_edit()` check for the menu and menu items? Otherwise, we would have to remove the interface.
By adding `User::edit_link()`, it’s possible to get the …
=> 2.x Fix can_edit() permission checks for Term, User, Comment and Menu classes

bin/install-wp-tests.sh, tests/Timber_UnitTestCase.php, tests/assets/themes/timber-test-theme-child/style.css, tests/assets/themes/timber-test-theme-child/views/single.twig, tests/assets/themes/timber-test-theme/style.css, tests/assets/themes/timber-test-theme/views/single-course.twig, tests/assets/themes/timber-test-theme/views/single-parent.twig, tests/assets/themes/timber-test-theme/views/single.twig, tests/test-external-image.php, tests/test-timber-loader.php, tests/test-timber-parent-child.php, tests/test-timber-site.php, tests/test-timber-theme.php, tests/test-timber-widgets.php
**Ticket**: #2695
Uuugh, it took me so long to figure out why tests were sometimes working and sometimes not (in #2695), depending on whether it’s a fresh test installation or not or running singular tests.
The issue that arises is when other tests install a theme or switch to a theme while other tests use the default theme as a baseline.
This pull request should solve a lot of testing side-effects by 
- preparing a Timber test theme as well as a child theme that should be used for all tests
- installs these themes while bootstrapping the tests instead of installing various themes during the tests
- switches back to the `default` theme after tests
Less side effects.
We should use the `timber-test-theme` and the `timber-test-theme-child` to run tests instead of various `twentyxx` themes …
=> 2.x Fix side effects with tests involving themes

src/Core.php, src/PostType.php, tests/test-timber-integration-acf.php, tests/test-timber-site.php
Dynamic (non-explicitly declared) properties are deprecated as of PHP 8.2 and are expected to become a fatal error in PHP 9.0.
As you may have noticed in the CI logs, this generates a lot of noise both in error logs and test run logs.
To reduce noise this pull request adds the `#[AllowDynamicProperties]` attribute to the [`Core`](src/Core.php) class.
Ideally, a magic `__set()` method should be added which will require adding a catch-all data property to store the non-declared fields.
```php
/**
* Store dynamic meta fields.
*
* @var array<string, mixed>
*/
private $fields = [];
/**
* Magic setter for dynamic meta fields, for convenience in Twig views.
*
* This method is not meant to be called directly.
*
* @example
* ```php
* $post = Timber\Post::get( get_the_ID() );
*
* …
=> 2.x Add `AllowDynamicProperties` attribute

src/Menu.php, tests/test-timber-menu.php
With Timber v2 , WPML, and PHP 8, if any nav menu location happens to be `null`, this warning occurs:
```
Warning: array_flip(): Can only flip string and integer values, entry skipped in vendor/timber/timber/src/Menu.php on line 255
```
This is similar to issue #2576 where the warning was with `MenuFactory::get_menu_location()`.
The solution is to apply the [same fix made to `MenuFactory`](https://github.com/timber/timber/commit/e4228795cf41a0e1d0c870fd70a9b969f2b44906); filter the nav menu locations array to enforce strings or integers.
The `TestTimberMenu::testThemeLocationProperty()` method was updated to match `TestMenuFactory::testGetMenuLocation()`.
=> 2.x Fix Menu theme locations array to enforce string or integers

.github/PULL_REQUEST_TEMPLATE.md
Let’s update the GitHub pull request template and use a notation for related tickets. This will automatically enhance the tickets with the proper ticket / pull request titles and the status of the related tickets. This that can be seen in the following screenshot:
=> Improve GitHub pull request template

src/Factory/PostFactory.php, src/Timber.php
The `timber/post/import_data` filter was running on every `Timber::get_post()` (😱😱😱) which can be used to get related posts, post metas, etc.
Ensure that the preview ID is matching the current post ID.
None.
None.
None.
Not yet.
=> Fix post preview

src/Integration/WpmlIntegration.php, src/Menu.php, tests/test-timber-menu.php
WPML uses a custom nav menu item class: `WPML_LS_Menu_Item`.
When this menu item is passed to `MenuItemFactory::from()`, the method ignores it and returns `null` which violates the return type of the array map closure in `Menu::convert_menu_items()` leading to a fatal error:
```
PHP Fatal error:  Uncaught TypeError: Timber\Menu::Timber\{closure}(): Return value must be of type Timber\MenuItem, null returned in vendor/timber/timber/src/Menu.php:289
Stack trace:
#0 [internal function]: Timber\Menu->Timber\{closure}(Object(WPML_LS_Menu_Item))
#1 vendor/timber/timber/src/Menu.php(288): array_map(Object(Closure), Array)
#2 vendor/timber/timber/src/Menu.php(213): Timber\Menu->convert_menu_items(Array)
#3 vendor/timber/timber/src/Factory/MenuFactory.php(276): Timber\Menu::build(Object(WP_Term), …
```
=> 2.x Fix menu item compatibility with WPML

docs/v2/guides/custom-fields.md, src/Post.php, src/Timber.php, tests/test-timber.php
Related:
- #2714
The `numberposts` parameter is only supported when using `get_posts()`, but not when using `Timber::get_posts()`.
Add a doing-it-wrong notice.
Better guidance for developers migrating to v2.
Use `posts_per_page` instead.
Can be removed in the next major Timber version.
Yes.
=> 2.x Add doing_it_wrong not for `numberposts` in Timber::get_posts()

src/Factory/CommentFactory.php, src/Factory/PostFactory.php, src/Factory/TermFactory.php, src/Factory/UserFactory.php, src/Timber.php
`Iterable` with capital `i` might let you think that it's a native class whereas it's a pseudo type
Not really an issue but I think iterable return types might lead to confusion. Proof is one them was backslashed in a PHPDoc block.
Lower case all of them. 
None.
None.
Using iterables on every `get_{objects}` (terms, users, comments) is bit annoying. While it's legitimate on `posts` because we return true collection objects, all the other ones just return simple arrays.
But since the return type is `iterable`:
- you're discouraged to use `array_*` functions (outside of Twig) which are often very useful (map, filter, etc.), although it will work in the current implementation for users, terms and comments
- when using `array_*` functions, my IDE (and PHPStan) complaints about it ("Expected …
=> Fix iterable case

docs/v2/guides/custom-fields.md, docs/v2/guides/custom-integrations.md, src/Post.php, src/Timber.php, tests/test-timber.php
- Register admin notice on `admin_init` action
- Remove `pre_get_posts` filters, I never paid attention to those filters but I don't think this should be Timber's responsability to provide some kind of query arguments normalization. 
- Filters integrations to ensure they implement `IntegrationInterface`
- Removes `test_compatibility()` which actually does nothing
Moving from closures to static functions (not ideal but better) provides a better way to remove those filters if needed.
None.
=> 2.x clean init

composer.json, docs/v2/upgrade-guides/2.0.md, src/ImageHelper.php, src/Post.php, src/TextHelper.php, tests/test-timber-text-helper.php
This is handled by PHP 8 and can easily be polyfilled. 
Timber is full of helpers that already exists either in WordPress or PHP (and can easily be polyfilled).
=> Remove string helpers

docs/v2/upgrade-guides/2.0.md
Reviewer may want to change "Setup Guide" to "Installation Guide" or "Installation Page" or something else if it's more accurate.
Link to Setup Guide in Upgrading to 2.0 docs 404s.
Inferred that this should probably be the Installation docs.
Fix regression, no other impact.
A CI step could be added which checks for broken links in markdown documents.
=> Update 2.0.md - fix 404 link to setup guide

.github/workflows/links.yml
Related:
- https://github.com/timber/timber/pull/2732
It may be hard to keep all links in docs up to date. 
As suggested in PR above, setup a workflow to spot them.
It will check every week docs links and create an issue if bad links are found.
=> Add workflow to check docs links

docs/v1/getting-started/theming.md, docs/v1/guides/cookbook-images.md, docs/v1/guides/custom-page-templates.md, docs/v1/guides/internationalization.md, docs/v2/getting-started/a-post-archive.md, docs/v2/getting-started/a-single-post.md, docs/v2/guides/cookbook-images.md, docs/v2/guides/custom-fields.md, docs/v2/guides/custom-page-templates.md, docs/v2/guides/internationalization.md, docs/v2/guides/menus.md, docs/v2/guides/performance.md, docs/v2/guides/posts.md, docs/v2/upgrade-guides/2.0.md
Ticket: #2742
Link checker action found 22 broken links in the documentation.
- Updated internal links: https://github.com/timber/timber/commit/5b8292c6d59933bb2b4ca05801dba765151875e6
- Updated 2.0 guide: https://github.com/timber/timber/commit/ff6d96772266b60c0bae354293afb0d4bf2f5647
- Added alternative for cdn guide: https://github.com/timber/timber/commit/ed2abaf81c9c2d99648b8a8afc7a2ac2dd6822d3 and https://github.com/timber/timber/commit/23bbe8a87c4b307c1b58198a28e69e16efe7a3f1
- Removed Gulp guide from translation since it is not available anymore: https://github.com/timber/timber/commit/4c808469b16cc9bcd568efeec07d418122b9502e
- Updated template hierarchy section with some explanation and an alternative link : https://github.com/timber/timber/commit/225fb104c4f5a65d1d64d5ddf4dff9c12 …
=> Update broken links in documentation

src/Factory/PostFactory.php
Related:
- #2444
Images with query params are not correctly identified as images.
The current way to detect an image is to use `wp_attachment_is_image` and use that with `wp_check_filetype` to detect if the file has an expected extension.
However, `wp_check_filetype` is not meant to be used with an URL but with a path instead. So this check fails currently if the URL has query params for example.
The fix is to use `get_attached_file` to get the actual file path instead of the URL matching what `wp_attachment_is_image` is doing.
I don't think there are any performance or BC changes since this is a bug fix IMHO.
No.
Ideally `wp_attachment_is_image` would been used, but seeing there are custom filters in place this is (no longer) a viable solution so mimicking what `wp_attachment_is_image` …
=> Fix `PostFactory::is_image` incorrectly using `wp_check_filetype`

src/Helper.php
- https://github.com/timber/timber/issues/2745
Helper.php class is not in the current V2 docs. This seems to be caused by the missing @api tag. This also causes one of the missing links in #2745 
Add the @api tag and deploy the new docs.
More docs!
=> Add @api tag to Helper

lib/Helper.php
due to reported (issue)[https://github.com/timber/timber/issues/2706]
(issue)[https://github.com/timber/timber/issues/2706]
Looks like a typo in PHPDoc
mix -> mixed
Warning:(154, 54) Expected parameter of type 'Timber\mix', 'array|WP_Post' provided
mix => mixed
almost zero
=> Fix PHPDoc typo

src/Theme.php
Related:
- #1313
When looking through the old issues, I found this issue which I ran into a long time ago as well. So I tried to clear up the docblocks.
The changes on rule 75 and 137 are leading in this PR. The now reflect more what to expect of the property/method.
Other changes while at it:
- The changes to rule 69, 94, 116 are to give a consistent example of theme slugs. 
- 113 fixes a typo.
- 146 removes a double space and adds a capital letter.
Hopefully a better overall understanding of the Theme class.
=> Update property and method docblocks in Theme.php.

src/Term.php
Related:
- https://github.com/timber/timber/pull/2668#pullrequestreview-1435474737
There is an unused property in `Timber\Term::build()`. The `$_options` parameter was introduced in https://github.com/timber/timber/commit/21445a1f5b50606fb3f8789c981f698a0437b2b9, where it was still needed. At that time, `Timber\Menu` still extended `Timber\Term`. So `Timber\Term::build()` had to use that optional parameter to be compatible.
Now, `Timber\Term` only extends `Timber\CoreEntity`. 
We can safely remove that unused parameter.
None.
None.
None.
None needed.
=> 2.x Remove unused param from `Timber\Term::build()`

tests/test-timber-meta.php, tests/test-timber-post.php
While testing a new way to run tests, I stumbled upon this.
ACF functions shouldn't be used outside ACF integration tests.
Use `update_post_meta`.
None
=> Fix custom field test

docs/v2/guides/date-time.md, src/DateTimeHelper.php, src/Post.php, tests/test-timber-dates.php
Related:
- #2737
The `|time_ago` filter doesn’t work correctly when timezone is set to Australia.
- Don’t use `strtotime()`, but create DateTime objects with their corresponding timezone.
- Update some documentation entries for correct usage with `{{ post.date }}`. It’s important to use a time string including the time.
The `|time_ago` filter should work more reliably.
None.
None.
Yes.
=> 2.x Fix a bug when `|time_ago` didn’t consider timezones correctly

.github/workflows/test.yml
Tests don’t run after automatic update to MariaDB v11.
As a first measure: downgrade to MariaDB v10.
Then, we can start to find out what went wrong. I read the Upgrade Guide for the 11 release (https://mariadb.com/kb/en/upgrading-from-mariadb-10-11-to-mariadb-11-0/), but I don’t know MariaDB or MySQL well enough to see what we would need to change.
@nlemoine Do you know what to do here?
Fixes automatic tests.
None.
None.
=> 2.x Fix MariaDB in automatic tests

src/Post.php, src/Theme.php
Some tiny improvements to make PHPStan happy.
=> fix: phpstan issues & use fully qualified imports

README.md
See https://github.com/timber/timber/tree/readme-funding.
=> Add sponsorship information to Readme

docs/v2/installation/installation.md
Related:
- #2741
When we mention how to [install Timber in the documentation](https://timber.github.io/docs/v2/installation/#install-timber-into-an-existing-project), it might not be clear how to install the release candidate.
Add a section about the release candidate that we can later remove again.
Less confusion.
None.
None.
No.
=> 2.x Add note about installing the release candidate

docs/v2/guides/extending-twig.md
Typo in the [Changing functions](https://timber.github.io/docs/v2/guides/extending-twig/#changing-functions) section of Extending Twig docs. References `$filters` instead of `$functions`
=> Typo: Changing functions section references $filters instead of $functions

.github/ISSUE_TEMPLATE/bug_report.yml
Related:
- #2741
Add a note about Timber 1.x being dropped so:
- we can inform and encourage users to move to Timber 2
- issues about Timber 1.x stop being added whereas they won't be adressed
=> doc: Add drop support notice to issue template

docs/v2/guides/cheatsheet.md
Related:
- #1313
In #2744 we updated the docblocks regarding these theme helpers, but the docs where still somewhat vague.
Updated the cheatsheet in v2 as well with the same hints.
Better understanding of the theme uri/path/link helpers straight from the docs.
none
none
no
=> docs(cheatcheat): Explained theme path, link and uri helpers.

docs/v2/upgrade-guides/2.0.md
Related:
- https://github.com/timber/timber/pull/2800
In the v2 guide there is no link/information about how to switch from the plugin version to the Composer-based installation.
After we merged #2800 and deployed the new docs we can merge this PR to refer in the 2.0 guide to the _Switch from the plugin to Composer_ guide.
Better information when you end up directly in the 2.0 upgrade guide.
no.
Cross-reference this 2.0 guide as the next step in the guide created in #2800? 
no.
=> docs: updated plugin support part

src/Attachment.php
Related:
- #2819 
The doc block was wrong here.
=> fix: Attachment size doc block

.github/ISSUE_TEMPLATE/bug_report.yml
URL to the switch to composer guide is pointing to the wrong place in the bugreport template. Let's fix that!
We must merge this in master and v2.
=> Workflow: fix path to guide

.editorconfig, .github/actions/setup/action.yml, .github/dependabot.yml, .github/workflows/composer-lint.yml, .github/workflows/links-check.yml, .github/workflows/php-coding-standards.yml, .github/workflows/php-lint.yml, .github/workflows/php-static-analysis.yml, .github/workflows/php-unit-tests.yml, composer.json
- Split each job into its own file
- Filter paths so Actions runs only when necessary (no need to run composer lint when it has not been modified)
- Add cs2pr to provide PR author direct feedback
- Add dependabot for GA
- Bump easy-coding-standards to ^12
We should have much faster/accurate CI tests and cleaner UI view.
=> ci: Update GitHub Actions workflows

src/Attachment.php, src/ExternalImage.php, src/Image.php, src/ImageInterface.php, tests/test-external-image.php
Related:
- Ticket 1
- Ticket 2
=> Extimg-patch

src/ExternalImage.php, tests/test-external-image.php
Related:
- Ticket #2817
The (protected) typed properties of `ExternalImage`, `$alt_text` and `$caption`, were not initialized properly in the static `build()` method, causing errors when accessing them later (`must not be accessed before initialization`). The error only occurred in PHP >= 7.4, when this behavior (not initializing typed properties) was introduced.
The calling method (`Timber::get_external_image()`) provides empty strings as default arguments for `alt` and `caption` when calling the build() method. Also, within the build method, there was a default for at least the `alt` parameter. But as these default parameters were empty strings, they were not used to initialize the properties properly. I did two things:
1. Ensure that also `caption` has a default value (empty string) …
=> fix: initialize typed properties correctly in ExternalImage::build()

src/Factory/TermFactory.php, tests/test-term-factory.php
Related:
- Ticket #2802 
A `fields` argument other than `all`or `all_with_object_id` lead to a fatal error, as `TermFactory::from_wp_term_query()` did expect the result of a query to always be of type `WP_term[]` 
In `TermFactory::from_wp_term_query()` call `TermFactory::build()` only if `fields` is `all` or `all_with_object_id`, otherwise, return plain result of `WP_Term_Query::get_terms()` (i.e., `int[]|string[]|string`)
One could - instead of examining the `fields` argument - check if the object returned from `WP_Term_Query::get_terms()` actually is a `WP_Term[]`. That would be future proof (if there are `fields` values added for which the query also returns an array of `WP_Term`) - but might have some impact on performance, so I decided to solve it this way.
No specific
=> fix: consider 'fields' value when returning terms from query

docs/v2/upgrade-guides/2.0.md, src/Comment.php, src/ExternalImage.php, src/Menu.php, src/MenuItem.php, src/Post.php, src/Term.php, src/User.php
Related:
- #2813
- #2660
The final constructors prevent advanced use cases as described in #2813. We don’t want to make it so hard to work around it. But we first need to figure out a proper solution for this.
Revert that pull request for 2.x and figure out a better solution in a future release.
Less trouble to incorporate advanced coding patterns with Timber.
None.
None.
No.
=> 2.x Revert final constructors

phpstan.neon
PHPStan is  running on tests folder.
Exclude tests folder.
Maybe allow PHPStan on tests later.
=> fix:  exclude tests from PHPStan
