timber/timber

- functions/timber-posts-collection.php
> Fix error on string concatenation, fixes #462

- composer.json
- lib/timber-routes.php
Cleaned-up usage of PHP router which should help other projects that include Timber via composer. This will also resolve #409
> Php router alpha

- lib/timber-image-helper.php
delete_resized_files_from_url -> delete_resized_files
> FIx deleting image, wrong function name

- lib/timber-image-helper.php
> Update timber-image-helper.php  #405

- lib/timber-archives.php
- lib/timber-url-helper.php
- tests/test-timber-archives.php
Fixes issues raised by @ogrosko in #516
- More tests for diff't archive types
- Args now properly accepted
> #516 archives

- lib/timber-image-helper.php
- tests/assets/image-resize-named.twig
- tests/assets/image-thumb-named.twig
- tests/test-timber-image.php
> resize filter should understand WordPress named image sizes

- lib/timber-image.php
Little override to allow animated GIFs to still play even when using TimberImage to downsize…
> Animated GIF TimberImage override

- lib/timber-comment.php
- lib/timber-post.php
Hello ! This is my suggestion for #182 
This add an attribute to TimberComment class (an array of his sub comments).
> Add support to sub comments in TimberComment & TimberPost

- lib/timber-image-helper.php
- lib/timber-url-helper.php
My own changes to #544 in order to pass tests
> Xavierpriour master1

- lib/timber-menu.php
Now we can extend timber-menu.
> fixed property visibility in timber-menu

- lib/timber-menu.php
- lib/timber-post.php
This is for ease of access and can help with creating hierarchical structures
> Store the menu item level as a param, custom Read More labels from <!--more--> tag, support for shortcodes when get_preview uses content

- lib/timber-user.php
@jarednova requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/jarednova/timber/
> Scrutinizer Auto-Fixes

- lib/timber-post.php
- tests/test-timber-post-preview.php
- tests/test-timber-post.php
This is @newkind's commits from #570 relating to `get_preview`, `` tags and shortcodes. I'm moving it into its own PR for discussion and testing
> 570 shortcodes and moretags

- .travis.yml
- tests/test-timber-menu.php
> Update Travis to just test HHVM

- lib/timber-helper.php
…filterable in order to allow people to add custom html tags
> Allowed tags in trim_words should be filterable, added blockquote to allowed tags

- lib/timber-twig.php
> Fixes date parsing when providing timestamp

- timber.php
> Erik landvall patch 1

- lib/timber-site.php
> Rpkoller master

- timber.php
I have added short descriptions and periods at the end of comments as recommended by Core Handbook at [PHP Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/).
> Better Documentation

- bin/install-wp-tests.sh
Use `WP_VERSION=nightly` as the environment variable
Related #730
> Add support for running tests against WordPress nightly

- lib/timber-post.php
- tests/test-timber-post-preview.php
> 748 post preview tags

- lib/timber-comment.php
- lib/timber-post.php
- tests/test-timber-comment.php
- tests/test-timber-dates.php
This is a tweak to @lggorman's #758
> Lggorman time function

- lib/timber-twig.php
- tests/test-timber-twig-filters.php
No Oxford comma, a la AP style.  But could pass a param if you think it'd be worth it!
> Added list filter and corresponding test

- docs/wiki/extending-timber.md
- docs/wiki/filters.md
Modified custom filter documentation to properly reflect deprecated Twig functions.
> Expand on adding custom filters to Twig

- lib/timber-archives.php
More details [here](https://github.com/jarednova/timber/issues/812).
> Timber Archives: Resolving 'monthly-nested' issue (Tree too nested)

- lib/timber-image.php
> Jonginn feature/add id to post thumbnail

- lib/timber-helper.php
If you are using i18n, you can use this filter
> Added timber_transients_slug filter

- tests/test-timber-request.php
Added test for `request.get` as the `post` test won't cover issues with the `get` data.
Guess I should start contributing to tests for the PR's I do :)
> Adding request.get test

- lib/timber-post.php
- tests/test-timber-post-preview.php
Also updated tests.
Fixes #624
> Fixing get_preview inconsistencies

- lib/timber-post.php
Sorry, I forgot to update the comments!
> Updating comments for get_preview (ref #858)

- lib/timber-image-helper.php
Finished off #804 - just adds comments in docblock
> Updating docblock for TimberImage(url)|resize(0, 50)

- lib/timber-post.php
> ref #879 -- change to code based on suggestion from @connorjburton

- index.html
Matches the previous examples to be in a syntax highlighter block
> Fix formatting of final example in Getting Started: Themeing

- .github/PR_TEMPLATE.md
Open for modifications/discussion. Took most of this from https://gist.github.com/bernii/6c362f4e8d68e7d816f0
> Adding pr template

- CONTRIBUTING.md
- README.md
- docs/wiki/getting-started-setup.md
- docs/wiki/tests.md
- docs/wiki/video-tutorials.md
- lib/timber-admin.php
- lib/timber-image-helper.php
- lib/timber-image.php
- lib/timber.php
- readme.txt
Updating doc links and adding Timmy reference for image manipulation. Also updated installation details.
Find + Replace
N/A
N/A
This is just a start on the docs (but essentials), more to come in different PR's.
> Cjb docs updates

- bin/timber.php
- lib/Admin.php
- lib/Archives.php
- lib/Core.php
- lib/FunctionWrapper.php
- lib/Image/Operation.php
- lib/Image/Operation/Retina.php
- lib/Integrations/ACF.php
- lib/Post.php
- lib/PostsCollection.php
- lib/QueryIterator.php
- lib/Site.php
- lib/User.php
Cleaning-up spacing to match with code conventions: no changes to actual PHP
> Fixed up spacing in bin/timber.php

- tests/test-timber-post-getter.php
> 963 post getter test

- lib/Timber.php
> Migrating #947

- lib/PostGetter.php
**Ticket**: # 
Was some legacy class names left over
Fixed names
None
No change
Worked with and without fix.
Already covered
> Fixing namespace mistakes in post getter

- lib/Post.php
> Migrating #958

- lib/User.php
**Ticket**: #943 
There was no built in way to retrieve the post author's URL.
Use `get_avatar_url` to return the URL to the class property
Need to consider how this may effect comments, will this conflict? We should probably deprecate `comment.avatar` and make it an alias of `comment.author.avatar`
`user.avatar`
No tests included.
> Adding avatar to user

- lib/Admin.php
**Ticket**: #974 
**Reviewer**: @jarednova
> Fixed static/non-static declaration

- .gitignore
**Ticket**: #994 
Timber.php was ignored globally instead of just at the root level
Add a slash
None
Nope!
> ref #994 -- target Timber.php only at the root level

- .travis.yml
- lib/ImageHelper.php
- lib/Timber.php
- tests/Timber_UnitTestCase.php
**Ticket**: #989 
Hot fix for PHP 5.3 compatability
> ref #989 -- PHP 5.3 fix

- .travis.yml
**Ticket**: #998
Travis tests for testAnimatedGifResize just started failing — why?
> ref #998 -- revert to prior travis state

- lib/Timber.php
In addition to #997 - trying to fix issues.
Ref #979
> Timber load at root

- lib/Timber.php
**Ticket**: #1005 
There is no way to get the current version of Timber
Add static property with current version number
No impact
`Timber::$version`
We could use a function, but just makes more sense for it to be an attribute
Not included
> Adding version attribute

- .travis.yml
Try testing against PHP 7.....
> Test PHP 7

- lib/PostGetter.php
`PostGetter::get_pids` — did anyone ever use it? I did waaaaaay at the beginning and then kinda forgot about this method. It was never documented and is a remnant of "Jared's personal WordPress toolbelt" vs. Timber
Kill it
While it's possible that there's one person out there who used it — I doubt it. It was never documented and anyone who actually saw the code would see that it's no more efficient vs. `get_posts`
Not covered by tests either
> get pids? what was I thinking

- lib/Archives.php
- lib/Comment.php
- lib/Core.php
- lib/Helper.php
- lib/Image.php
- lib/Image/Operation/Letterbox.php
- lib/Image/Operation/Resize.php
- lib/Image/Operation/Retina.php
- lib/Image/Operation/ToJpg.php
- lib/ImageHelper.php
- lib/Integrations.php
- lib/Integrations/ACF.php
- lib/Integrations/Command.php
- lib/Integrations/Timber_WP_CLI_Command.php
- lib/Loader.php
- lib/Menu.php
- lib/MenuItem.php
- lib/Post.php
- lib/PostGetter.php
- lib/PostPreview.php
- lib/PostType.php
- lib/PostsCollection.php
- lib/QueryIterator.php
- lib/Request.php
- lib/Site.php
- lib/Term.php
- lib/Theme.php
- lib/Timber.php
- lib/Twig.php
- lib/User.php
**Ticket**: #
Lots and lots of functions had the default public visibility without defining it, it's always better to explicitly define what visibility each function has.
Adding public to functions with no visibility
Better readability
No change
Some other blanket changes such as doc blocks are a possibility
None
> Adding visibility to all functions

- composer.json
**Ticket**: #687 
The ticket explains it much better than I can.
> Removing wp cli

- lib/Post.php
- tests/test-timber-post.php
> Dknoben 836 preview page fix

- lib/Timber.php
Can you please merge and release @jarednova - just a small bug with `1.0.4`
Merci!
> Changing static call to regular call

- lib/Core.php
- lib/PostType.php
- tests/test-timber-core.php
**Ticket**: #1068 
This merges the issue and the test
> Flying dr import error php7

- lib/Loader.php
- readme.txt
> Flying dr loader locations normalization

- README.md
- bin/timber.php
- composer.json
- init.php
- lib/Timber.php
> Mrgrain fix 979 proper initalization

- lib/Loader.php
- tests/assets/output.twig
- tests/test-timber-filters.php
> Johnbillion contextual parameters

- README.md
**Ticket**: N/A
Documentation instructions weren't current
Added updated instructions for editing and publishing docs.
--
New procedure for publishing docs, as detailed in instructions.
--
--
> Added instructions for new docs

- docs/wiki/_escapers.md
this is the documentation for my escapers
> add escapers documentation

- lib/TermGetter.php
**Ticket**: #1164 
Timber\TermGetter wrong default $TermClass
`$TermClass = 'Term'` changed to `$TermClass = '\Timber\Term'`
> [BUGFIX] - #1164

- lib/Core.php
- tests/test-timber-integrations.php
> 838 meta field

- lib/Loader.php
- lib/Timber.php
- readme.txt
- tests/test-timber-comment-avatar.php
- tests/test-timber-loader.php
> removed LoaderChain stuff

- lib/Timber.php
> ref #1186 -- remove instance init calls; set init to be static

- lib/Helper.php
> Improve transient docs

- lib/Loader.php
Resolving some errors due to Twig upgrade
> Fixed error with loading absolute paths

- lib/Site.php
- tests/test-timber-site.php
> ref #1210 -- added site icon support

- bin/timber.php
- lib/Term.php
- lib/Timber.php
- tests/test-timber-term.php
> 824 term meta

- tests/test-timber-cache.php
More tests for diff't caching strategies
> 161114 tests

- lib/Loader.php
> ref #1241 -- allow for open_basedir restrictions

- lib/Pagination.php
- tests/test-timber-helper.php
- tests/test-timber-pagination.php
**Ticket**: https://github.com/timber/timber/issues/1249
Problem with pagination and usage of query vars
Take query_vars into account when deciding if pages need to be removed
Pagination
I've also removed tests I added in the past when working on some other pagination issues, as one of them is in fact doing the wrong thing.
Unit tests are included.
> Add support for public query_vars

- lib/Post.php
- lib/PostPreview.php
- lib/TextHelper.php
- tests/test-timber-post-preview-object.php
> ref #1338 -- destroy some tags

- lib/ImageHelper.php
- lib/TextHelper.php
- tests/test-timber-text-helper.php
> Digitalquery analyze url

- lib/ImageHelper.php
Should be tested against `false`, not 0
**Ticket**: # 
**Reviewer**: @
> Fixes incorrect strpos comparison

- .travis.yml
- lib/ImageHelper.php
- tests/test-timber-image-helper.php
- tests/travis.php.ini
> Gillesgoetsch master

- .travis.yml
- composer.json
- composer.lock
- phpunit-nocover.xml
Tests with PHP 7 aren't executing, they should
> Investigate Test Issues with PHP 7

- composer.json
> Upgrades to PHP and Twig

- lib/Post.php
> ref #1357 -- fixed missing $type param

- lib/CommentThread.php
- lib/Post.php
- tests/php/timber-custom-comment.php
- tests/test-timber-comment-thread.php
- tests/test-timber-post-comments.php
> ref #1363 -- make sure that $post::comments() takes custom comment class

- lib/MenuItem.php
> ref #1263 -- add default args for `nav_menu_css_class` filter

- lib/Post.php
**Ticket**: # 
Unable to get page.children, I gather the docs are supposed to say post.children
Updated page.children to post.children
> Updating docs

- README.md
**Ticket**: # 
Fix markdown heading markup.
> Fix markdown heading

- bin/deploy-to-wp-org.sh
Hello,
I suggest this little change, which has noticable performance improvement without any downsides. With that, I was able to save around 130 file_exists calls on quite small project. This is especialy helpful on Windows platforms.
More on composer optimization: https://getcomposer.org/doc/articles/autoloader-optimization.md
Thanks for great library! Jakub
> [PERF Optimization] Add optimize-autoloader to composer install

- lib/Post.php
> ref #1338 -- deprecate get_preview and destroy some tags

- lib/Site.php
> ref #1371 -- convert language_attributes to a method

- lib/ImageHelper.php
Prevents too many errors in the log for every lost file.
**Ticket**: # 
**Reviewer**: @
> Added check to see if source exists

- lib/Image/Operation/ToJpg.php
Remove hardcoded list of extensions. Added benefit (?) of supporting BMP in the future.
**Ticket**: # 
**Reviewer**: @
> Making code more readable

- lib/Menu.php
- tests/test-timber-menu.php
- tests/test-timber-wpml.php
> Mikeyb31 wpml menu theme location

- lib/FunctionWrapper.php
- lib/Timber.php
- tests/test-timber-widgets.php
> Gchtr 1412/fix get widgets

- lib/URLHelper.php
- tests/test-timber-url-helper.php
**Ticket**: #1403 #1448 
Adds a test to cover port handling
> Nixonnixon master

- lib/URLHelper.php
> Fixed bug in "prepend_to_url" and "remove_double_slashes"

- docs/wiki/_extending-timber.md
fixed minor misspelling in the documentation part **Adding to Twig**
> Documention - fixed minor misspelling

- docs/getting-started/setup.md
- docs/getting-started/themeing.md
- docs/getting-started/twig-tools.md
- docs/getting-started/video-tutorials.md
- docs/guides/acf-cookbook.md
- docs/guides/cheatsheet.md
- docs/guides/cookbook-images.md
- docs/guides/cookbook-text.md
- docs/guides/cookbook-twig.md
- docs/guides/custom-page-templates.md
- docs/guides/debugging.md
- docs/guides/escapers.md
- docs/guides/extending-timber.md
- docs/guides/filters.md
- docs/guides/functions.md
- docs/guides/internationalization.md
- docs/guides/pagination.md
- docs/guides/performance.md
- docs/guides/routing.md
- docs/guides/sidebars.md
- docs/guides/template-locations.md
- docs/guides/testing.md
- docs/guides/woocommerce.md
- docs/guides/wp-integration.md
- docs/upgrade-guides/1.0.md
Resolved merge conflict in #1483
> Gchtr docs/prepare

- lib/Image/Operation/Resize.php
**Ticket**: # 
unused variables in run_animated_gif method of Resize
remove unused variables in run_animated_gif method of Resize
> clean(resize_image): remove unused variables

- docs/guides/template-locations.md
- Improve structure
This commit also deprecates the wiki page about custom template locations.
**Reviewer**: @jarednova
> Update documentation for Template Locations

- docs/guides/custom-page-templates.md
- Fix links
This commit also deprecates the wiki page about custom page templates.
**Reviewer**: @jarednova
> Update documentation for Custom Page Templates

- README.md
- readme.txt
Although a redirection is in place, it’s probably better to use the correct links in the Readme.
> Update Readme: Use correct links for documentation, update documentation section

- readme.txt
- tests/test-timber-url-helper.php
**Ticket**: #1513 
This creates a test to verify the fix in #1513
> ref #1513 -- created failing test

- .gitignore
- lib/Post.php
- lib/PostGetter.php
- tests/test-timber-post.php
**Ticket**: #1488
Described in the ticket
Described in the ticket
Impact 1.5-2x speed
new method 
```
\Timber\Post::css_class($class = '')
```
Magic usage
```
$post = new \Timber\Post();
$post->class;
// or 
$post->class('additional-css-class');
```
Existing tests should pass
> Critical performance bug fixes

- lib/PostCollection.php
- lib/PostsIterator.php
Tweaks to #1514 to ensure tests run
> 1514/gchtr integrations/post collection

- docs/getting-started/twig-tools.md
Shamelessly added my own plugin to the tools list with a new heading called WordPress tools.
> Added section for WordPress tools

- docs/guides/functions.md
Twig_Function is an abstract class and can thus not be instantiated.
**Ticket**: #
> Twig_Function: Use Twig_SimpleFunction instead.

- docs/guides/testing.md
Merge remaining content of wiki/testing into docs
> Updated testing doc with info from the wiki

- lib/MenuItem.php
**Ticket**: #1569 
Scrutinizer flagged an ambiguous conditional to clarify ...
> ref #1569 -- more thorough check for menu children

- lib/MenuItem.php
- tests/test-timber-menu.php
> tests to ensure menu leveling is working

- lib/Post.php
- readme.txt
- tests/test-timber-post.php
> Marciojc post format

- lib/Post.php
- tests/test-timber-post.php
**Ticket**: # 
Can't get the gallery, video and audio by timber post
Create new methods
Add gallery
- applying get_post_galleries
Add video
- applying get_media_embedded_in_content
Add audio
- applying get_media_embedded_in_content
> Add gallery, audio and video

- lib/Integrations/ACF.php
- lib/Post.php
- readme.txt
- tests/test-timber-integrations.php
**Ticket**: #1599 
Test and cleanup for #1599, #1597
> Palmiak get field object

- lib/PostGetter.php
- tests/test-timber.php
> Multiplylabs issue 1660

- docs/getting-started/setup.md
- docs/guides/cookbook-images.md
- docs/guides/cookbook-text.md
- docs/guides/functions.md
- docs/guides/internationalization.md
- docs/guides/performance.md
- docs/guides/wp-integration.md
**Ticket**: #1676 #1646 
... this is the easy way
> ref #1676 -- there's also the simple way

- README.md
Made some tweaks to the readme
> Updated some readme links and language

- lib/Post.php
- tests/test-timber-post.php
**Ticket**: #1712
... organized @braican's PR so that a method to check if post was in "preview" mode could handle that logic in one place
> 1712 preview mode custom fields

- docs/guides/menus.md
- lib/Menu.php
- readme.txt
- tests/test-timber-menu.php
**Ticket**: #1716 
Some tweaks to @acobster's PR ...
* Remove `get_` from public methods
* Use `null` as the default to return all values rather than `-1`
> Sitecrafting feature/get current item

- .scrutinizer.yml
Update `.scrutinizer.yml` to use new settings as recommended by the service
> update scrutinizer file with new config

- .scrutinizer.yml
- composer.json
Per instructions on:  https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/analyzing-wordpress
> Add setup for WP dependency

- lib/Image.php
> Check for // instead of ://

- lib/PostPreview.php
A little bit more documentation because I had to read the source-Code to understand how to use it.
> Update PostPreview Dokumentation

- lib/Post.php
- lib/PostsIterator.php
- Posts can now clean up after themselves with a teardown method
- PostsIterator calls the teardown method of the post before looping to next item
> Added teardown method, added new postsiterator

- lib/Post.php
- lib/PostsIterator.php
- lib/Setupable.php
- tests/test-timber-post-iterator.php
- Added Interface for setup & teardown method
- Added test for `$wp_query->in_the_loop` (Not yet working)
> 2.x context revision

- lib/Attachment.php
- lib/Image.php
- tests/test-timber-attachment.php
I totally screwed up something attempting to merge #1788 into #1789, this fixes the screw-up
> resolved changes between #1789 and #1788

- lib/Timber.php
@gchtr I removed the two almost empty methods in the `Timber` class
> Removed almost empty methods

- lib/Image.php
Update documentation
lib/Image
> Update Image documentation

- lib/Archives.php
- lib/Comment.php
Update documentation
Change the documentation
> WIP: Documentation

- lib/Attachment.php
- lib/CommentThread.php
- lib/Image.php
- lib/ImageHelper.php
Update documentation
- Attachment
- CommentThread
- Image
- ImageHelper
> Documentation v2

- lib/Image/Operation/ToWebp.php
- lib/ImageHelper.php
Added some documentation clarification based on problems supported in #1849
> ref #1849 -- add docs to clarify WEBP behaviors

- README.md
Discolure: I'm the author of this project :)
> Add Timber WebLink Extension to "related projects"

- docs/upgrade-guides/2.0.md
**Ticket**: #1860 
Just fixing a couple @todo links in the docs to sections I know are there in 2.x.
> #1860 add a couple links in the docs

- docs/guides/routing.md
First off, hello! Thanks for submitting a PR. We love/welcome PRs (especially if it's your first). Have any questions? Read [this section in CONTRIBUTING.md](https://github.com/timber/timber/blob/master/CONTRIBUTING.md#pull-requests) 
Just added another routing library.
> Added cortex to routing docs

- .travis.yml
- lib/ImageHelper.php
- lib/Pagination.php
- lib/TextHelper.php
- readme.txt
- tests/test-timber-pagination.php
Review @gchtr's changes on pagination
> Escape pagination

- lib/Helper.php
- lib/Post.php
- tests/test-timber-helper.php
- tests/test-timber-integrations.php
Similar to  https://github.com/timber/timber/pull/1439
On a relationship, repeater and Post Object field, Timber returns an array with instances of TimberPost (only). I find it useful to also return a TimberTerm or TimberUser if get_field returns a WP_Term or WP_User.
Make a helper function that checks for the instance of the given class and returns the equivalent timber class. Ex. Given a WP_Post, a \Timber\Post will be returned
get_field() on a repeater/taxonomy/etc which returns WP_Term's while on Twig will now return a \Timber\Term, same for WP_User. No impact for WP_Post, as it works the same way as before.
I find that the second argument of convert() was no longer necessary.
Second argument of convert() was no longer necessary, so it was removed.
The helper function could be …
> Enable Post::convert() to convert WP_Posts, WP_Term and WP_User

- README.md
- docs/guides/debugging.md
**Ticket**: #1852
Add @boris-djemrovski’s [Timber Debugger](https://github.com/djboris88/timber-debugger) package in the README and the Debugging Guide.
> Add Timber Debugger

- README.md
- docs/guides/debugging.md
- docs/guides/gutenberg.md
- lib/Twig.php
- tests/test-timber-twig-filters.php
> Fix `list` filter being too opinionated about its `second_delimiter`

- lib/Comment.php
- lib/Menu.php
- lib/Term.php
- lib/Timber.php
- lib/Twig.php
Address a few issues flagged by Scrutinizer
> Quick Scrutinizer Fixes

- lib/Helper.php
- tests/assets/Sport.php
- tests/test-timber-helper.php
This condenses the commits in #1876 — I think there's some craziness going on over there.
> Add support for class maps in converting wp to Timber objects

- lib/Timber.php
**Ticket**: #1877
Let’s add a call to `Helper::deprecated()` to be extra bugging.
> Ref #1877 – Add deprecation error message

- lib/URLHelper.php
- tests/test-timber-url-helper.php
> Fix is_external returning false for protocol-less URLs

- docs/getting-started/twig-tools.md
I've open sourced the premium version of the Lisa Templates plugin upon request from a friendly user. 😉
It's been given a new life on GitHub and I've added the repository link in the documentation.
**Ticket**: #
> Re-added Lisa Templates.

- .github/CODEOWNERS
> 2.x Add CODEOWNERS file

- .github/CODEOWNERS
- .github/SUPPORT.md
- CONTRIBUTING.md
Clarify PR process both for maintainers and contributors
Codify what we're already doing and clarify a few questions (at least, ones I've had in my mind).
Hopefully makes things smoother and easier
I'm really interested in best practices from both people's day jobs and other open source projects. I hope this clarifies who should take certain PRs that come in and the best ways to handle. I don't have strong beliefs about this stuff — but I do want to figure out how to reduce any (potential) confusion so we can focus on the codez and not "wait, who's supposed to be doing that?"
> Update CONTRIBUTING with PR process proposal

- docs/guides/woocommerce.md
**Ticket**: #1936 
- New section about Theme Developer Handbook mentioned in https://github.com/timber/timber/pull/1936#issuecomment-470272909
- Some small fixes, like bold file names and the language tag for the fenced code block.
> Ref #1936 – Update WooCommerce guide

- .editorconfig
- docs/getting-started/theming.md
- docs/guides/acf-cookbook.md
- docs/guides/cheatsheet.md
- docs/guides/cookbook-images.md
- docs/guides/gutenberg.md
- docs/guides/menus.md
- docs/guides/pagination.md
- docs/guides/performance.md
- docs/guides/sidebars.md
- docs/guides/woocommerce.md
- docs/guides/wp-integration.md
- lib/Helper.php
- lib/Image.php
- lib/Post.php
- lib/Site.php
- lib/Theme.php
- lib/Timber.php
- tests/test-timber-context.php
- tests/test-timber-function-wrapper.php
- tests/test-timber-gettext.php
- tests/test-timber-hooks.php
- tests/test-timber-menu.php
- tests/test-timber-request.php
- tests/test-timber-sidebar.php
- tests/test-timber-site.php
- tests/test-timber-theme.php
- tests/test-timber.php
As Timber::get_context() will be deprecated, I updated the documentation to the new Timber::context()
> Update documentation to use Timber::context

- lib/PostGetter.php
@gchtr caught a typo in #1813 which this fixes
> ref #1813 -- suppress spelling fixed

- tests/test-timber-post.php
**Ticket**: #1900
Same as #1900, but for the `master` branch.
> Fix failing test

- .travis.yml
- README.md
#2027 
New Travis PRs are failing. Did something change? This is to test whether a minor change to the readme triggers failing Travis tests.
- If tests fail: bad news. Tests work sometimes, but not other times. Why? Could be quite a rabbit hole
- If tests pass: good news! There's probably a change in those PRs we're overlooking that's causing failure
> small change to readme in order to kick Travis tests into gear

- .travis.yml
Updating to a more precise config for Travis based on info from:
https://travis-ci.community/t/prs-started-failing-on-6-12/3707/4
> Updated YML based on feedback from Travis team

- .travis.yml
**Ticket**: #2030
Instead of updating every open pull request for 2.x with the updated Travis configuration, let’s pull the update into 2.x and then update all base branches in the open pull requests.
> 2.x Update .travis.yml

- lib/Twig.php
**Ticket**: #2081 
This is a backport of #2070 into master
Copy-pasta!
There could be some merge conflicts with the identical code from 2.x
> Bring in fix for #2070 into master

- docs/guides/template-locations.md
- docs/upgrade-guides/2.0.md
- lib/Loader.php
- lib/LocationManager.php
- tests/test-timber-loader.php
fixes : https://github.com/timber/timber/issues/1837
-------
Feedback welcome!
> deprecated timber/loader/paths in favor of timber/locations

- tests/test-timber-pagination.php
> wrote a test for #1459

- lib/PathHelper.php
I found some work locally that I didn’t push yet :).
This pull request improves the inline documentation and coding standards for `Timber\PathHelper`.
Better looking documentation.
None.
None.
None needed.
> Improve inline documentation for Timber\PathHelper

- .travis.yml
- lib/Image/Operation.php
- tests/test-timber-post.php
#2132 Update Travis and tests to successfully test against PHP 7.4
> Use PHP 7.2 and 7.4

- tests/test-timber-integration-acf.php
Just a quick test to confirm that the issue in #2142 _doesn't_ happen in 2.x!
> Add test for #2143 for current 2.x behavior

- .travis.yml
- lib/ImageHelper.php
- phpstan.neon
- tests/phpstan/bootstrap.php
Resolves merge conflict from #2164
> Szepeviktor phpstan level 1

- lib/Factory/UserFactory.php
- lib/Timber.php
**Ticket**: #2160
This pull request improves the DocBlocks for the new User API and the User Class Map, so that they will properly appear in the online documentation.
> 2.x User factories DocBlocks

- docs/guides/posts.md
* clarify that you don't need to call `->to_array()` to loop
* clarify distinctions from core `get_posts` and `WP_Query`
* edit style for clarity, conciseness :)
> Clarify PostCollection semantics (docs only)

- .gitattributes
> Do not distribute development files

- docs/guides/routing.md
**Ticket**: #2182
Changing name of variable in routing docs.
Changed name of variable in routing docs.
> 2182 DOCfix

- lib/User.php
- tests/test-timber-post.php
- tests/test-timber-term-getter.php
- tests/test-timber-user.php
Fix the issue and apply tests based on #2187
> Correct return type of User::$id and apply tests to objects

- tests/test-timber-image.php
Clean up the tests by clearing out the uploads dir after every run
> Clear out uploads directory after every test run

- tests/test-timber-theme.php
Upgrade tests to use Twenty Seventeen theme to test against (as WP 5.4 no longer includes `twentysixteen`)
> Upgrade theme to test against to Twenty Seventeen

- lib/PostType.php
**Ticket**: #2185 
The possible bug was described in the issue. All in all there was one check missing for Timber/PostType.
Just added the check is `! empty()`.
It shouldn't have any impact.
No changes.
> #2185 post type extra check

- .travis.yml
- composer.json
- lib/User.php
- tests/test-timber-user.php
> Flip111 patch 1

- composer.json
**Ticket**: #2235
@jarednova summoned me
> Fix autoloading causing unit test errors

- composer.json
Test an upgrade of PHPUnit versions
> Upgrade PHPUnit version

- .travis.yml
> Use speedy pcov instead of xdebug

- .travis.yml
Test to apply #2257 to the current master ...
> Apply @szepeviktor's fix to 1.x

- .travis.yml
- composer.json
- phpunit-nocover.xml
- phpunit.xml
See https://github.com/codecov/codecov-bash/blob/master/codecov#L145
That stray "coveralls" was there for 5 months!
"after_success" executes first.
> codecov should make tests fail

- .travis.yml
> codecov should make tests fail v1

- readme.txt
Adding some support info to the readme. But really using it as a quick test to see if Codecov is disabled or not
> Add support blurb to readme

- .travis.yml
Fixes #2288
🙊 
> When your CI is building in parallel, you’ll want your coverage results to be merged after all have completed.
> Make Coveralls merge our 3 coverage reports

- .travis.yml
From one side it is nice, from another side it is ugly
Now what??
> Remove all conditionals from CI configuration

- .travis.yml
- README.md
- docs/guides/hosts-servers.md
- lib/ImageHelper.php
- lib/Loader.php
- tests/test-timber-multisite.php
- tests/test-timber-wp-vip.php
Addresses merge conflicts with merging `master` into `2.x` — wanted to confirm success before pulling into #1617
> 2.x july27 merge conflicts

- .travis.yml
> Modernize and indent Travis config

- lib/ImageHelper.php
- tests/test-timber-image-helper.php
> Oxyc issue 2216

- .travis.yml
From https://github.com/timber/timber/pull/2319#issuecomment-683980238
@jarednova Here we(bp) go!
> Run WebP related tests also

- .travis.yml
Just naming them :)
Looks good!
> Name CI jobs

- .travis.yml
- composer.json
Travis switched its version of Composer which means there are a few things to chase down in our `composer.json` file
> Upgrade to Composer 2.x

- docs/v2/upgrade-guides/2.0.md
**Ticket**: #2354, #2073
There’s an outstanding issue to document the changes made in #2354.
Add the relevant content to the upgrade guide.
None.
None.
?
None needed.
> 2.x Add upgrade documentation for THE PURGE

- README.md
Hello all, I have been using Timber for a good while and recently I've noticed that there is a projects that use Timber section and I would like to add my theme template that I've put together with Timber and has gotten me and my team through quite a few Wordpress projects.
The template is called [Hozokit and is available here on GitHub](https://github.com/csalmeida/hozokit). I am not sure what the requirements are for a project to be added to the list but I still work on it frequently and its always evolving so thought I would let you know and would deeply appreciate if it becomes part of this list.
Thank you very much!
**Ticket**: N/A # 
No real issue, just requesting to add [Hozokit](https://github.com/csalmeida/hozokit) to the projects that use Timber list.
Adding a line to …
> Adds Hozokit to the projects list

- docs/v2/guides/cookbook-images.md
- docs/v2/guides/custom-fields.md
- docs/v2/guides/performance.md
- docs/v2/guides/sidebars.md
- docs/v2/guides/terms.md
- docs/v2/guides/wp-integration.md
- docs/v2/integrations/advanced-custom-fields.md
- lib/Comment.php
- lib/PostQuery.php
I found several instances where we forgot to use the new API.
Switch to new API in documentation where needed.
No confusion.
None.
None.
None, documentation only.
> 2.x Fix various instances of direct object instantiation

- lib/Timber.php
**Ticket**: #2385
Missing default value
Add a default value to the missing required value
> #2385 - PHP 8 Add default value to required parameter

- .travis.yml
**Ticket**: I have only a speeding ticket.
> Remove PHP 5.6 remnants from Travis config

- .travis.yml
an AMD microarchitecture
https://en.wikipedia.org/wiki/ARM_Cortex-A76#Neoverse_N1
Please see https://twitter.com/szepeviktor/status/1347000358455791616
> Run CI on Graviton

- .gitignore
- lib/Image.php
- readme.txt
- tests/test-timber-image.php
- tests/test-timber-theme.php
The results of tests and updates to #2421 from my local
> SVGs: Updates to #2421

- docs/v2/guides/date-time.md
When working with dates that have no times, the time zone is still relevant. When a datetime object is created, `wp_timezone()` should still be used. This was not mentioned in the Date/Time Guide before.
Improve section about working with dates that have no times and some other parts that are related to this.
None.
None.
None.
None.
> 2.x Improve Date/Time Guide

- README.md
**Ticket**: # 
The link to Twig was returning a 404.
I updated the new link in the readme
> Update the readme with new link to Twig

- .editorconfig
- .github/workflows/test.yml
- CONTRIBUTING.md
- bin/install-wp-tests.sh
- composer.json
- tests/bootstrap.php
- tests/test-timber-image-resize.php
Here's the 2.x version of Github Actions (basically the same as #2415). #2414
> Github Actions tests (2.x)

- .travis.yml
- README.md
Current tests against `master` fail due to a setup error during the WebP tests. A starting hypothesis is that the `PREFER_LOWEST` might be the issue
https://app.travis-ci.com/github/timber/timber/jobs/536572310
> Don't prefer lowest for WebP tests

- README.md
Nico should really be an official Timber contributor.
Make it so!
@nlemoine do you want to link out to your website? Twitter? Instagram?
> Adds @nlemoine to the contribs list!

- lib/Timber.php
- Remove the Twig check, 2.x is now a pure PHP package
- Update PHP check
> Update compatibility checks

- docs/v2/guides/context.md
- docs/v2/guides/extending-timber.md
- docs/v2/guides/menus.md
- docs/v2/guides/posts.md
- docs/v2/guides/users.md
- docs/v2/upgrade-guides/2.0.md
- lib/Factory/CommentFactory.php
- lib/Factory/PostFactory.php
- lib/Factory/TermFactory.php
- lib/Factory/UserFactory.php
- lib/Timber.php
- tests/test-comment-factory.php
- tests/test-post-factory.php
- tests/test-term-factory.php
- tests/test-timber-attachment.php
- tests/test-timber-image.php
- tests/test-timber-pages.php
- tests/test-timber-post.php
- tests/test-timber.php
- tests/test-user-factory.php
> 2.0 Use `null` instead of `false` as return type in factories

- .github/ISSUE_TEMPLATE/1x_release_checklist.md
This adds a release checklist as suggested by @szepeviktor :) — duh!
https://github.com/timber/timber/pull/2595#issuecomment-1163832290
> Add release checklist

- .git-blame-ignore-revs
- src/CoreEntity.php
- src/Helper.php
- src/Loader.php
- tests/test-timber-helper.php
- tests/test-timber-integration-wpml.php
- tests/test-timber-twig.php
Some coding standards issues that causes errors in other pull request.
Fix them.
None.
> 2.x Fix some coding standard issues

- src/Integration/AcfIntegration.php
Restore `add_filter` priority & arguments
> Fix AcfIntegration

- phpstan.neon
- src/CoreEntity.php
- src/Factory/PagesMenuFactory.php
- src/Image.php
- src/ImageHelper.php
- src/Integration/AcfIntegration.php
- src/Loader.php
- src/LocationManager.php
- src/Post.php
- src/PostExcerpt.php
- src/Timber.php
- tests/test-timber-post.php
There are various issues raised by PHPStan on level 0.
This pull request resolves some of them. Other issues will be resolved in separate pull requests.
- #2631
- #2660
- #2664
More robust code.
Some return type changes.
Should be covered through existing tests.
Except the new return types, which we should add tests for. Coverage shrinked because of this.
> 2.x Fix PHPStan issues on level 0

- src/Helper.php
No need to use 'his' here. I'd like to think of code of something neutral.
> Make comment neutral.

- README.md
Erik was not on the contributors list.
Let's fix it!
Erik will join a group of legends
Is there a social media or other that Erik would prefer to link to?
> Add Erik to Contributors List

- docs/v2/getting-started/a-single-post.md
- docs/v2/guides/functions.md
Related:
- #2745 
- https://github.com/timber/timber/pull/2746
Two final missing links.
First should be fixed by #2746. the second one is fixed in this PR. I'll keep this PR in draft until we know for sure that the mentioned PR fixes the missing Reference guide and thus fixing the link.
> 2745 link checker report

- docs/v2/upgrade-guides/2.0.md
Related:
- #2750
Missing note in the Upgrade Guide about a breaking change.
Update Upgrade Guide.
See #2750.
> 2.x Update Upgrade Guide for #2750

- docs/v2/getting-started/a-post-archive.md
- docs/v2/getting-started/introduction.md
- docs/v2/getting-started/template-inheritance-and-includes.md
Related:
- #2278 
I initially wanted to add test for the different code snippets. But this seems a little too tedious. Most of the functionality used there is already tested elsewhere.
Still, I found some details to fix.
Fix some smaller issues.
None.
None.
None.
No.
> 2.x Fix some small issues in Getting Started docs

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- composer.json
- docs/v1/getting-started/setup.md
- docs/v1/getting-started/switch-to-composer.md
Related:
- #2820
- #2800
This PR merges in documentation updates we made for 1.x.
> 2.x Merge master branch
